; RUN-INPUTS: 0x0*256
; RUN-REPEAT: 50
source_filename = "known-miscompiles/m058-nibble-bytesel-highbit/reduced.ll"
target datalayout = "e-m:e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128:128:48-p9:192:256:256:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9"
target triple = "amdgcn-amd-amdhsa"

; Function Attrs: convergent nounwind
define amdgpu_kernel void @fuzz_kernel(ptr addrspace(1) %in, ptr addrspace(1) %out) #0 {
entry:
  %wg = call i32 @llvm.amdgcn.workgroup.id.x()
  %wi = call i32 @llvm.amdgcn.workitem.id.x()
  %block.base = mul i32 %wg, 256
  %idx = add i32 %block.base, %wi
  %idx64 = zext i32 %idx to i64
  %in.ptr = getelementptr i32, ptr addrspace(1) %in, i64 %idx64
  %v = load i32, ptr addrspace(1) %in.ptr, align 4
  %salt = mul i32 %idx, -1640531527
  %mix = xor i32 %v, %salt
  %out.ptr = getelementptr i32, ptr addrspace(1) %out, i64 %idx64
  %fuzz.load.idx64 = zext i32 0 to i64
  %fuzz.load.ptr = getelementptr i32, ptr addrspace(1) %in, i64 %fuzz.load.idx64
  %fuzz.load.value = load i32, ptr addrspace(1) %fuzz.load.ptr, align 4
  %fuzz.load.sub = sub i32 %fuzz.load.value, %mix
  br label %fuzz.loop.header

fuzz.loop.header:                                 ; preds = %fuzz.loop.continue, %entry
  %fuzz.loop.iv = phi i32 [ 0, %entry ], [ %fuzz.loop.next, %fuzz.loop.continue ]
  %fuzz.loop.acc = phi i32 [ %fuzz.load.sub, %entry ], [ %fuzz.cfg.maskshift.shl, %fuzz.loop.continue ]
  %fuzz.loop.cond = icmp ult i32 %fuzz.loop.iv, 6
  %fuzz.cfg.soverflow.idiom.sub.flag.ssub = sub i32 %fuzz.loop.acc, 31
  %fuzz.cfg.soverflow.idiom.sub.flag.ssub.abxor = xor i32 %fuzz.loop.acc, 31
  %fuzz.cfg.soverflow.idiom.sub.flag.ssub.flip = xor i32 %fuzz.loop.acc, %fuzz.cfg.soverflow.idiom.sub.flag.ssub
  %fuzz.cfg.soverflow.idiom.sub.flag.ssub.ovbits = and i32 %fuzz.cfg.soverflow.idiom.sub.flag.ssub.abxor, %fuzz.cfg.soverflow.idiom.sub.flag.ssub.flip
  %fuzz.cfg.soverflow.idiom.sub.flag.ssub.ov = icmp slt i32 %fuzz.cfg.soverflow.idiom.sub.flag.ssub.ovbits, -941812744
  %fuzz.cfg.soverflow.idiom.sub.flag.ssub.neg = icmp slt i32 %fuzz.loop.acc, 0
  %fuzz.cfg.soverflow.idiom.ssub.ov.i32 = zext i1 %fuzz.cfg.soverflow.idiom.sub.flag.ssub.ov to i32
  %fuzz.cfg.soverflow.idiom.ssub.add = add i32 %fuzz.cfg.soverflow.idiom.sub.flag.ssub, %fuzz.cfg.soverflow.idiom.ssub.ov.i32
  %fuzz.cfg.maskshift.shift.mask = and i32 7, 31
  %fuzz.cfg.maskshift.shl = shl i32 %fuzz.cfg.soverflow.idiom.ssub.add, %fuzz.cfg.maskshift.shift.mask
  %fuzz.loop.break = icmp uge i32 %fuzz.cfg.maskshift.shl, 0
  br i1 %fuzz.loop.break, label %fuzz.loop.exit, label %fuzz.loop.continue

fuzz.loop.continue:                               ; preds = %fuzz.loop.header
  %fuzz.loop.next = add i32 %fuzz.loop.iv, 1
  br label %fuzz.loop.header

fuzz.loop.exit:                                   ; preds = %fuzz.loop.header
  %fuzz.nibbletable.idiom.nib.shr = lshr i32 %fuzz.cfg.maskshift.shl, 0
  %fuzz.nibbletable.idiom.nib = and i32 %fuzz.nibbletable.idiom.nib.shr, 15
  %fuzz.nibbletable.idiom.case = icmp eq i32 %fuzz.nibbletable.idiom.nib, 0
  %fuzz.nibbletable.idiom.entry = select i1 %fuzz.nibbletable.idiom.case, i32 91, i32 168
  %fuzz.nibbletable.idiom.case1 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 1
  %fuzz.nibbletable.idiom.entry2 = select i1 %fuzz.nibbletable.idiom.case1, i32 127, i32 %fuzz.nibbletable.idiom.entry
  %fuzz.nibbletable.idiom.case3 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 2
  %fuzz.nibbletable.idiom.entry4 = select i1 %fuzz.nibbletable.idiom.case3, i32 86, i32 %fuzz.nibbletable.idiom.entry2
  %fuzz.nibbletable.idiom.case5 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 3
  %fuzz.nibbletable.idiom.entry6 = select i1 %fuzz.nibbletable.idiom.case5, i32 89, i32 %fuzz.nibbletable.idiom.entry4
  %fuzz.nibbletable.idiom.case7 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 4
  %fuzz.nibbletable.idiom.entry8 = select i1 %fuzz.nibbletable.idiom.case7, i32 249, i32 %fuzz.nibbletable.idiom.entry6
  %fuzz.nibbletable.idiom.case9 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 5
  %fuzz.nibbletable.idiom.entry10 = select i1 %fuzz.nibbletable.idiom.case9, i32 178, i32 %fuzz.nibbletable.idiom.entry8
  %fuzz.nibbletable.idiom.case11 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 6
  %fuzz.nibbletable.idiom.entry12 = select i1 %fuzz.nibbletable.idiom.case11, i32 26, i32 %fuzz.nibbletable.idiom.entry10
  %fuzz.nibbletable.idiom.case13 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 7
  %fuzz.nibbletable.idiom.entry14 = select i1 %fuzz.nibbletable.idiom.case13, i32 144, i32 %fuzz.nibbletable.idiom.entry12
  %fuzz.nibbletable.idiom.case15 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 8
  %fuzz.nibbletable.idiom.entry16 = select i1 %fuzz.nibbletable.idiom.case15, i32 198, i32 %fuzz.nibbletable.idiom.entry14
  %fuzz.nibbletable.idiom.case17 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 9
  %fuzz.nibbletable.idiom.entry18 = select i1 %fuzz.nibbletable.idiom.case17, i32 71, i32 %fuzz.nibbletable.idiom.entry16
  %fuzz.nibbletable.idiom.case19 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 10
  %fuzz.nibbletable.idiom.entry20 = select i1 %fuzz.nibbletable.idiom.case19, i32 75, i32 %fuzz.nibbletable.idiom.entry18
  %fuzz.nibbletable.idiom.case21 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 11
  %fuzz.nibbletable.idiom.entry22 = select i1 %fuzz.nibbletable.idiom.case21, i32 153, i32 %fuzz.nibbletable.idiom.entry20
  %fuzz.nibbletable.idiom.case23 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 12
  %fuzz.nibbletable.idiom.entry24 = select i1 %fuzz.nibbletable.idiom.case23, i32 57, i32 %fuzz.nibbletable.idiom.entry22
  %fuzz.nibbletable.idiom.case25 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 13
  %fuzz.nibbletable.idiom.entry26 = select i1 %fuzz.nibbletable.idiom.case25, i32 86, i32 %fuzz.nibbletable.idiom.entry24
  %fuzz.nibbletable.idiom.case27 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 14
  %fuzz.nibbletable.idiom.entry28 = select i1 %fuzz.nibbletable.idiom.case27, i32 27, i32 %fuzz.nibbletable.idiom.entry26
  %fuzz.nibbletable.idiom.case29 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 15
  %fuzz.nibbletable.idiom.entry30 = select i1 %fuzz.nibbletable.idiom.case29, i32 231, i32 %fuzz.nibbletable.idiom.entry28
  %fuzz.nibbletable.idiom.pop = call i32 @llvm.ctpop.i32(i32 %fuzz.nibbletable.idiom.entry30)
  %fuzz.nibbletable.idiom.pop.shl = shl i32 %fuzz.nibbletable.idiom.pop, 1
  %fuzz.nibbletable.idiom.mix.xor = xor i32 %fuzz.nibbletable.idiom.entry30, %fuzz.nibbletable.idiom.pop.shl
  %fuzz.nibbletable.idiom.fold.add = add i32 70, %fuzz.nibbletable.idiom.mix.xor
  %fuzz.nibbletable.idiom.fold.xor = xor i32 %fuzz.nibbletable.idiom.fold.add, %fuzz.nibbletable.idiom.nib
  %fuzz.nibbletable.idiom.nib.shr31 = lshr i32 %block.base, 4
  %fuzz.nibbletable.idiom.nib32 = and i32 %fuzz.nibbletable.idiom.nib.shr31, 15
  %fuzz.nibbletable.idiom.case33 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 0
  %fuzz.nibbletable.idiom.entry34 = select i1 %fuzz.nibbletable.idiom.case33, i32 16, i32 -2147483648
  %fuzz.nibbletable.idiom.case35 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 1
  %fuzz.nibbletable.idiom.entry36 = select i1 %fuzz.nibbletable.idiom.case35, i32 136, i32 %fuzz.nibbletable.idiom.entry34
  %fuzz.nibbletable.idiom.case37 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 2
  %fuzz.nibbletable.idiom.entry38 = select i1 %fuzz.nibbletable.idiom.case37, i32 253, i32 %fuzz.nibbletable.idiom.entry36
  %fuzz.nibbletable.idiom.case39 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 3
  %fuzz.nibbletable.idiom.entry40 = select i1 %fuzz.nibbletable.idiom.case39, i32 129, i32 %fuzz.nibbletable.idiom.entry38
  %fuzz.nibbletable.idiom.case41 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 0
  %fuzz.nibbletable.idiom.entry42 = select i1 %fuzz.nibbletable.idiom.case41, i32 127, i32 %fuzz.nibbletable.idiom.entry40
  %fuzz.nibbletable.idiom.case43 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 5
  %fuzz.nibbletable.idiom.entry44 = select i1 %fuzz.nibbletable.idiom.case43, i32 44, i32 %fuzz.nibbletable.idiom.entry42
  %fuzz.nibbletable.idiom.case45 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 6
  %fuzz.nibbletable.idiom.entry46 = select i1 %fuzz.nibbletable.idiom.case45, i32 254, i32 %fuzz.nibbletable.idiom.entry44
  %fuzz.nibbletable.idiom.case47 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 7
  %fuzz.nibbletable.idiom.entry48 = select i1 %fuzz.nibbletable.idiom.case47, i32 118, i32 %fuzz.nibbletable.idiom.entry46
  %fuzz.nibbletable.idiom.case49 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 8
  %fuzz.nibbletable.idiom.entry50 = select i1 %fuzz.nibbletable.idiom.case49, i32 93, i32 %fuzz.nibbletable.idiom.entry48
  %fuzz.nibbletable.idiom.case51 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 9
  %fuzz.nibbletable.idiom.entry52 = select i1 %fuzz.nibbletable.idiom.case51, i32 140, i32 %fuzz.nibbletable.idiom.entry50
  %fuzz.nibbletable.idiom.case53 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 10
  %fuzz.nibbletable.idiom.entry54 = select i1 %fuzz.nibbletable.idiom.case53, i32 140, i32 %fuzz.nibbletable.idiom.entry52
  %fuzz.nibbletable.idiom.case55 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 11
  %fuzz.nibbletable.idiom.entry56 = select i1 %fuzz.nibbletable.idiom.case55, i32 69, i32 %fuzz.nibbletable.idiom.entry54
  %fuzz.nibbletable.idiom.case57 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 12
  %fuzz.nibbletable.idiom.entry58 = select i1 %fuzz.nibbletable.idiom.case57, i32 134, i32 %fuzz.nibbletable.idiom.entry56
  %fuzz.nibbletable.idiom.case59 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 13
  %fuzz.nibbletable.idiom.entry60 = select i1 %fuzz.nibbletable.idiom.case59, i32 66, i32 %fuzz.nibbletable.idiom.entry58
  %fuzz.nibbletable.idiom.case61 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 14
  %fuzz.nibbletable.idiom.entry62 = select i1 %fuzz.nibbletable.idiom.case61, i32 103, i32 %fuzz.nibbletable.idiom.entry60
  %fuzz.nibbletable.idiom.case63 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 15
  %fuzz.nibbletable.idiom.entry64 = select i1 %fuzz.nibbletable.idiom.case63, i32 10, i32 %fuzz.nibbletable.idiom.entry62
  %fuzz.nibbletable.idiom.pop65 = call i32 @llvm.ctpop.i32(i32 %fuzz.nibbletable.idiom.entry64)
  %fuzz.nibbletable.idiom.pop.shl66 = shl i32 %fuzz.nibbletable.idiom.pop65, 2
  %fuzz.nibbletable.idiom.mix.xor67 = xor i32 %fuzz.nibbletable.idiom.entry64, %fuzz.nibbletable.idiom.pop.shl66
  %fuzz.nibbletable.idiom.fold.add68 = add i32 %fuzz.nibbletable.idiom.fold.xor, %fuzz.nibbletable.idiom.mix.xor67
  %fuzz.nibbletable.idiom.fold.xor69 = xor i32 %fuzz.nibbletable.idiom.fold.add68, %fuzz.nibbletable.idiom.nib32
  %fuzz.nibbletable.idiom.nib.shr70 = lshr i32 %fuzz.cfg.maskshift.shl, 8
  %fuzz.nibbletable.idiom.nib71 = and i32 %fuzz.nibbletable.idiom.nib.shr70, 15
  %fuzz.nibbletable.idiom.case72 = icmp eq i32 %fuzz.nibbletable.idiom.nib71, 0
  %fuzz.nibbletable.idiom.entry73 = select i1 %fuzz.nibbletable.idiom.case72, i32 172, i32 143
  %fuzz.nibbletable.idiom.case74 = icmp eq i32 %fuzz.nibbletable.idiom.nib71, 1
  %fuzz.nibbletable.idiom.entry75 = select i1 %fuzz.nibbletable.idiom.case74, i32 164, i32 %fuzz.nibbletable.idiom.entry73
  %fuzz.nibbletable.idiom.case76 = icmp eq i32 %fuzz.nibbletable.idiom.nib71, 2
  %fuzz.nibbletable.idiom.entry77 = select i1 %fuzz.nibbletable.idiom.case76, i32 26, i32 %fuzz.nibbletable.idiom.entry75
  %fuzz.nibbletable.idiom.case78 = icmp eq i32 %fuzz.nibbletable.idiom.nib71, 3
  %fuzz.nibbletable.idiom.entry79 = select i1 %fuzz.nibbletable.idiom.case78, i32 196, i32 %fuzz.nibbletable.idiom.entry77
  %fuzz.nibbletable.idiom.case80 = icmp eq i32 %fuzz.nibbletable.idiom.nib71, 4
  %fuzz.nibbletable.idiom.entry81 = select i1 %fuzz.nibbletable.idiom.case80, i32 249, i32 %fuzz.nibbletable.idiom.entry79
  %fuzz.nibbletable.idiom.case82 = icmp eq i32 %fuzz.nibbletable.idiom.nib71, 5
  %fuzz.nibbletable.idiom.entry83 = select i1 %fuzz.nibbletable.idiom.case82, i32 255, i32 %fuzz.nibbletable.idiom.entry81
  %fuzz.nibbletable.idiom.case84 = icmp eq i32 %fuzz.nibbletable.idiom.nib71, 6
  %fuzz.nibbletable.idiom.entry85 = select i1 %fuzz.nibbletable.idiom.case84, i32 220, i32 %fuzz.nibbletable.idiom.entry83
  %fuzz.nibbletable.idiom.case86 = icmp eq i32 %fuzz.nibbletable.idiom.nib71, 7
  %fuzz.nibbletable.idiom.entry87 = select i1 %fuzz.nibbletable.idiom.case86, i32 22, i32 %fuzz.nibbletable.idiom.entry85
  %fuzz.nibbletable.idiom.case88 = icmp eq i32 %fuzz.nibbletable.idiom.nib71, 8
  %fuzz.nibbletable.idiom.entry89 = select i1 %fuzz.nibbletable.idiom.case88, i32 134, i32 %fuzz.nibbletable.idiom.entry87
  %fuzz.nibbletable.idiom.case90 = icmp eq i32 %fuzz.nibbletable.idiom.nib71, 9
  %fuzz.nibbletable.idiom.entry91 = select i1 %fuzz.nibbletable.idiom.case90, i32 59, i32 %fuzz.nibbletable.idiom.entry89
  %fuzz.nibbletable.idiom.case92 = icmp eq i32 %fuzz.nibbletable.idiom.nib71, 10
  %fuzz.nibbletable.idiom.entry93 = select i1 %fuzz.nibbletable.idiom.case92, i32 227, i32 %fuzz.nibbletable.idiom.entry91
  %fuzz.nibbletable.idiom.case94 = icmp eq i32 %fuzz.nibbletable.idiom.nib71, 11
  %fuzz.nibbletable.idiom.entry95 = select i1 %fuzz.nibbletable.idiom.case94, i32 88, i32 %fuzz.nibbletable.idiom.entry93
  %fuzz.nibbletable.idiom.case96 = icmp eq i32 %fuzz.nibbletable.idiom.nib71, 12
  %fuzz.nibbletable.idiom.entry97 = select i1 %fuzz.nibbletable.idiom.case96, i32 153, i32 %fuzz.nibbletable.idiom.entry95
  %fuzz.nibbletable.idiom.case98 = icmp eq i32 %fuzz.nibbletable.idiom.nib71, 13
  %fuzz.nibbletable.idiom.entry99 = select i1 %fuzz.nibbletable.idiom.case98, i32 99, i32 %fuzz.nibbletable.idiom.entry97
  %fuzz.nibbletable.idiom.case100 = icmp eq i32 %fuzz.nibbletable.idiom.nib71, 14
  %fuzz.nibbletable.idiom.entry101 = select i1 %fuzz.nibbletable.idiom.case100, i32 24, i32 %fuzz.nibbletable.idiom.entry99
  %fuzz.nibbletable.idiom.case102 = icmp eq i32 %fuzz.nibbletable.idiom.nib71, -1398686021
  %fuzz.nibbletable.idiom.entry103 = select i1 %fuzz.nibbletable.idiom.case102, i32 221, i32 %fuzz.nibbletable.idiom.entry101
  %fuzz.nibbletable.idiom.pop104 = call i32 @llvm.ctpop.i32(i32 %fuzz.nibbletable.idiom.entry103)
  %fuzz.nibbletable.idiom.mix.add = add i32 %fuzz.nibbletable.idiom.entry103, %fuzz.nibbletable.idiom.fold.xor69
  %fuzz.nibbletable.idiom.fold.add105 = add i32 %fuzz.nibbletable.idiom.fold.xor69, %fuzz.nibbletable.idiom.mix.add
  %fuzz.nibbletable.idiom.fold.xor106 = xor i32 %fuzz.nibbletable.idiom.fold.add105, %fuzz.nibbletable.idiom.nib71
  %fuzz.nibbletable.idiom.nib.shr107 = lshr i32 %block.base, 12
  %fuzz.nibbletable.idiom.nib108 = and i32 %fuzz.nibbletable.idiom.nib.shr107, 15
  %fuzz.nibbletable.idiom.case109 = icmp eq i32 %fuzz.nibbletable.idiom.nib108, 0
  %fuzz.nibbletable.idiom.entry110 = select i1 %fuzz.nibbletable.idiom.case109, i32 90, i32 108
  %fuzz.nibbletable.idiom.case111 = icmp eq i32 %fuzz.nibbletable.idiom.nib108, 1
  %fuzz.nibbletable.idiom.entry112 = select i1 %fuzz.nibbletable.idiom.case111, i32 5, i32 %fuzz.nibbletable.idiom.entry110
  %fuzz.nibbletable.idiom.case113 = icmp eq i32 %fuzz.nibbletable.idiom.nib108, 2
  %fuzz.nibbletable.idiom.entry114 = select i1 %fuzz.nibbletable.idiom.case113, i32 24, i32 %fuzz.nibbletable.idiom.entry112
  %fuzz.nibbletable.idiom.case115 = icmp eq i32 %fuzz.nibbletable.idiom.nib108, 3
  %fuzz.nibbletable.idiom.entry116 = select i1 %fuzz.nibbletable.idiom.case115, i32 71, i32 %fuzz.nibbletable.idiom.entry114
  %fuzz.nibbletable.idiom.case117 = icmp eq i32 %fuzz.nibbletable.idiom.nib108, 4
  %fuzz.nibbletable.idiom.entry118 = select i1 %fuzz.nibbletable.idiom.case117, i32 2, i32 %fuzz.nibbletable.idiom.entry116
  %fuzz.nibbletable.idiom.case119 = icmp eq i32 %fuzz.nibbletable.idiom.nib108, 5
  %fuzz.nibbletable.idiom.entry120 = select i1 %fuzz.nibbletable.idiom.case119, i32 160, i32 %fuzz.nibbletable.idiom.entry118
  %fuzz.nibbletable.idiom.case121 = icmp eq i32 %fuzz.nibbletable.idiom.nib108, 6
  %fuzz.nibbletable.idiom.entry122 = select i1 %fuzz.nibbletable.idiom.case121, i32 234, i32 %fuzz.nibbletable.idiom.entry120
  %fuzz.nibbletable.idiom.case123 = icmp eq i32 %fuzz.nibbletable.idiom.nib108, 7
  %fuzz.nibbletable.idiom.entry124 = select i1 %fuzz.nibbletable.idiom.case123, i32 219, i32 %fuzz.nibbletable.idiom.entry122
  %fuzz.nibbletable.idiom.case125 = icmp eq i32 %fuzz.nibbletable.idiom.nib108, 8
  %fuzz.nibbletable.idiom.entry126 = select i1 %fuzz.nibbletable.idiom.case125, i32 1, i32 %fuzz.nibbletable.idiom.entry124
  %fuzz.nibbletable.idiom.case127 = icmp eq i32 %fuzz.nibbletable.idiom.nib108, 9
  %fuzz.nibbletable.idiom.entry128 = select i1 %fuzz.nibbletable.idiom.case127, i32 201, i32 %fuzz.nibbletable.idiom.entry126
  %fuzz.nibbletable.idiom.case129 = icmp eq i32 %fuzz.nibbletable.idiom.nib108, 10
  %fuzz.nibbletable.idiom.entry130 = select i1 %fuzz.nibbletable.idiom.case129, i32 52, i32 %fuzz.nibbletable.idiom.entry128
  %fuzz.nibbletable.idiom.case131 = icmp eq i32 %fuzz.nibbletable.idiom.nib108, 11
  %fuzz.nibbletable.idiom.entry132 = select i1 %fuzz.nibbletable.idiom.case131, i32 42, i32 %fuzz.nibbletable.idiom.entry130
  %fuzz.nibbletable.idiom.case133 = icmp eq i32 %fuzz.nibbletable.idiom.nib108, 12
  %fuzz.nibbletable.idiom.entry134 = select i1 %fuzz.nibbletable.idiom.case133, i32 41, i32 %fuzz.nibbletable.idiom.entry132
  %fuzz.nibbletable.idiom.case135 = icmp eq i32 %fuzz.nibbletable.idiom.nib108, 13
  %fuzz.nibbletable.idiom.entry136 = select i1 %fuzz.nibbletable.idiom.case135, i32 41, i32 %fuzz.nibbletable.idiom.entry134
  %fuzz.nibbletable.idiom.case137 = icmp eq i32 %fuzz.nibbletable.idiom.nib108, 14
  %fuzz.nibbletable.idiom.entry138 = select i1 %fuzz.nibbletable.idiom.case137, i32 253, i32 %fuzz.nibbletable.idiom.entry136
  %fuzz.nibbletable.idiom.case139 = icmp eq i32 %fuzz.nibbletable.idiom.nib108, 15
  %fuzz.nibbletable.idiom.entry140 = select i1 %fuzz.nibbletable.idiom.case139, i32 16, i32 %fuzz.nibbletable.idiom.entry138
  %fuzz.nibbletable.idiom.pop141 = call i32 @llvm.ctpop.i32(i32 %fuzz.nibbletable.idiom.entry140)
  %fuzz.nibbletable.idiom.entry.nz = or i32 %fuzz.nibbletable.idiom.entry140, 1
  %fuzz.nibbletable.idiom.mix.sub = sub i32 %fuzz.nibbletable.idiom.entry.nz, %fuzz.nibbletable.idiom.pop141
  %fuzz.nibbletable.idiom.fold.add142 = add i32 %fuzz.nibbletable.idiom.fold.xor106, %fuzz.nibbletable.idiom.mix.sub
  %fuzz.nibbletable.idiom.fold.xor143 = xor i32 %fuzz.nibbletable.idiom.fold.add142, %fuzz.nibbletable.idiom.nib108
  %fuzz.nibbletable.idiom.pack.mask = and i32 %fuzz.nibbletable.idiom.mix.xor, 255
  %fuzz.nibbletable.idiom.pack.or = or i32 0, %fuzz.nibbletable.idiom.pack.mask
  %fuzz.nibbletable.idiom.pack.mask144 = and i32 %fuzz.nibbletable.idiom.mix.xor67, 255
  %fuzz.nibbletable.idiom.pack.shift = shl i32 %fuzz.nibbletable.idiom.pack.mask144, 8
  %fuzz.nibbletable.idiom.pack.or145 = or i32 %fuzz.nibbletable.idiom.pack.or, %fuzz.nibbletable.idiom.pack.shift
  %fuzz.nibbletable.idiom.pack.mask146 = and i32 %fuzz.nibbletable.idiom.mix.add, 255
  %fuzz.nibbletable.idiom.pack.shift147 = shl i32 %fuzz.nibbletable.idiom.pack.mask146, 16
  %fuzz.nibbletable.idiom.pack.or148 = or i32 %fuzz.nibbletable.idiom.pack.or145, %fuzz.nibbletable.idiom.pack.shift147
  %fuzz.nibbletable.idiom.pack.mask149 = and i32 %fuzz.nibbletable.idiom.mix.sub, 255
  %fuzz.nibbletable.idiom.pack.shift150 = shl i32 %fuzz.nibbletable.idiom.pack.mask149, 24
  %fuzz.nibbletable.idiom.pack.or151 = or i32 %fuzz.nibbletable.idiom.pack.or148, %fuzz.nibbletable.idiom.pack.shift150
  %fuzz.nibbletable.idiom.packed.sub = sub i32 %fuzz.nibbletable.idiom.fold.xor143, %fuzz.nibbletable.idiom.pack.or151
  %fuzz.bytesel.idiom.a.byte.trunc = trunc i32 %fuzz.nibbletable.idiom.packed.sub to i8
  %fuzz.bytesel.idiom.a.byte.zext = zext i8 %fuzz.bytesel.idiom.a.byte.trunc to i32
  %fuzz.bytesel.idiom.b.byte.shr = lshr i32 3, 8
  %fuzz.bytesel.idiom.b.byte.trunc = trunc i32 %fuzz.bytesel.idiom.b.byte.shr to i8
  %fuzz.bytesel.idiom.b.byte.zext = zext i8 %fuzz.bytesel.idiom.b.byte.trunc to i32
  %fuzz.bytesel.idiom.xbyte = xor i32 %fuzz.bytesel.idiom.a.byte.zext, %fuzz.bytesel.idiom.b.byte.zext
  %fuzz.bytesel.idiom.ult = icmp ult i32 %fuzz.bytesel.idiom.a.byte.zext, %fuzz.bytesel.idiom.b.byte.zext
  %fuzz.bytesel.idiom.select = select i1 %fuzz.bytesel.idiom.ult, i32 %fuzz.bytesel.idiom.a.byte.zext, i32 %fuzz.bytesel.idiom.b.byte.zext
  %fuzz.bytesel.idiom.rot.lo = shl i32 %fuzz.bytesel.idiom.select, 1
  %fuzz.bytesel.idiom.rot.hi = lshr i32 %fuzz.bytesel.idiom.select, 7
  %fuzz.bytesel.idiom.rot = or i32 %fuzz.bytesel.idiom.rot.lo, %fuzz.bytesel.idiom.rot.hi
  %fuzz.bytesel.idiom.lane = xor i32 %fuzz.bytesel.idiom.rot, 188
  %fuzz.bytesel.idiom.carry.mask = and i32 188, 255
  %fuzz.bytesel.idiom.carry.next = add i32 %fuzz.bytesel.idiom.select, %fuzz.bytesel.idiom.carry.mask
  %fuzz.bytesel.idiom.a.byte.shr = lshr i32 %fuzz.nibbletable.idiom.packed.sub, 8
  %fuzz.bytesel.idiom.a.byte.trunc1 = trunc i32 %fuzz.bytesel.idiom.a.byte.shr to i8
  %fuzz.bytesel.idiom.a.byte.zext2 = zext i8 %fuzz.bytesel.idiom.a.byte.trunc1 to i32
  %fuzz.bytesel.idiom.b.byte.shr3 = lshr i32 3, 16
  %fuzz.bytesel.idiom.b.byte.trunc4 = trunc i32 %fuzz.bytesel.idiom.b.byte.shr3 to i8
  %fuzz.bytesel.idiom.b.byte.zext5 = zext i8 %fuzz.bytesel.idiom.b.byte.trunc4 to i32
  %fuzz.bytesel.idiom.xbyte6 = xor i32 %fuzz.bytesel.idiom.a.byte.zext2, %fuzz.bytesel.idiom.b.byte.zext5
  %fuzz.bytesel.idiom.ugt = icmp ugt i32 %fuzz.bytesel.idiom.xbyte6, %fuzz.bytesel.idiom.carry.next
  %fuzz.bytesel.idiom.select7 = select i1 %fuzz.bytesel.idiom.ugt, i32 %fuzz.bytesel.idiom.a.byte.zext2, i32 %fuzz.bytesel.idiom.b.byte.zext5
  %fuzz.bytesel.idiom.rot.lo8 = shl i32 %fuzz.bytesel.idiom.select7, 2
  %fuzz.bytesel.idiom.rot.hi9 = lshr i32 %fuzz.bytesel.idiom.select7, 6
  %fuzz.bytesel.idiom.rot10 = or i32 %fuzz.bytesel.idiom.rot.lo8, %fuzz.bytesel.idiom.rot.hi9
  %fuzz.bytesel.idiom.lane11 = xor i32 %fuzz.bytesel.idiom.rot10, %fuzz.bytesel.idiom.carry.next
  %fuzz.bytesel.idiom.carry.mask12 = and i32 %fuzz.bytesel.idiom.carry.next, 255
  %fuzz.bytesel.idiom.carry.next13 = add i32 %fuzz.bytesel.idiom.select7, %fuzz.bytesel.idiom.carry.mask12
  %fuzz.bytesel.idiom.a.byte.shr14 = lshr i32 %fuzz.nibbletable.idiom.packed.sub, 16
  %fuzz.bytesel.idiom.a.byte.trunc15 = trunc i32 %fuzz.bytesel.idiom.a.byte.shr14 to i8
  %fuzz.bytesel.idiom.a.byte.zext16 = zext i8 %fuzz.bytesel.idiom.a.byte.trunc15 to i32
  %fuzz.bytesel.idiom.b.byte.shr17 = lshr i32 3, 24
  %fuzz.bytesel.idiom.b.byte.trunc18 = trunc i32 %fuzz.bytesel.idiom.b.byte.shr17 to i8
  %fuzz.bytesel.idiom.b.byte.zext19 = zext i8 %fuzz.bytesel.idiom.b.byte.trunc18 to i32
  %fuzz.bytesel.idiom.xbyte20 = xor i32 %fuzz.bytesel.idiom.a.byte.zext16, %fuzz.bytesel.idiom.b.byte.zext19
  %fuzz.bytesel.idiom.ugt21 = icmp ugt i32 %fuzz.bytesel.idiom.xbyte20, %fuzz.bytesel.idiom.carry.next13
  %fuzz.bytesel.idiom.select22 = select i1 %fuzz.bytesel.idiom.ugt21, i32 %fuzz.bytesel.idiom.a.byte.zext16, i32 %fuzz.bytesel.idiom.b.byte.zext19
  %fuzz.bytesel.idiom.rot.lo23 = shl i32 %fuzz.bytesel.idiom.select22, 3
  %fuzz.bytesel.idiom.rot.hi24 = lshr i32 %fuzz.bytesel.idiom.select22, 5
  %fuzz.bytesel.idiom.rot25 = or i32 %fuzz.bytesel.idiom.rot.lo23, %fuzz.bytesel.idiom.rot.hi24
  %fuzz.bytesel.idiom.lane26 = xor i32 %fuzz.bytesel.idiom.rot25, %fuzz.bytesel.idiom.carry.next13
  %fuzz.bytesel.idiom.carry.mask27 = and i32 %fuzz.bytesel.idiom.carry.next13, 255
  %fuzz.bytesel.idiom.carry.next28 = add i32 %fuzz.bytesel.idiom.select22, %fuzz.bytesel.idiom.carry.mask27
  %fuzz.bytesel.idiom.a.byte.shr29 = lshr i32 %fuzz.nibbletable.idiom.packed.sub, 24
  %fuzz.bytesel.idiom.a.byte.trunc30 = trunc i32 %fuzz.bytesel.idiom.a.byte.shr29 to i8
  %fuzz.bytesel.idiom.a.byte.zext31 = zext i8 %fuzz.bytesel.idiom.a.byte.trunc30 to i32
  %fuzz.bytesel.idiom.b.byte.trunc32 = trunc i32 3 to i8
  %fuzz.bytesel.idiom.b.byte.zext33 = zext i8 %fuzz.bytesel.idiom.b.byte.trunc32 to i32
  %fuzz.bytesel.idiom.xbyte34 = xor i32 %fuzz.bytesel.idiom.a.byte.zext31, %fuzz.bytesel.idiom.b.byte.zext33
  %fuzz.bytesel.idiom.lowbit = and i32 %fuzz.bytesel.idiom.xbyte34, 1
  %fuzz.bytesel.idiom.even = icmp eq i32 %fuzz.bytesel.idiom.lowbit, 0
  %fuzz.bytesel.idiom.select35 = select i1 %fuzz.bytesel.idiom.even, i32 %fuzz.bytesel.idiom.a.byte.zext31, i32 %fuzz.bytesel.idiom.b.byte.zext33
  %fuzz.bytesel.idiom.rot.lo36 = shl i32 %fuzz.bytesel.idiom.select35, 4
  %fuzz.bytesel.idiom.rot.hi37 = lshr i32 %fuzz.bytesel.idiom.select35, 4
  %fuzz.bytesel.idiom.rot38 = or i32 %fuzz.bytesel.idiom.rot.lo36, %fuzz.bytesel.idiom.rot.hi37
  %fuzz.bytesel.idiom.lane39 = xor i32 %fuzz.bytesel.idiom.rot38, %fuzz.bytesel.idiom.carry.next28
  %fuzz.bytesel.idiom.carry.mask40 = and i32 %fuzz.bytesel.idiom.carry.next28, 255
  %fuzz.bytesel.idiom.carry.next41 = add i32 %fuzz.bytesel.idiom.select35, %fuzz.bytesel.idiom.carry.mask40
  %fuzz.bytesel.idiom.pack.mask = and i32 %fuzz.bytesel.idiom.lane, 255
  %fuzz.bytesel.idiom.pack.add = add i32 0, %fuzz.bytesel.idiom.pack.mask
  %fuzz.bytesel.idiom.pack.mask42 = and i32 %fuzz.bytesel.idiom.lane11, 255
  %fuzz.bytesel.idiom.pack.shift = shl i32 %fuzz.bytesel.idiom.pack.mask42, 8
  %fuzz.bytesel.idiom.pack.add43 = add i32 %fuzz.bytesel.idiom.pack.add, %fuzz.bytesel.idiom.pack.shift
  %fuzz.bytesel.idiom.pack.mask44 = and i32 %fuzz.bytesel.idiom.lane26, 255
  %fuzz.bytesel.idiom.pack.shift45 = shl i32 %fuzz.bytesel.idiom.pack.mask44, 16
  %fuzz.bytesel.idiom.pack.add46 = add i32 %fuzz.bytesel.idiom.pack.add43, %fuzz.bytesel.idiom.pack.shift45
  %fuzz.bytesel.idiom.pack.mask47 = and i32 %fuzz.bytesel.idiom.lane39, 255
  %fuzz.bytesel.idiom.pack.shift48 = shl i32 %fuzz.bytesel.idiom.pack.mask47, 24
  %fuzz.bytesel.idiom.pack.add49 = add i32 %fuzz.bytesel.idiom.pack.add46, %fuzz.bytesel.idiom.pack.shift48
  %fuzz.bytesel.idiom.carry.xor = xor i32 %fuzz.bytesel.idiom.pack.add49, %fuzz.bytesel.idiom.carry.next41
  %fuzz.funnel.idiom.shift = and i32 255, 31
  %fuzz.funnel.idiom.inv.raw = sub i32 32, %fuzz.funnel.idiom.shift
  %fuzz.funnel.idiom.inv = and i32 %fuzz.funnel.idiom.inv.raw, 31
  %fuzz.funnel.idiom.zero = icmp eq i32 %fuzz.funnel.idiom.shift, 0
  %fuzz.funnel.idiom.left = shl i32 %fuzz.bytesel.idiom.carry.xor, %fuzz.funnel.idiom.shift
  %fuzz.funnel.idiom.right = lshr i32 255, %fuzz.funnel.idiom.inv
  %fuzz.funnel.idiom.fshl.raw = or i32 %fuzz.funnel.idiom.left, %fuzz.funnel.idiom.right
  %fuzz.funnel.idiom.fshl = select i1 %fuzz.funnel.idiom.zero, i32 %fuzz.bytesel.idiom.carry.xor, i32 %fuzz.funnel.idiom.fshl.raw
  store i32 %fuzz.funnel.idiom.fshl, ptr addrspace(1) %out.ptr, align 4
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef i32 @llvm.amdgcn.workgroup.id.x() #1

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef range(i32 0, 1024) i32 @llvm.amdgcn.workitem.id.x() #1

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.ctpop.i32(i32) #2

attributes #0 = { convergent nounwind "amdgpu-flat-work-group-size"="1,256" "target-cpu"="gfx950" "uniform-work-group-size"="true" }
attributes #1 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #2 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
