; RUN-LLVM-BUILD: build/llvm-fuzzer
; RUN-INPUTS: 0x0 0x1
; ModuleID = '/tmp/fuzzx-m064-original.ll'
source_filename = "/tmp/fuzzx-smoke-20260519-m061-supp/corpus/directed/.seed-155477.ll"
target datalayout = "e-m:e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128:128:48-p9:192:256:256:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9"
target triple = "amdgcn-amd-amdhsa"

; Function Attrs: convergent nounwind
define amdgpu_kernel void @fuzz_kernel(ptr addrspace(1) %in, ptr addrspace(1) %out) #0 {
entry:
  %wg = call i32 @llvm.amdgcn.workgroup.id.x()
  %wi = call i32 @llvm.amdgcn.workitem.id.x()
  %block.base = mul i32 %wg, 256
  %idx = add i32 %block.base, %wi
  %idx64 = zext i32 %idx to i64
  %in.ptr = getelementptr i32, ptr addrspace(1) %in, i64 %idx64
  %v = load i32, ptr addrspace(1) %in.ptr, align 4
  %salt = mul i32 %idx, -1640531527
  %mix = xor i32 %v, %salt
  %out.ptr = getelementptr i32, ptr addrspace(1) %out, i64 %idx64
  %fuzz.i64prefix.idiom.wide.lo64 = zext i32 %mix to i64
  %fuzz.i64prefix.idiom.wide.hi64 = zext i32 %wi to i64
  %fuzz.i64prefix.idiom.wide.hi.shift = shl i64 %fuzz.i64prefix.idiom.wide.hi64, 32
  %fuzz.i64prefix.idiom.wide.pack = or i64 %fuzz.i64prefix.idiom.wide.lo64, %fuzz.i64prefix.idiom.wide.hi.shift
  %fuzz.i64prefix.idiom.part = lshr i64 %fuzz.i64prefix.idiom.wide.pack, 1
  %fuzz.i64prefix.idiom.scan.add = add i64 %fuzz.i64prefix.idiom.wide.pack, %fuzz.i64prefix.idiom.part
  %fuzz.i64prefix.idiom.part1 = lshr i64 %fuzz.i64prefix.idiom.scan.add, 2
  %fuzz.i64prefix.idiom.scan.add2 = add i64 %fuzz.i64prefix.idiom.scan.add, %fuzz.i64prefix.idiom.part1
  %fuzz.i64prefix.idiom.part3 = lshr i64 %fuzz.i64prefix.idiom.scan.add2, 4
  %fuzz.i64prefix.idiom.scan.add4 = add i64 %fuzz.i64prefix.idiom.scan.add2, %fuzz.i64prefix.idiom.part3
  %fuzz.i64prefix.idiom.part5 = lshr i64 %fuzz.i64prefix.idiom.scan.add4, 8
  %fuzz.i64prefix.idiom.scan.or = or i64 %fuzz.i64prefix.idiom.scan.add4, %fuzz.i64prefix.idiom.part5
  %fuzz.i64prefix.idiom.part6 = lshr i64 %fuzz.i64prefix.idiom.scan.or, 16
  %fuzz.i64prefix.idiom.scan.add7 = add i64 %fuzz.i64prefix.idiom.scan.or, %fuzz.i64prefix.idiom.part6
  %fuzz.i64prefix.idiom.part8 = lshr i64 %fuzz.i64prefix.idiom.scan.add7, 32
  %fuzz.i64prefix.idiom.scan.or9 = or i64 %fuzz.i64prefix.idiom.scan.add7, %fuzz.i64prefix.idiom.part8
  %fuzz.i64prefix.idiom.a8 = and i32 %mix, 255
  %fuzz.i64prefix.idiom.a8.64 = zext i32 %fuzz.i64prefix.idiom.a8 to i64
  %fuzz.i64prefix.idiom.a8.shl = shl i64 %fuzz.i64prefix.idiom.a8.64, 24
  %fuzz.i64prefix.idiom.mask = or i64 71777214294589695, %fuzz.i64prefix.idiom.a8.shl
  %fuzz.i64prefix.idiom.and = and i64 %fuzz.i64prefix.idiom.scan.or9, %fuzz.i64prefix.idiom.mask
  %fuzz.i64prefix.idiom.fold.lo = trunc i64 %fuzz.i64prefix.idiom.and to i32
  %fuzz.i64prefix.idiom.fold.hi64 = lshr i64 %fuzz.i64prefix.idiom.and, 32
  %fuzz.i64prefix.idiom.fold.hi = trunc i64 %fuzz.i64prefix.idiom.fold.hi64 to i32
  %fuzz.i64prefix.idiom.fold.xor = xor i32 %fuzz.i64prefix.idiom.fold.lo, %fuzz.i64prefix.idiom.fold.hi
  %fuzz.i64prefix.idiom.b.add = add i32 %fuzz.i64prefix.idiom.fold.xor, %wi
  %fuzz.bitmatrix.idiom.bit.shr = lshr i32 %fuzz.i64prefix.idiom.b.add, 6
  %fuzz.bitmatrix.idiom.bit = and i32 %fuzz.bitmatrix.idiom.bit.shr, 1
  %fuzz.bitmatrix.idiom.bit.shl = shl i32 %fuzz.bitmatrix.idiom.bit, 0
  %fuzz.bitmatrix.idiom.ballot = or i32 0, %fuzz.bitmatrix.idiom.bit.shl
  %fuzz.bitmatrix.idiom.bit.shr1 = lshr i32 %wg, 7
  %fuzz.bitmatrix.idiom.bit2 = and i32 %fuzz.bitmatrix.idiom.bit.shr1, 1
  %fuzz.bitmatrix.idiom.bit.shl3 = shl i32 %fuzz.bitmatrix.idiom.bit2, 1
  %fuzz.bitmatrix.idiom.ballot4 = or i32 %fuzz.bitmatrix.idiom.ballot, %fuzz.bitmatrix.idiom.bit.shl3
  %fuzz.bitmatrix.idiom.bit.shr5 = lshr i32 %fuzz.i64prefix.idiom.b.add, 13
  %fuzz.bitmatrix.idiom.bit6 = and i32 %fuzz.bitmatrix.idiom.bit.shr5, 1
  %fuzz.bitmatrix.idiom.bit.shl7 = shl i32 %fuzz.bitmatrix.idiom.bit6, 2
  %fuzz.bitmatrix.idiom.ballot8 = or i32 %fuzz.bitmatrix.idiom.ballot4, %fuzz.bitmatrix.idiom.bit.shl7
  %fuzz.bitmatrix.idiom.bit.shr9 = lshr i32 %wg, 19
  %fuzz.bitmatrix.idiom.bit10 = and i32 %fuzz.bitmatrix.idiom.bit.shr9, 1
  %fuzz.bitmatrix.idiom.bit.shl11 = shl i32 %fuzz.bitmatrix.idiom.bit10, 3
  %fuzz.bitmatrix.idiom.ballot12 = or i32 %fuzz.bitmatrix.idiom.ballot8, %fuzz.bitmatrix.idiom.bit.shl11
  %fuzz.bitmatrix.idiom.bit.shr13 = lshr i32 %fuzz.i64prefix.idiom.b.add, 27
  %fuzz.bitmatrix.idiom.bit14 = and i32 %fuzz.bitmatrix.idiom.bit.shr13, 1
  %fuzz.bitmatrix.idiom.bit.shl15 = shl i32 %fuzz.bitmatrix.idiom.bit14, 4
  %fuzz.bitmatrix.idiom.ballot16 = or i32 %fuzz.bitmatrix.idiom.ballot12, %fuzz.bitmatrix.idiom.bit.shl15
  %fuzz.bitmatrix.idiom.bit.shr17 = lshr i32 %wg, 29
  %fuzz.bitmatrix.idiom.bit18 = and i32 %fuzz.bitmatrix.idiom.bit.shr17, 1
  %fuzz.bitmatrix.idiom.bit.shl19 = shl i32 %fuzz.bitmatrix.idiom.bit18, 5
  %fuzz.bitmatrix.idiom.ballot20 = or i32 %fuzz.bitmatrix.idiom.ballot16, %fuzz.bitmatrix.idiom.bit.shl19
  %fuzz.bitmatrix.idiom.bit.shr21 = lshr i32 %fuzz.i64prefix.idiom.b.add, 1
  %fuzz.bitmatrix.idiom.bit22 = and i32 %fuzz.bitmatrix.idiom.bit.shr21, 1
  %fuzz.bitmatrix.idiom.bit.shl23 = shl i32 %fuzz.bitmatrix.idiom.bit22, 6
  %fuzz.bitmatrix.idiom.ballot24 = or i32 %fuzz.bitmatrix.idiom.ballot20, %fuzz.bitmatrix.idiom.bit.shl23
  %fuzz.bitmatrix.idiom.bit.shr25 = lshr i32 %wg, 10
  %fuzz.bitmatrix.idiom.bit26 = and i32 %fuzz.bitmatrix.idiom.bit.shr25, 1
  %fuzz.bitmatrix.idiom.bit.shl27 = shl i32 %fuzz.bitmatrix.idiom.bit26, 7
  %fuzz.bitmatrix.idiom.ballot28 = or i32 %fuzz.bitmatrix.idiom.ballot24, %fuzz.bitmatrix.idiom.bit.shl27
  %fuzz.bitmatrix.idiom.spread = mul i32 %fuzz.bitmatrix.idiom.ballot28, 16843009
  %fuzz.bitmatrix.idiom.rows = and i32 %fuzz.bitmatrix.idiom.spread, -2143281136
  %fuzz.bitmatrix.idiom.fold.shr = lshr i32 %fuzz.bitmatrix.idiom.rows, 9
  %fuzz.bitmatrix.idiom.fold = xor i32 %fuzz.bitmatrix.idiom.rows, %fuzz.bitmatrix.idiom.fold.shr
  %fuzz.bitmatrix.idiom.a.low = and i32 %fuzz.i64prefix.idiom.b.add, 255
  %fuzz.bitmatrix.idiom.bias = add i32 %fuzz.bitmatrix.idiom.fold, %fuzz.bitmatrix.idiom.a.low
  %fuzz.veci8shufmul.idiom.x.byte.trunc = trunc i32 %fuzz.bitmatrix.idiom.bias to i8
  %fuzz.veci8shufmul.idiom.x.byte.zext = zext i8 %fuzz.veci8shufmul.idiom.x.byte.trunc to i32
  %fuzz.veci8shufmul.idiom.y.byte.shr = lshr i32 %fuzz.bitmatrix.idiom.bit.shl7, 24
  %fuzz.veci8shufmul.idiom.y.byte.trunc = trunc i32 %fuzz.veci8shufmul.idiom.y.byte.shr to i8
  %fuzz.veci8shufmul.idiom.y.byte.zext = zext i8 %fuzz.veci8shufmul.idiom.y.byte.trunc to i32
  %fuzz.veci8shufmul.idiom.a.bias = xor i32 %fuzz.veci8shufmul.idiom.x.byte.zext, 121
  %fuzz.veci8shufmul.idiom.a.trunc = trunc i32 %fuzz.veci8shufmul.idiom.a.bias to i8
  %fuzz.veci8shufmul.idiom.b.bias = add i32 %fuzz.veci8shufmul.idiom.y.byte.zext, 48
  %fuzz.veci8shufmul.idiom.b.trunc = trunc i32 %fuzz.veci8shufmul.idiom.b.bias to i8
  %fuzz.veci8shufmul.idiom.x.byte.shr = lshr i32 %fuzz.bitmatrix.idiom.bit.shl7, 8
  %fuzz.veci8shufmul.idiom.x.byte.trunc1 = trunc i32 %fuzz.veci8shufmul.idiom.x.byte.shr to i8
  %fuzz.veci8shufmul.idiom.x.byte.zext2 = zext i8 %fuzz.veci8shufmul.idiom.x.byte.trunc1 to i32
  %fuzz.veci8shufmul.idiom.y.byte.trunc3 = trunc i32 %fuzz.bitmatrix.idiom.bias to i8
  %fuzz.veci8shufmul.idiom.y.byte.zext4 = zext i8 %fuzz.veci8shufmul.idiom.y.byte.trunc3 to i32
  %fuzz.veci8shufmul.idiom.a.bias5 = xor i32 %fuzz.veci8shufmul.idiom.x.byte.zext2, 17
  %fuzz.veci8shufmul.idiom.a.trunc6 = trunc i32 %fuzz.veci8shufmul.idiom.a.bias5 to i8
  %fuzz.veci8shufmul.idiom.b.bias7 = add i32 %fuzz.veci8shufmul.idiom.y.byte.zext4, 113
  %fuzz.veci8shufmul.idiom.b.trunc8 = trunc i32 %fuzz.veci8shufmul.idiom.b.bias7 to i8
  %fuzz.veci8shufmul.idiom.x.byte.shr9 = lshr i32 %fuzz.bitmatrix.idiom.bias, 16
  %fuzz.veci8shufmul.idiom.x.byte.trunc10 = trunc i32 %fuzz.veci8shufmul.idiom.x.byte.shr9 to i8
  %fuzz.veci8shufmul.idiom.x.byte.zext11 = zext i8 %fuzz.veci8shufmul.idiom.x.byte.trunc10 to i32
  %fuzz.veci8shufmul.idiom.y.byte.shr12 = lshr i32 %fuzz.bitmatrix.idiom.bit.shl7, 8
  %fuzz.veci8shufmul.idiom.y.byte.trunc13 = trunc i32 %fuzz.veci8shufmul.idiom.y.byte.shr12 to i8
  %fuzz.veci8shufmul.idiom.y.byte.zext14 = zext i8 %fuzz.veci8shufmul.idiom.y.byte.trunc13 to i32
  %fuzz.veci8shufmul.idiom.a.bias15 = xor i32 %fuzz.veci8shufmul.idiom.x.byte.zext11, 28
  %fuzz.veci8shufmul.idiom.a.trunc16 = trunc i32 %fuzz.veci8shufmul.idiom.a.bias15 to i8
  %fuzz.veci8shufmul.idiom.b.bias17 = add i32 %fuzz.veci8shufmul.idiom.y.byte.zext14, 187
  %fuzz.veci8shufmul.idiom.b.trunc18 = trunc i32 %fuzz.veci8shufmul.idiom.b.bias17 to i8
  %fuzz.veci8shufmul.idiom.x.byte.shr19 = lshr i32 %fuzz.bitmatrix.idiom.bit.shl7, 24
  %fuzz.veci8shufmul.idiom.x.byte.trunc20 = trunc i32 %fuzz.veci8shufmul.idiom.x.byte.shr19 to i8
  %fuzz.veci8shufmul.idiom.x.byte.zext21 = zext i8 %fuzz.veci8shufmul.idiom.x.byte.trunc20 to i32
  %fuzz.veci8shufmul.idiom.y.byte.shr22 = lshr i32 %fuzz.bitmatrix.idiom.bias, 16
  %fuzz.veci8shufmul.idiom.y.byte.trunc23 = trunc i32 %fuzz.veci8shufmul.idiom.y.byte.shr22 to i8
  %fuzz.veci8shufmul.idiom.y.byte.zext24 = zext i8 %fuzz.veci8shufmul.idiom.y.byte.trunc23 to i32
  %fuzz.veci8shufmul.idiom.a.bias25 = xor i32 %fuzz.veci8shufmul.idiom.x.byte.zext21, 56
  %fuzz.veci8shufmul.idiom.a.trunc26 = trunc i32 %fuzz.veci8shufmul.idiom.a.bias25 to i8
  %fuzz.veci8shufmul.idiom.b.bias27 = add i32 %fuzz.veci8shufmul.idiom.y.byte.zext24, 127
  %fuzz.veci8shufmul.idiom.b.trunc28 = trunc i32 %fuzz.veci8shufmul.idiom.b.bias27 to i8
  %fuzz.veci8shufmul.idiom.x.byte.trunc29 = trunc i32 %fuzz.bitmatrix.idiom.bias to i8
  %fuzz.veci8shufmul.idiom.x.byte.zext30 = zext i8 %fuzz.veci8shufmul.idiom.x.byte.trunc29 to i32
  %fuzz.veci8shufmul.idiom.y.byte.shr31 = lshr i32 %fuzz.bitmatrix.idiom.bit.shl7, 24
  %fuzz.veci8shufmul.idiom.y.byte.trunc32 = trunc i32 %fuzz.veci8shufmul.idiom.y.byte.shr31 to i8
  %fuzz.veci8shufmul.idiom.y.byte.zext33 = zext i8 %fuzz.veci8shufmul.idiom.y.byte.trunc32 to i32
  %fuzz.veci8shufmul.idiom.a.bias34 = xor i32 %fuzz.veci8shufmul.idiom.x.byte.zext30, 134
  %fuzz.veci8shufmul.idiom.a.trunc35 = trunc i32 %fuzz.veci8shufmul.idiom.a.bias34 to i8
  %fuzz.veci8shufmul.idiom.b.bias36 = add i32 %fuzz.veci8shufmul.idiom.y.byte.zext33, 49
  %fuzz.veci8shufmul.idiom.b.trunc37 = trunc i32 %fuzz.veci8shufmul.idiom.b.bias36 to i8
  %fuzz.veci8shufmul.idiom.x.byte.shr38 = lshr i32 %fuzz.bitmatrix.idiom.bit.shl7, 8
  %fuzz.veci8shufmul.idiom.x.byte.trunc39 = trunc i32 %fuzz.veci8shufmul.idiom.x.byte.shr38 to i8
  %fuzz.veci8shufmul.idiom.x.byte.zext40 = zext i8 %fuzz.veci8shufmul.idiom.x.byte.trunc39 to i32
  %fuzz.veci8shufmul.idiom.y.byte.trunc41 = trunc i32 %fuzz.bitmatrix.idiom.bias to i8
  %fuzz.veci8shufmul.idiom.y.byte.zext42 = zext i8 %fuzz.veci8shufmul.idiom.y.byte.trunc41 to i32
  %fuzz.veci8shufmul.idiom.a.bias43 = xor i32 %fuzz.veci8shufmul.idiom.x.byte.zext40, 128
  %fuzz.veci8shufmul.idiom.a.trunc44 = trunc i32 %fuzz.veci8shufmul.idiom.a.bias43 to i8
  %fuzz.veci8shufmul.idiom.b.bias45 = add i32 %fuzz.veci8shufmul.idiom.y.byte.zext42, 88
  %fuzz.veci8shufmul.idiom.b.trunc46 = trunc i32 %fuzz.veci8shufmul.idiom.b.bias45 to i8
  %fuzz.veci8shufmul.idiom.x.byte.shr47 = lshr i32 %fuzz.bitmatrix.idiom.bias, 16
  %fuzz.veci8shufmul.idiom.x.byte.trunc48 = trunc i32 %fuzz.veci8shufmul.idiom.x.byte.shr47 to i8
  %fuzz.veci8shufmul.idiom.x.byte.zext49 = zext i8 %fuzz.veci8shufmul.idiom.x.byte.trunc48 to i32
  %fuzz.veci8shufmul.idiom.y.byte.shr50 = lshr i32 %fuzz.bitmatrix.idiom.bit.shl7, 8
  %fuzz.veci8shufmul.idiom.y.byte.trunc51 = trunc i32 %fuzz.veci8shufmul.idiom.y.byte.shr50 to i8
  %fuzz.veci8shufmul.idiom.y.byte.zext52 = zext i8 %fuzz.veci8shufmul.idiom.y.byte.trunc51 to i32
  %fuzz.veci8shufmul.idiom.a.bias53 = xor i32 %fuzz.veci8shufmul.idiom.x.byte.zext49, 145
  %fuzz.veci8shufmul.idiom.a.trunc54 = trunc i32 %fuzz.veci8shufmul.idiom.a.bias53 to i8
  %fuzz.veci8shufmul.idiom.b.bias55 = add i32 %fuzz.veci8shufmul.idiom.y.byte.zext52, 71
  %fuzz.veci8shufmul.idiom.b.trunc56 = trunc i32 %fuzz.veci8shufmul.idiom.b.bias55 to i8
  %fuzz.veci8shufmul.idiom.x.byte.shr57 = lshr i32 %fuzz.bitmatrix.idiom.bit.shl7, 24
  %fuzz.veci8shufmul.idiom.x.byte.trunc58 = trunc i32 %fuzz.veci8shufmul.idiom.x.byte.shr57 to i8
  %fuzz.veci8shufmul.idiom.x.byte.zext59 = zext i8 %fuzz.veci8shufmul.idiom.x.byte.trunc58 to i32
  %fuzz.veci8shufmul.idiom.y.byte.shr60 = lshr i32 %fuzz.bitmatrix.idiom.bias, 16
  %fuzz.veci8shufmul.idiom.y.byte.trunc61 = trunc i32 %fuzz.veci8shufmul.idiom.y.byte.shr60 to i8
  %fuzz.veci8shufmul.idiom.y.byte.zext62 = zext i8 %fuzz.veci8shufmul.idiom.y.byte.trunc61 to i32
  %fuzz.veci8shufmul.idiom.a.bias63 = xor i32 %fuzz.veci8shufmul.idiom.x.byte.zext59, 6
  %fuzz.veci8shufmul.idiom.a.trunc64 = trunc i32 %fuzz.veci8shufmul.idiom.a.bias63 to i8
  %fuzz.veci8shufmul.idiom.b.bias65 = add i32 %fuzz.veci8shufmul.idiom.y.byte.zext62, 211
  %fuzz.veci8shufmul.idiom.b.trunc66 = trunc i32 %fuzz.veci8shufmul.idiom.b.bias65 to i8
  %fuzz.vec.ins = insertelement <8 x i8> zeroinitializer, i8 %fuzz.veci8shufmul.idiom.a.trunc, i32 0
  %fuzz.vec.ins67 = insertelement <8 x i8> %fuzz.vec.ins, i8 %fuzz.veci8shufmul.idiom.a.trunc6, i32 1
  %fuzz.vec.ins68 = insertelement <8 x i8> %fuzz.vec.ins67, i8 %fuzz.veci8shufmul.idiom.a.trunc16, i32 2
  %fuzz.vec.ins69 = insertelement <8 x i8> %fuzz.vec.ins68, i8 %fuzz.veci8shufmul.idiom.a.trunc26, i32 3
  %fuzz.vec.ins70 = insertelement <8 x i8> %fuzz.vec.ins69, i8 %fuzz.veci8shufmul.idiom.a.trunc35, i32 4
  %fuzz.vec.ins71 = insertelement <8 x i8> %fuzz.vec.ins70, i8 %fuzz.veci8shufmul.idiom.a.trunc44, i32 5
  %fuzz.vec.ins72 = insertelement <8 x i8> %fuzz.vec.ins71, i8 %fuzz.veci8shufmul.idiom.a.trunc54, i32 6
  %fuzz.vec.ins73 = insertelement <8 x i8> %fuzz.vec.ins72, i8 %fuzz.veci8shufmul.idiom.a.trunc64, i32 7
  %fuzz.vec.ins74 = insertelement <8 x i8> zeroinitializer, i8 %fuzz.veci8shufmul.idiom.b.trunc, i32 0
  %fuzz.vec.ins75 = insertelement <8 x i8> %fuzz.vec.ins74, i8 %fuzz.veci8shufmul.idiom.b.trunc8, i32 1
  %fuzz.vec.ins76 = insertelement <8 x i8> %fuzz.vec.ins75, i8 %fuzz.veci8shufmul.idiom.b.trunc18, i32 2
  %fuzz.vec.ins77 = insertelement <8 x i8> %fuzz.vec.ins76, i8 %fuzz.veci8shufmul.idiom.b.trunc28, i32 3
  %fuzz.vec.ins78 = insertelement <8 x i8> %fuzz.vec.ins77, i8 %fuzz.veci8shufmul.idiom.b.trunc37, i32 4
  %fuzz.vec.ins79 = insertelement <8 x i8> %fuzz.vec.ins78, i8 %fuzz.veci8shufmul.idiom.b.trunc46, i32 5
  %fuzz.vec.ins80 = insertelement <8 x i8> %fuzz.vec.ins79, i8 %fuzz.veci8shufmul.idiom.b.trunc56, i32 6
  %fuzz.vec.ins81 = insertelement <8 x i8> %fuzz.vec.ins80, i8 %fuzz.veci8shufmul.idiom.b.trunc66, i32 7
  %fuzz.veci8shufmul.idiom.rot = shufflevector <8 x i8> %fuzz.vec.ins73, <8 x i8> %fuzz.vec.ins73, <8 x i32> <i32 3, i32 4, i32 5, i32 6, i32 7, i32 0, i32 1, i32 2>
  %fuzz.veci8shufmul.idiom.rev = shufflevector <8 x i8> %fuzz.vec.ins81, <8 x i8> %fuzz.vec.ins81, <8 x i32> <i32 7, i32 6, i32 5, i32 4, i32 3, i32 2, i32 1, i32 0>
  %fuzz.veci8shufmul.idiom.mul = mul <8 x i8> %fuzz.veci8shufmul.idiom.rot, %fuzz.vec.ins81
  %fuzz.veci8shufmul.idiom.cmp = icmp ult <8 x i8> %fuzz.veci8shufmul.idiom.mul, %fuzz.veci8shufmul.idiom.rev
  %fuzz.veci8shufmul.idiom.select = select <8 x i1> %fuzz.veci8shufmul.idiom.cmp, <8 x i8> %fuzz.veci8shufmul.idiom.mul, <8 x i8> %fuzz.veci8shufmul.idiom.rev
  %fuzz.veci8shufmul.idiom.rotrev = add <8 x i8> %fuzz.veci8shufmul.idiom.rot, %fuzz.veci8shufmul.idiom.rev
  %fuzz.veci8shufmul.idiom.xor = xor <8 x i8> %fuzz.veci8shufmul.idiom.mul, %fuzz.veci8shufmul.idiom.rotrev
  %fuzz.veci8shufmul.idiom.lane = extractelement <8 x i8> %fuzz.veci8shufmul.idiom.xor, i32 0
  %fuzz.veci8shufmul.idiom.lane.zext = zext i8 %fuzz.veci8shufmul.idiom.lane to i32
  %fuzz.veci8shufmul.idiom.fold.xor = xor i32 0, %fuzz.veci8shufmul.idiom.lane.zext
  %fuzz.veci8shufmul.idiom.fold.next = add i32 %fuzz.veci8shufmul.idiom.fold.xor, 0
  %fuzz.veci8shufmul.idiom.fold.byte = and i32 %fuzz.veci8shufmul.idiom.fold.next, 255
  %fuzz.veci8shufmul.idiom.lane82 = extractelement <8 x i8> %fuzz.veci8shufmul.idiom.xor, i32 1
  %fuzz.veci8shufmul.idiom.lane.zext83 = zext i8 %fuzz.veci8shufmul.idiom.lane82 to i32
  %fuzz.veci8shufmul.idiom.fold.xor84 = xor i32 %fuzz.veci8shufmul.idiom.fold.next, %fuzz.veci8shufmul.idiom.lane.zext83
  %fuzz.veci8shufmul.idiom.fold.next85 = add i32 %fuzz.veci8shufmul.idiom.fold.xor84, 1
  %fuzz.veci8shufmul.idiom.lane86 = extractelement <8 x i8> %fuzz.veci8shufmul.idiom.xor, i32 2
  %fuzz.veci8shufmul.idiom.lane.zext87 = zext i8 %fuzz.veci8shufmul.idiom.lane86 to i32
  %fuzz.veci8shufmul.idiom.fold.xor88 = xor i32 %fuzz.veci8shufmul.idiom.fold.next85, %fuzz.veci8shufmul.idiom.lane.zext87
  %fuzz.veci8shufmul.idiom.fold.next89 = add i32 %fuzz.veci8shufmul.idiom.fold.xor88, 2
  %fuzz.veci8shufmul.idiom.fold.byte90 = and i32 %fuzz.veci8shufmul.idiom.fold.next89, 255
  %fuzz.veci8shufmul.idiom.lane91 = extractelement <8 x i8> %fuzz.veci8shufmul.idiom.xor, i32 3
  %fuzz.veci8shufmul.idiom.lane.zext92 = zext i8 %fuzz.veci8shufmul.idiom.lane91 to i32
  %fuzz.veci8shufmul.idiom.fold.xor93 = xor i32 %fuzz.veci8shufmul.idiom.fold.next89, %fuzz.veci8shufmul.idiom.lane.zext92
  %fuzz.veci8shufmul.idiom.fold.next94 = add i32 %fuzz.veci8shufmul.idiom.fold.xor93, 3
  %fuzz.veci8shufmul.idiom.lane95 = extractelement <8 x i8> %fuzz.veci8shufmul.idiom.xor, i32 4
  %fuzz.veci8shufmul.idiom.lane.zext96 = zext i8 %fuzz.veci8shufmul.idiom.lane95 to i32
  %fuzz.veci8shufmul.idiom.fold.xor97 = xor i32 %fuzz.veci8shufmul.idiom.fold.next94, %fuzz.veci8shufmul.idiom.lane.zext96
  %fuzz.veci8shufmul.idiom.fold.next98 = add i32 %fuzz.veci8shufmul.idiom.fold.xor97, 4
  %fuzz.veci8shufmul.idiom.fold.byte99 = and i32 %fuzz.veci8shufmul.idiom.fold.next98, 255
  %fuzz.veci8shufmul.idiom.lane100 = extractelement <8 x i8> %fuzz.veci8shufmul.idiom.xor, i32 5
  %fuzz.veci8shufmul.idiom.lane.zext101 = zext i8 %fuzz.veci8shufmul.idiom.lane100 to i32
  %fuzz.veci8shufmul.idiom.fold.xor102 = xor i32 %fuzz.veci8shufmul.idiom.fold.next98, %fuzz.veci8shufmul.idiom.lane.zext101
  %fuzz.veci8shufmul.idiom.fold.next103 = add i32 %fuzz.veci8shufmul.idiom.fold.xor102, 5
  %fuzz.veci8shufmul.idiom.lane104 = extractelement <8 x i8> %fuzz.veci8shufmul.idiom.xor, i32 6
  %fuzz.veci8shufmul.idiom.lane.zext105 = zext i8 %fuzz.veci8shufmul.idiom.lane104 to i32
  %fuzz.veci8shufmul.idiom.fold.xor106 = xor i32 %fuzz.veci8shufmul.idiom.fold.next103, %fuzz.veci8shufmul.idiom.lane.zext105
  %fuzz.veci8shufmul.idiom.fold.next107 = add i32 %fuzz.veci8shufmul.idiom.fold.xor106, 6
  %fuzz.veci8shufmul.idiom.fold.byte108 = and i32 %fuzz.veci8shufmul.idiom.fold.next107, 255
  %fuzz.veci8shufmul.idiom.lane109 = extractelement <8 x i8> %fuzz.veci8shufmul.idiom.xor, i32 7
  %fuzz.veci8shufmul.idiom.lane.zext110 = zext i8 %fuzz.veci8shufmul.idiom.lane109 to i32
  %fuzz.veci8shufmul.idiom.fold.xor111 = xor i32 %fuzz.veci8shufmul.idiom.fold.next107, %fuzz.veci8shufmul.idiom.lane.zext110
  %fuzz.veci8shufmul.idiom.fold.next112 = add i32 %fuzz.veci8shufmul.idiom.fold.xor111, 7
  %fuzz.veci8shufmul.idiom.pack.mask = and i32 %fuzz.veci8shufmul.idiom.fold.byte, 255
  %fuzz.veci8shufmul.idiom.pack.or = or i32 0, %fuzz.veci8shufmul.idiom.pack.mask
  %fuzz.veci8shufmul.idiom.pack.mask113 = and i32 %fuzz.veci8shufmul.idiom.fold.byte90, 255
  %fuzz.veci8shufmul.idiom.pack.shift = shl i32 %fuzz.veci8shufmul.idiom.pack.mask113, 8
  %fuzz.veci8shufmul.idiom.pack.or114 = or i32 %fuzz.veci8shufmul.idiom.pack.or, %fuzz.veci8shufmul.idiom.pack.shift
  %fuzz.veci8shufmul.idiom.pack.mask115 = and i32 %fuzz.veci8shufmul.idiom.fold.byte99, 255
  %fuzz.veci8shufmul.idiom.pack.shift116 = shl i32 %fuzz.veci8shufmul.idiom.pack.mask115, 16
  %fuzz.veci8shufmul.idiom.pack.or117 = or i32 %fuzz.veci8shufmul.idiom.pack.or114, %fuzz.veci8shufmul.idiom.pack.shift116
  %fuzz.veci8shufmul.idiom.pack.mask118 = and i32 %fuzz.veci8shufmul.idiom.fold.byte108, 255
  %fuzz.veci8shufmul.idiom.pack.shift119 = shl i32 %fuzz.veci8shufmul.idiom.pack.mask118, 24
  %fuzz.veci8shufmul.idiom.pack.or120 = or i32 %fuzz.veci8shufmul.idiom.pack.or117, %fuzz.veci8shufmul.idiom.pack.shift119
  %fuzz.nibblecarry.idiom.x.nib.mask = and i32 %fuzz.veci8shufmul.idiom.pack.or120, 15
  %fuzz.nibblecarry.idiom.y.nib.shr = lshr i32 31, 20
  %fuzz.nibblecarry.idiom.y.nib.mask = and i32 %fuzz.nibblecarry.idiom.y.nib.shr, 15
  %fuzz.nibblecarry.idiom.carry.in = and i32 1, 1
  %fuzz.nibblecarry.idiom.sum.xy = add i32 %fuzz.nibblecarry.idiom.x.nib.mask, %fuzz.nibblecarry.idiom.y.nib.mask
  %fuzz.nibblecarry.idiom.sum = add i32 %fuzz.nibblecarry.idiom.sum.xy, %fuzz.nibblecarry.idiom.carry.in
  %fuzz.nibblecarry.idiom.sum.nib = and i32 %fuzz.nibblecarry.idiom.sum, 15
  %fuzz.nibblecarry.idiom.carry.raw = lshr i32 %fuzz.nibblecarry.idiom.sum, 4
  %fuzz.nibblecarry.idiom.carry.out = and i32 %fuzz.nibblecarry.idiom.carry.raw, 1
  %fuzz.nibblecarry.idiom.carry.cmp = icmp ugt i32 %fuzz.nibblecarry.idiom.sum, 15
  %fuzz.nibblecarry.idiom.carry.bit = shl i32 %fuzz.nibblecarry.idiom.carry.out, 3
  %fuzz.nibblecarry.idiom.nib.xor = xor i32 %fuzz.nibblecarry.idiom.sum.nib, %fuzz.nibblecarry.idiom.carry.bit
  %fuzz.nibblecarry.idiom.lane.nib = and i32 %fuzz.nibblecarry.idiom.nib.xor, 15
  %fuzz.nibblecarry.idiom.fold.add = add i32 0, %fuzz.nibblecarry.idiom.lane.nib
  %fuzz.nibblecarry.idiom.fold.next = xor i32 %fuzz.nibblecarry.idiom.fold.add, %fuzz.nibblecarry.idiom.carry.out
  %fuzz.nibblecarry.idiom.x.nib.shr = lshr i32 %fuzz.veci8shufmul.idiom.pack.or120, 4
  %fuzz.nibblecarry.idiom.x.nib.mask1 = and i32 %fuzz.nibblecarry.idiom.x.nib.shr, 15
  %fuzz.nibblecarry.idiom.y.nib.shr2 = lshr i32 31, 24
  %fuzz.nibblecarry.idiom.y.nib.mask3 = and i32 %fuzz.nibblecarry.idiom.y.nib.shr2, 15
  %fuzz.nibblecarry.idiom.carry.in4 = and i32 %fuzz.nibblecarry.idiom.carry.out, 1
  %fuzz.nibblecarry.idiom.sum.xy5 = add i32 %fuzz.nibblecarry.idiom.x.nib.mask1, %fuzz.nibblecarry.idiom.y.nib.mask3
  %fuzz.nibblecarry.idiom.sum6 = add i32 %fuzz.nibblecarry.idiom.sum.xy5, %fuzz.nibblecarry.idiom.carry.in4
  %fuzz.nibblecarry.idiom.sum.nib7 = and i32 %fuzz.nibblecarry.idiom.sum6, 15
  %fuzz.nibblecarry.idiom.carry.raw8 = lshr i32 %fuzz.nibblecarry.idiom.sum6, 4
  %fuzz.nibblecarry.idiom.carry.out9 = and i32 %fuzz.nibblecarry.idiom.carry.raw8, 1
  %fuzz.nibblecarry.idiom.carry.cmp10 = icmp ugt i32 %fuzz.nibblecarry.idiom.sum6, 15
  %fuzz.nibblecarry.idiom.carry.select = select i1 %fuzz.nibblecarry.idiom.carry.cmp10, i32 %fuzz.nibblecarry.idiom.x.nib.mask1, i32 %fuzz.nibblecarry.idiom.sum.nib7
  %fuzz.nibblecarry.idiom.lane.nib11 = and i32 %fuzz.nibblecarry.idiom.carry.select, 15
  %fuzz.nibblecarry.idiom.hi.nib = shl i32 %fuzz.nibblecarry.idiom.lane.nib11, 4
  %fuzz.nibblecarry.idiom.byte.pack = or i32 %fuzz.nibblecarry.idiom.lane.nib, %fuzz.nibblecarry.idiom.hi.nib
  %fuzz.nibblecarry.idiom.fold.add12 = add i32 %fuzz.nibblecarry.idiom.fold.next, %fuzz.nibblecarry.idiom.lane.nib11
  %fuzz.nibblecarry.idiom.fold.next13 = xor i32 %fuzz.nibblecarry.idiom.fold.add12, %fuzz.nibblecarry.idiom.carry.out9
  %fuzz.nibblecarry.idiom.x.nib.shr14 = lshr i32 %fuzz.veci8shufmul.idiom.pack.or120, 8
  %fuzz.nibblecarry.idiom.x.nib.mask15 = and i32 %fuzz.nibblecarry.idiom.x.nib.shr14, 15
  %fuzz.nibblecarry.idiom.y.nib.shr16 = lshr i32 31, 28
  %fuzz.nibblecarry.idiom.y.nib.mask17 = and i32 %fuzz.nibblecarry.idiom.y.nib.shr16, 15
  %fuzz.nibblecarry.idiom.carry.in18 = and i32 %fuzz.nibblecarry.idiom.carry.out9, 1
  %fuzz.nibblecarry.idiom.sum.xy19 = add i32 %fuzz.nibblecarry.idiom.x.nib.mask15, %fuzz.nibblecarry.idiom.y.nib.mask17
  %fuzz.nibblecarry.idiom.sum20 = add i32 %fuzz.nibblecarry.idiom.sum.xy19, %fuzz.nibblecarry.idiom.carry.in18
  %fuzz.nibblecarry.idiom.sum.nib21 = and i32 %fuzz.nibblecarry.idiom.sum20, 15
  %fuzz.nibblecarry.idiom.carry.raw22 = lshr i32 %fuzz.nibblecarry.idiom.sum20, 4
  %fuzz.nibblecarry.idiom.carry.out23 = and i32 %fuzz.nibblecarry.idiom.carry.raw22, 1
  %fuzz.nibblecarry.idiom.carry.cmp24 = icmp ugt i32 %fuzz.nibblecarry.idiom.sum20, 15
  %fuzz.nibblecarry.idiom.lane.nib25 = and i32 %fuzz.nibblecarry.idiom.sum.nib21, 15
  %fuzz.nibblecarry.idiom.fold.add26 = add i32 %fuzz.nibblecarry.idiom.fold.next13, %fuzz.nibblecarry.idiom.lane.nib25
  %fuzz.nibblecarry.idiom.fold.next27 = xor i32 %fuzz.nibblecarry.idiom.fold.add26, %fuzz.nibblecarry.idiom.carry.out23
  %fuzz.nibblecarry.idiom.x.nib.shr28 = lshr i32 %fuzz.veci8shufmul.idiom.pack.or120, 12
  %fuzz.nibblecarry.idiom.x.nib.mask29 = and i32 %fuzz.nibblecarry.idiom.x.nib.shr28, 15
  %fuzz.nibblecarry.idiom.y.nib.mask30 = and i32 31, 15
  %fuzz.nibblecarry.idiom.carry.in31 = and i32 %fuzz.nibblecarry.idiom.carry.out23, 1
  %fuzz.nibblecarry.idiom.sum.xy32 = add i32 %fuzz.nibblecarry.idiom.x.nib.mask29, %fuzz.nibblecarry.idiom.y.nib.mask30
  %fuzz.nibblecarry.idiom.sum33 = add i32 %fuzz.nibblecarry.idiom.sum.xy32, %fuzz.nibblecarry.idiom.carry.in31
  %fuzz.nibblecarry.idiom.sum.nib34 = and i32 %fuzz.nibblecarry.idiom.sum33, 15
  %fuzz.nibblecarry.idiom.carry.raw35 = lshr i32 %fuzz.nibblecarry.idiom.sum33, 4
  %fuzz.nibblecarry.idiom.carry.out36 = and i32 %fuzz.nibblecarry.idiom.carry.raw35, 1
  %fuzz.nibblecarry.idiom.carry.cmp37 = icmp ugt i32 %fuzz.nibblecarry.idiom.sum33, 15
  %fuzz.nibblecarry.idiom.carry.select38 = select i1 %fuzz.nibblecarry.idiom.carry.cmp37, i32 %fuzz.nibblecarry.idiom.x.nib.mask29, i32 %fuzz.nibblecarry.idiom.sum.nib34
  %fuzz.nibblecarry.idiom.lane.nib39 = and i32 %fuzz.nibblecarry.idiom.carry.select38, 15
  %fuzz.nibblecarry.idiom.hi.nib40 = shl i32 %fuzz.nibblecarry.idiom.lane.nib39, 4
  %fuzz.nibblecarry.idiom.byte.pack41 = or i32 %fuzz.nibblecarry.idiom.lane.nib25, %fuzz.nibblecarry.idiom.hi.nib40
  %fuzz.nibblecarry.idiom.fold.add42 = add i32 %fuzz.nibblecarry.idiom.fold.next27, %fuzz.nibblecarry.idiom.lane.nib39
  %fuzz.nibblecarry.idiom.fold.next43 = xor i32 %fuzz.nibblecarry.idiom.fold.add42, %fuzz.nibblecarry.idiom.carry.out36
  %fuzz.nibblecarry.idiom.x.nib.shr44 = lshr i32 %fuzz.veci8shufmul.idiom.pack.or120, 16
  %fuzz.nibblecarry.idiom.x.nib.mask45 = and i32 %fuzz.nibblecarry.idiom.x.nib.shr44, 15
  %fuzz.nibblecarry.idiom.y.nib.shr46 = lshr i32 31, 4
  %fuzz.nibblecarry.idiom.y.nib.mask47 = and i32 %fuzz.nibblecarry.idiom.y.nib.shr46, 15
  %fuzz.nibblecarry.idiom.carry.in48 = and i32 %fuzz.nibblecarry.idiom.carry.out36, 1
  %fuzz.nibblecarry.idiom.sum.xy49 = add i32 %fuzz.nibblecarry.idiom.x.nib.mask45, %fuzz.nibblecarry.idiom.y.nib.mask47
  %fuzz.nibblecarry.idiom.sum50 = add i32 %fuzz.nibblecarry.idiom.sum.xy49, %fuzz.nibblecarry.idiom.carry.in48
  %fuzz.nibblecarry.idiom.sum.nib51 = and i32 %fuzz.nibblecarry.idiom.sum50, 15
  %fuzz.nibblecarry.idiom.carry.raw52 = lshr i32 %fuzz.nibblecarry.idiom.sum50, 4
  %fuzz.nibblecarry.idiom.carry.out53 = and i32 %fuzz.nibblecarry.idiom.carry.raw52, 1
  %fuzz.nibblecarry.idiom.carry.cmp54 = icmp ugt i32 %fuzz.nibblecarry.idiom.sum50, 15
  %fuzz.nibblecarry.idiom.lane.nib55 = and i32 %fuzz.nibblecarry.idiom.sum.nib51, 15
  %fuzz.nibblecarry.idiom.fold.add56 = add i32 %fuzz.nibblecarry.idiom.fold.next43, %fuzz.nibblecarry.idiom.lane.nib55
  %fuzz.nibblecarry.idiom.fold.next57 = xor i32 %fuzz.nibblecarry.idiom.fold.add56, %fuzz.nibblecarry.idiom.carry.out53
  %fuzz.nibblecarry.idiom.x.nib.shr58 = lshr i32 %fuzz.veci8shufmul.idiom.pack.or120, 20
  %fuzz.nibblecarry.idiom.x.nib.mask59 = and i32 %fuzz.nibblecarry.idiom.x.nib.shr58, 15
  %fuzz.nibblecarry.idiom.y.nib.shr60 = lshr i32 31, 8
  %fuzz.nibblecarry.idiom.y.nib.mask61 = and i32 %fuzz.nibblecarry.idiom.y.nib.shr60, 15
  %fuzz.nibblecarry.idiom.carry.in62 = and i32 %fuzz.nibblecarry.idiom.carry.out53, 1
  %fuzz.nibblecarry.idiom.sum.xy63 = add i32 %fuzz.nibblecarry.idiom.x.nib.mask59, %fuzz.nibblecarry.idiom.y.nib.mask61
  %fuzz.nibblecarry.idiom.sum64 = add i32 %fuzz.nibblecarry.idiom.sum.xy63, %fuzz.nibblecarry.idiom.carry.in62
  %fuzz.nibblecarry.idiom.sum.nib65 = and i32 %fuzz.nibblecarry.idiom.sum64, 15
  %fuzz.nibblecarry.idiom.carry.raw66 = lshr i32 %fuzz.nibblecarry.idiom.sum64, 4
  %fuzz.nibblecarry.idiom.carry.out67 = and i32 %fuzz.nibblecarry.idiom.carry.raw66, 1
  %fuzz.nibblecarry.idiom.carry.cmp68 = icmp ugt i32 %fuzz.nibblecarry.idiom.sum64, 15
  %fuzz.nibblecarry.idiom.carry.select69 = select i1 %fuzz.nibblecarry.idiom.carry.cmp68, i32 %fuzz.nibblecarry.idiom.x.nib.mask59, i32 %fuzz.nibblecarry.idiom.sum.nib65
  %fuzz.nibblecarry.idiom.lane.nib70 = and i32 %fuzz.nibblecarry.idiom.carry.select69, 15
  %fuzz.nibblecarry.idiom.hi.nib71 = shl i32 %fuzz.nibblecarry.idiom.lane.nib70, 4
  %fuzz.nibblecarry.idiom.byte.pack72 = or i32 %fuzz.nibblecarry.idiom.lane.nib55, %fuzz.nibblecarry.idiom.hi.nib71
  %fuzz.nibblecarry.idiom.fold.add73 = add i32 %fuzz.nibblecarry.idiom.fold.next57, %fuzz.nibblecarry.idiom.lane.nib70
  %fuzz.nibblecarry.idiom.fold.next74 = xor i32 %fuzz.nibblecarry.idiom.fold.add73, %fuzz.nibblecarry.idiom.carry.out67
  %fuzz.nibblecarry.idiom.x.nib.shr75 = lshr i32 %fuzz.veci8shufmul.idiom.pack.or120, 24
  %fuzz.nibblecarry.idiom.x.nib.mask76 = and i32 %fuzz.nibblecarry.idiom.x.nib.shr75, 15
  %fuzz.nibblecarry.idiom.y.nib.shr77 = lshr i32 31, 12
  %fuzz.nibblecarry.idiom.y.nib.mask78 = and i32 %fuzz.nibblecarry.idiom.y.nib.shr77, 15
  %fuzz.nibblecarry.idiom.carry.in79 = and i32 %fuzz.nibblecarry.idiom.carry.out67, 1
  %fuzz.nibblecarry.idiom.sum.xy80 = add i32 %fuzz.nibblecarry.idiom.x.nib.mask76, %fuzz.nibblecarry.idiom.y.nib.mask78
  %fuzz.nibblecarry.idiom.sum81 = add i32 %fuzz.nibblecarry.idiom.sum.xy80, %fuzz.nibblecarry.idiom.carry.in79
  %fuzz.nibblecarry.idiom.sum.nib82 = and i32 %fuzz.nibblecarry.idiom.sum81, 15
  %fuzz.nibblecarry.idiom.carry.raw83 = lshr i32 %fuzz.nibblecarry.idiom.sum81, 4
  %fuzz.nibblecarry.idiom.carry.out84 = and i32 %fuzz.nibblecarry.idiom.carry.raw83, 1
  %fuzz.nibblecarry.idiom.carry.cmp85 = icmp ugt i32 %fuzz.nibblecarry.idiom.sum81, 15
  %fuzz.nibblecarry.idiom.carry.bit86 = shl i32 %fuzz.nibblecarry.idiom.carry.out84, 3
  %fuzz.nibblecarry.idiom.nib.xor87 = xor i32 %fuzz.nibblecarry.idiom.sum.nib82, %fuzz.nibblecarry.idiom.carry.bit86
  %fuzz.nibblecarry.idiom.lane.nib88 = and i32 %fuzz.nibblecarry.idiom.nib.xor87, 15
  %fuzz.nibblecarry.idiom.fold.add89 = add i32 %fuzz.nibblecarry.idiom.fold.next74, %fuzz.nibblecarry.idiom.lane.nib88
  %fuzz.nibblecarry.idiom.fold.next90 = xor i32 %fuzz.nibblecarry.idiom.fold.add89, %fuzz.nibblecarry.idiom.carry.out84
  %fuzz.nibblecarry.idiom.x.nib.shr91 = lshr i32 %fuzz.veci8shufmul.idiom.pack.or120, 28
  %fuzz.nibblecarry.idiom.x.nib.mask92 = and i32 %fuzz.nibblecarry.idiom.x.nib.shr91, 15
  %fuzz.nibblecarry.idiom.y.nib.shr93 = lshr i32 31, 16
  %fuzz.nibblecarry.idiom.y.nib.mask94 = and i32 %fuzz.nibblecarry.idiom.y.nib.shr93, 15
  %fuzz.nibblecarry.idiom.carry.in95 = and i32 %fuzz.nibblecarry.idiom.carry.out84, 1
  %fuzz.nibblecarry.idiom.sum.xy96 = add i32 %fuzz.nibblecarry.idiom.x.nib.mask92, %fuzz.nibblecarry.idiom.y.nib.mask94
  %fuzz.nibblecarry.idiom.sum97 = add i32 %fuzz.nibblecarry.idiom.sum.xy96, %fuzz.nibblecarry.idiom.carry.in95
  %fuzz.nibblecarry.idiom.sum.nib98 = and i32 %fuzz.nibblecarry.idiom.sum97, 15
  %fuzz.nibblecarry.idiom.carry.raw99 = lshr i32 %fuzz.nibblecarry.idiom.sum97, 4
  %fuzz.nibblecarry.idiom.carry.out100 = and i32 %fuzz.nibblecarry.idiom.carry.raw99, 1
  %fuzz.nibblecarry.idiom.carry.cmp101 = icmp ugt i32 %fuzz.nibblecarry.idiom.sum97, 15
  %fuzz.nibblecarry.idiom.lane.nib102 = and i32 %fuzz.nibblecarry.idiom.sum.nib98, 15
  %fuzz.nibblecarry.idiom.hi.nib103 = shl i32 %fuzz.nibblecarry.idiom.lane.nib102, 4
  %fuzz.nibblecarry.idiom.byte.pack104 = or i32 %fuzz.nibblecarry.idiom.lane.nib88, %fuzz.nibblecarry.idiom.hi.nib103
  %fuzz.nibblecarry.idiom.fold.add105 = add i32 %fuzz.nibblecarry.idiom.fold.next90, %fuzz.nibblecarry.idiom.lane.nib102
  %fuzz.nibblecarry.idiom.fold.next106 = xor i32 %fuzz.nibblecarry.idiom.fold.add105, %fuzz.nibblecarry.idiom.carry.out100
  %fuzz.nibblecarry.idiom.pack.mask = and i32 %fuzz.nibblecarry.idiom.byte.pack, 255
  %fuzz.nibblecarry.idiom.pack.add = add i32 0, %fuzz.nibblecarry.idiom.pack.mask
  %fuzz.nibblecarry.idiom.pack.mask107 = and i32 %fuzz.nibblecarry.idiom.byte.pack41, 255
  %fuzz.nibblecarry.idiom.pack.shift = shl i32 %fuzz.nibblecarry.idiom.pack.mask107, 8
  %fuzz.nibblecarry.idiom.pack.add108 = add i32 %fuzz.nibblecarry.idiom.pack.add, %fuzz.nibblecarry.idiom.pack.shift
  %fuzz.nibblecarry.idiom.pack.mask109 = and i32 %fuzz.nibblecarry.idiom.byte.pack72, 255
  %fuzz.nibblecarry.idiom.pack.shift110 = shl i32 %fuzz.nibblecarry.idiom.pack.mask109, 16
  %fuzz.nibblecarry.idiom.pack.add111 = add i32 %fuzz.nibblecarry.idiom.pack.add108, %fuzz.nibblecarry.idiom.pack.shift110
  %fuzz.nibblecarry.idiom.pack.mask112 = and i32 %fuzz.nibblecarry.idiom.byte.pack104, 255
  %fuzz.nibblecarry.idiom.pack.shift113 = shl i32 %fuzz.nibblecarry.idiom.pack.mask112, 24
  %fuzz.nibblecarry.idiom.pack.add114 = add i32 %fuzz.nibblecarry.idiom.pack.add111, %fuzz.nibblecarry.idiom.pack.shift113
  %fuzz.nibblecarry.idiom.fold.sub = sub i32 %fuzz.nibblecarry.idiom.fold.next106, %fuzz.nibblecarry.idiom.pack.add114
  br label %fuzz.loop.nest.header

fuzz.loop.nest.header:                            ; preds = %fuzz.nested.loop.exit, %entry
  %fuzz.loop.nest.iv = phi i32 [ 0, %entry ], [ %fuzz.loop.nest.next, %fuzz.nested.loop.exit ]
  %fuzz.loop.nest.acc = phi i32 [ %fuzz.nibblecarry.idiom.fold.sub, %entry ], [ %fuzz.loop.acc.inner, %fuzz.nested.loop.exit ]
  %fuzz.loop.nest.cond = icmp ult i32 %fuzz.loop.nest.iv, 1
  br i1 %fuzz.loop.nest.cond, label %fuzz.loop.nest.body, label %fuzz.loop.nest.exit

fuzz.loop.nest.body:                              ; preds = %fuzz.loop.nest.header
  %fuzz.loop.trip.inner.mask = and i32 %fuzz.bitmatrix.idiom.rows, 3
  %fuzz.loop.trip.inner = add i32 %fuzz.loop.trip.inner.mask, 1
  br label %fuzz.nested.loop.header

fuzz.nested.loop.header:                          ; preds = %fuzz.nested.loop.body, %fuzz.loop.nest.body
  %fuzz.loop.iv.inner = phi i32 [ 0, %fuzz.loop.nest.body ], [ %fuzz.loop.next.inner, %fuzz.nested.loop.body ]
  %fuzz.loop.acc.inner = phi i32 [ %fuzz.loop.nest.acc, %fuzz.loop.nest.body ], [ %fuzz.loop.acc.inner.mix, %fuzz.nested.loop.body ]
  %fuzz.loop.cond.inner = icmp ult i32 %fuzz.loop.iv.inner, %fuzz.loop.trip.inner
  br i1 %fuzz.loop.cond.inner, label %fuzz.nested.loop.body, label %fuzz.nested.loop.exit

fuzz.nested.loop.body:                            ; preds = %fuzz.nested.loop.header
  %fuzz.cfg.ternary.idiom.not.a = xor i32 %fuzz.loop.acc.inner, -1
  %fuzz.cfg.ternary.idiom.not.b = xor i32 %fuzz.bitmatrix.idiom.rows, -1
  %fuzz.cfg.ternary.idiom.not.c = xor i32 -1, -1
  %fuzz.cfg.ternary.idiom.blend.mask = xor i32 %fuzz.loop.acc.inner, %fuzz.bitmatrix.idiom.rows
  %fuzz.cfg.ternary.idiom.blend.left = and i32 -1, %fuzz.cfg.ternary.idiom.blend.mask
  %fuzz.cfg.ternary.idiom.blend.not = xor i32 %fuzz.cfg.ternary.idiom.blend.mask, -1
  %fuzz.cfg.ternary.idiom.blend.right = and i32 %fuzz.bitmatrix.idiom.rows, %fuzz.cfg.ternary.idiom.blend.not
  %fuzz.cfg.ternary.idiom.blend = or i32 %fuzz.cfg.ternary.idiom.blend.left, %fuzz.cfg.ternary.idiom.blend.right
  %fuzz.cfg.bytecounthash.idiom.acc.init = xor i32 %fuzz.cfg.ternary.idiom.blend, -2128831035
  %fuzz.cfg.bytecounthash.idiom.x.byte.trunc = trunc i32 %fuzz.cfg.ternary.idiom.blend to i8
  %fuzz.cfg.bytecounthash.idiom.x.byte.zext = zext i8 %fuzz.cfg.bytecounthash.idiom.x.byte.trunc to i32
  %fuzz.cfg.bytecounthash.idiom.y.byte.trunc = trunc i32 %fuzz.bitmatrix.idiom.rows to i8
  %fuzz.cfg.bytecounthash.idiom.y.byte.zext = zext i8 %fuzz.cfg.bytecounthash.idiom.y.byte.trunc to i32
  %fuzz.cfg.bytecounthash.idiom.y.shl = shl i32 %fuzz.cfg.bytecounthash.idiom.y.byte.zext, 8
  %fuzz.cfg.bytecounthash.idiom.pair = or i32 %fuzz.cfg.bytecounthash.idiom.x.byte.zext, %fuzz.cfg.bytecounthash.idiom.y.shl
  %fuzz.cfg.bytecounthash.idiom.ctpop = call i32 @llvm.ctpop.i32(i32 %fuzz.cfg.bytecounthash.idiom.pair)
  %fuzz.cfg.bytecounthash.idiom.ctlz = call i32 @llvm.ctlz.i32(i32 %fuzz.cfg.bytecounthash.idiom.pair, i1 false)
  %fuzz.cfg.bytecounthash.idiom.cttz = call i32 @llvm.cttz.i32(i32 %fuzz.cfg.bytecounthash.idiom.pair, i1 false)
  %fuzz.cfg.bytecounthash.idiom.counts.add = add i32 %fuzz.cfg.bytecounthash.idiom.ctlz, %fuzz.cfg.bytecounthash.idiom.cttz
  %fuzz.cfg.bytecounthash.idiom.counts.mix = xor i32 %fuzz.cfg.bytecounthash.idiom.ctpop, %fuzz.cfg.bytecounthash.idiom.counts.add
  %fuzz.cfg.bytecounthash.idiom.acc.xor = xor i32 %fuzz.cfg.bytecounthash.idiom.acc.init, %fuzz.cfg.bytecounthash.idiom.pair
  %fuzz.cfg.bytecounthash.idiom.acc.mul = mul i32 %fuzz.cfg.bytecounthash.idiom.acc.xor, 16777619
  %fuzz.cfg.bytecounthash.idiom.lane.sub = sub i32 %fuzz.cfg.bytecounthash.idiom.acc.mul, %fuzz.cfg.bytecounthash.idiom.counts.mix
  %fuzz.cfg.bytecounthash.idiom.lane.byte = and i32 %fuzz.cfg.bytecounthash.idiom.lane.sub, 255
  %fuzz.cfg.bytecounthash.idiom.x.byte.shr = lshr i32 %fuzz.bitmatrix.idiom.rows, 8
  %fuzz.cfg.bytecounthash.idiom.x.byte.trunc1 = trunc i32 %fuzz.cfg.bytecounthash.idiom.x.byte.shr to i8
  %fuzz.cfg.bytecounthash.idiom.x.byte.zext2 = zext i8 %fuzz.cfg.bytecounthash.idiom.x.byte.trunc1 to i32
  %fuzz.cfg.bytecounthash.idiom.y.byte.shr = lshr i32 %fuzz.cfg.ternary.idiom.blend, 8
  %fuzz.cfg.bytecounthash.idiom.y.byte.trunc3 = trunc i32 %fuzz.cfg.bytecounthash.idiom.y.byte.shr to i8
  %fuzz.cfg.bytecounthash.idiom.y.byte.zext4 = zext i8 %fuzz.cfg.bytecounthash.idiom.y.byte.trunc3 to i32
  %fuzz.cfg.bytecounthash.idiom.y.shl5 = shl i32 %fuzz.cfg.bytecounthash.idiom.y.byte.zext4, 8
  %fuzz.cfg.bytecounthash.idiom.pair6 = or i32 %fuzz.cfg.bytecounthash.idiom.x.byte.zext2, %fuzz.cfg.bytecounthash.idiom.y.shl5
  %fuzz.cfg.bytecounthash.idiom.ctpop7 = call i32 @llvm.ctpop.i32(i32 %fuzz.cfg.bytecounthash.idiom.pair6)
  %fuzz.cfg.bytecounthash.idiom.ctlz8 = call i32 @llvm.ctlz.i32(i32 %fuzz.cfg.bytecounthash.idiom.pair6, i1 false)
  %fuzz.cfg.bytecounthash.idiom.cttz9 = call i32 @llvm.cttz.i32(i32 %fuzz.cfg.bytecounthash.idiom.pair6, i1 false)
  %fuzz.cfg.bytecounthash.idiom.counts.add10 = add i32 %fuzz.cfg.bytecounthash.idiom.ctlz8, %fuzz.cfg.bytecounthash.idiom.cttz9
  %fuzz.cfg.bytecounthash.idiom.counts.mix11 = xor i32 %fuzz.cfg.bytecounthash.idiom.ctpop7, %fuzz.cfg.bytecounthash.idiom.counts.add10
  %fuzz.cfg.bytecounthash.idiom.acc.xor12 = xor i32 %fuzz.cfg.bytecounthash.idiom.acc.mul, %fuzz.cfg.bytecounthash.idiom.pair6
  %fuzz.cfg.bytecounthash.idiom.acc.mul13 = mul i32 %fuzz.cfg.bytecounthash.idiom.acc.xor12, 16777876
  %fuzz.cfg.bytecounthash.idiom.lane.add = add i32 %fuzz.cfg.bytecounthash.idiom.acc.mul13, %fuzz.cfg.bytecounthash.idiom.counts.mix11
  %fuzz.cfg.bytecounthash.idiom.lane.byte14 = and i32 %fuzz.cfg.bytecounthash.idiom.lane.add, 255
  %fuzz.cfg.bytecounthash.idiom.x.byte.shr15 = lshr i32 %fuzz.cfg.ternary.idiom.blend, 16
  %fuzz.cfg.bytecounthash.idiom.x.byte.trunc16 = trunc i32 %fuzz.cfg.bytecounthash.idiom.x.byte.shr15 to i8
  %fuzz.cfg.bytecounthash.idiom.x.byte.zext17 = zext i8 %fuzz.cfg.bytecounthash.idiom.x.byte.trunc16 to i32
  %fuzz.cfg.bytecounthash.idiom.y.byte.shr18 = lshr i32 %fuzz.bitmatrix.idiom.rows, 16
  %fuzz.cfg.bytecounthash.idiom.y.byte.trunc19 = trunc i32 %fuzz.cfg.bytecounthash.idiom.y.byte.shr18 to i8
  %fuzz.cfg.bytecounthash.idiom.y.byte.zext20 = zext i8 %fuzz.cfg.bytecounthash.idiom.y.byte.trunc19 to i32
  %fuzz.cfg.bytecounthash.idiom.y.shl21 = shl i32 %fuzz.cfg.bytecounthash.idiom.y.byte.zext20, 8
  %fuzz.cfg.bytecounthash.idiom.pair22 = or i32 %fuzz.cfg.bytecounthash.idiom.x.byte.zext17, %fuzz.cfg.bytecounthash.idiom.y.shl21
  %fuzz.cfg.bytecounthash.idiom.ctpop23 = call i32 @llvm.ctpop.i32(i32 %fuzz.cfg.bytecounthash.idiom.pair22)
  %fuzz.cfg.bytecounthash.idiom.ctlz24 = call i32 @llvm.ctlz.i32(i32 %fuzz.cfg.bytecounthash.idiom.pair22, i1 false)
  %fuzz.cfg.bytecounthash.idiom.cttz25 = call i32 @llvm.cttz.i32(i32 %fuzz.cfg.bytecounthash.idiom.pair22, i1 false)
  %fuzz.cfg.bytecounthash.idiom.counts.add26 = add i32 %fuzz.cfg.bytecounthash.idiom.ctlz24, %fuzz.cfg.bytecounthash.idiom.cttz25
  %fuzz.cfg.bytecounthash.idiom.counts.mix27 = xor i32 %fuzz.cfg.bytecounthash.idiom.ctpop23, %fuzz.cfg.bytecounthash.idiom.counts.add26
  %fuzz.cfg.bytecounthash.idiom.acc.xor28 = xor i32 %fuzz.cfg.bytecounthash.idiom.acc.mul13, %fuzz.cfg.bytecounthash.idiom.pair22
  %fuzz.cfg.bytecounthash.idiom.acc.mul29 = mul i32 %fuzz.cfg.bytecounthash.idiom.acc.xor28, 16778133
  %fuzz.cfg.bytecounthash.idiom.lane.sub30 = sub i32 %fuzz.cfg.bytecounthash.idiom.acc.mul29, %fuzz.cfg.bytecounthash.idiom.counts.mix27
  %fuzz.cfg.bytecounthash.idiom.lane.byte31 = and i32 %fuzz.cfg.bytecounthash.idiom.lane.sub30, 255
  %fuzz.cfg.bytecounthash.idiom.x.byte.shr32 = lshr i32 %fuzz.bitmatrix.idiom.rows, 24
  %fuzz.cfg.bytecounthash.idiom.x.byte.trunc33 = trunc i32 %fuzz.cfg.bytecounthash.idiom.x.byte.shr32 to i8
  %fuzz.cfg.bytecounthash.idiom.x.byte.zext34 = zext i8 %fuzz.cfg.bytecounthash.idiom.x.byte.trunc33 to i32
  %fuzz.cfg.bytecounthash.idiom.y.byte.shr35 = lshr i32 %fuzz.cfg.ternary.idiom.blend, 24
  %fuzz.cfg.bytecounthash.idiom.y.byte.trunc36 = trunc i32 %fuzz.cfg.bytecounthash.idiom.y.byte.shr35 to i8
  %fuzz.cfg.bytecounthash.idiom.y.byte.zext37 = zext i8 %fuzz.cfg.bytecounthash.idiom.y.byte.trunc36 to i32
  %fuzz.cfg.bytecounthash.idiom.y.shl38 = shl i32 %fuzz.cfg.bytecounthash.idiom.y.byte.zext37, 8
  %fuzz.cfg.bytecounthash.idiom.pair39 = or i32 %fuzz.cfg.bytecounthash.idiom.x.byte.zext34, %fuzz.cfg.bytecounthash.idiom.y.shl38
  %fuzz.cfg.bytecounthash.idiom.ctpop40 = call i32 @llvm.ctpop.i32(i32 %fuzz.cfg.bytecounthash.idiom.pair39)
  %fuzz.cfg.bytecounthash.idiom.ctlz41 = call i32 @llvm.ctlz.i32(i32 %fuzz.cfg.bytecounthash.idiom.pair39, i1 false)
  %fuzz.cfg.bytecounthash.idiom.cttz42 = call i32 @llvm.cttz.i32(i32 %fuzz.cfg.bytecounthash.idiom.pair39, i1 false)
  %fuzz.cfg.bytecounthash.idiom.counts.add43 = add i32 %fuzz.cfg.bytecounthash.idiom.ctlz41, %fuzz.cfg.bytecounthash.idiom.cttz42
  %fuzz.cfg.bytecounthash.idiom.counts.mix44 = xor i32 %fuzz.cfg.bytecounthash.idiom.ctpop40, %fuzz.cfg.bytecounthash.idiom.counts.add43
  %fuzz.cfg.bytecounthash.idiom.acc.xor45 = xor i32 %fuzz.cfg.bytecounthash.idiom.acc.mul29, %fuzz.cfg.bytecounthash.idiom.pair39
  %fuzz.cfg.bytecounthash.idiom.acc.mul46 = mul i32 %fuzz.cfg.bytecounthash.idiom.acc.xor45, 16778390
  %fuzz.cfg.bytecounthash.idiom.lane.sub47 = sub i32 %fuzz.cfg.bytecounthash.idiom.acc.mul46, %fuzz.cfg.bytecounthash.idiom.counts.mix44
  %fuzz.cfg.bytecounthash.idiom.lane.byte48 = and i32 %fuzz.cfg.bytecounthash.idiom.lane.sub47, 255
  %fuzz.cfg.bytecounthash.idiom.pack.mask = and i32 %fuzz.cfg.bytecounthash.idiom.lane.byte, 255
  %fuzz.cfg.bytecounthash.idiom.pack.add = add i32 0, %fuzz.cfg.bytecounthash.idiom.pack.mask
  %fuzz.cfg.bytecounthash.idiom.pack.mask49 = and i32 %fuzz.cfg.bytecounthash.idiom.lane.byte14, 255
  %fuzz.cfg.bytecounthash.idiom.pack.shift = shl i32 %fuzz.cfg.bytecounthash.idiom.pack.mask49, 8
  %fuzz.cfg.bytecounthash.idiom.pack.add50 = add i32 %fuzz.cfg.bytecounthash.idiom.pack.add, %fuzz.cfg.bytecounthash.idiom.pack.shift
  %fuzz.cfg.bytecounthash.idiom.pack.mask51 = and i32 %fuzz.cfg.bytecounthash.idiom.lane.byte31, 255
  %fuzz.cfg.bytecounthash.idiom.pack.shift52 = shl i32 %fuzz.cfg.bytecounthash.idiom.pack.mask51, 16
  %fuzz.cfg.bytecounthash.idiom.pack.add53 = add i32 %fuzz.cfg.bytecounthash.idiom.pack.add50, %fuzz.cfg.bytecounthash.idiom.pack.shift52
  %fuzz.cfg.bytecounthash.idiom.pack.mask54 = and i32 %fuzz.cfg.bytecounthash.idiom.lane.byte48, 255
  %fuzz.cfg.bytecounthash.idiom.pack.shift55 = shl i32 %fuzz.cfg.bytecounthash.idiom.pack.mask54, 24
  %fuzz.cfg.bytecounthash.idiom.pack.add56 = add i32 %fuzz.cfg.bytecounthash.idiom.pack.add53, %fuzz.cfg.bytecounthash.idiom.pack.shift55
  %fuzz.cfg.bytecounthash.idiom.acc.xor57 = xor i32 %fuzz.cfg.bytecounthash.idiom.pack.add56, %fuzz.cfg.bytecounthash.idiom.acc.mul46
  %fuzz.nested.branch = icmp ne i32 %fuzz.cfg.bytecounthash.idiom.acc.xor57, %fuzz.bitmatrix.idiom.rows
  %fuzz.cfg.halfblend.idiom.a.lo.trunc = trunc i32 %fuzz.cfg.bytecounthash.idiom.acc.xor57 to i16
  %fuzz.cfg.halfblend.idiom.a.lo.zext = zext i16 %fuzz.cfg.halfblend.idiom.a.lo.trunc to i32
  %fuzz.cfg.halfblend.idiom.a.hi.shr = lshr i32 %fuzz.cfg.bytecounthash.idiom.acc.xor57, 16
  %fuzz.cfg.halfblend.idiom.a.hi.trunc = trunc i32 %fuzz.cfg.halfblend.idiom.a.hi.shr to i16
  %fuzz.cfg.halfblend.idiom.a.hi.zext = zext i16 %fuzz.cfg.halfblend.idiom.a.hi.trunc to i32
  %fuzz.cfg.halfblend.idiom.b.lo.trunc = trunc i32 %fuzz.bitmatrix.idiom.rows to i16
  %fuzz.cfg.halfblend.idiom.b.lo.zext = zext i16 %fuzz.cfg.halfblend.idiom.b.lo.trunc to i32
  %fuzz.cfg.halfblend.idiom.b.hi.shr = lshr i32 %fuzz.bitmatrix.idiom.rows, 16
  %fuzz.cfg.halfblend.idiom.b.hi.trunc = trunc i32 %fuzz.cfg.halfblend.idiom.b.hi.shr to i16
  %fuzz.cfg.halfblend.idiom.b.hi.zext = zext i16 %fuzz.cfg.halfblend.idiom.b.hi.trunc to i32
  %fuzz.cfg.halfblend.idiom.ult = icmp ult i32 %fuzz.cfg.halfblend.idiom.a.hi.zext, %fuzz.cfg.halfblend.idiom.b.lo.zext
  %fuzz.cfg.halfblend.idiom.lo = select i1 %fuzz.cfg.halfblend.idiom.ult, i32 %fuzz.cfg.halfblend.idiom.a.hi.zext, i32 %fuzz.cfg.halfblend.idiom.b.lo.zext
  %fuzz.cfg.halfblend.idiom.hi = select i1 %fuzz.cfg.halfblend.idiom.ult, i32 %fuzz.cfg.halfblend.idiom.b.lo.zext, i32 %fuzz.cfg.halfblend.idiom.a.hi.zext
  %fuzz.cfg.halfblend.idiom.hi.shl = shl i32 %fuzz.cfg.halfblend.idiom.hi, 3
  %fuzz.cfg.halfblend.idiom.mix.xor = xor i32 %fuzz.cfg.halfblend.idiom.lo, %fuzz.cfg.halfblend.idiom.hi.shl
  %fuzz.cfg.halfblend.idiom.half.update = and i32 %fuzz.cfg.halfblend.idiom.mix.xor, 65535
  %fuzz.cfg.halfblend.idiom.fold.add = add i32 31346, %fuzz.cfg.halfblend.idiom.mix.xor
  %fuzz.cfg.halfblend.idiom.cmp.i32 = zext i1 %fuzz.cfg.halfblend.idiom.ult to i32
  %fuzz.cfg.halfblend.idiom.fold.next = xor i32 %fuzz.cfg.halfblend.idiom.fold.add, %fuzz.cfg.halfblend.idiom.cmp.i32
  %fuzz.cfg.halfblend.idiom.ult58 = icmp ult i32 %fuzz.cfg.halfblend.idiom.b.hi.zext, %fuzz.cfg.halfblend.idiom.half.update
  %fuzz.cfg.halfblend.idiom.lo59 = select i1 %fuzz.cfg.halfblend.idiom.ult58, i32 %fuzz.cfg.halfblend.idiom.b.hi.zext, i32 %fuzz.cfg.halfblend.idiom.half.update
  %fuzz.cfg.halfblend.idiom.hi60 = select i1 %fuzz.cfg.halfblend.idiom.ult58, i32 %fuzz.cfg.halfblend.idiom.half.update, i32 %fuzz.cfg.halfblend.idiom.b.hi.zext
  %fuzz.cfg.halfblend.idiom.hi.shl61 = shl i32 %fuzz.cfg.halfblend.idiom.hi60, 3
  %fuzz.cfg.halfblend.idiom.mix.xor62 = xor i32 %fuzz.cfg.halfblend.idiom.lo59, %fuzz.cfg.halfblend.idiom.hi.shl61
  %fuzz.cfg.halfblend.idiom.half.update63 = and i32 %fuzz.cfg.halfblend.idiom.mix.xor62, 65535
  %fuzz.cfg.halfblend.idiom.fold.add64 = add i32 %fuzz.cfg.halfblend.idiom.fold.next, %fuzz.cfg.halfblend.idiom.mix.xor62
  %fuzz.cfg.halfblend.idiom.cmp.i3265 = zext i1 %fuzz.cfg.halfblend.idiom.ult58 to i32
  %fuzz.cfg.halfblend.idiom.fold.next66 = xor i32 %fuzz.cfg.halfblend.idiom.fold.add64, %fuzz.cfg.halfblend.idiom.cmp.i3265
  %fuzz.cfg.halfblend.idiom.x.i16 = trunc i32 %fuzz.cfg.halfblend.idiom.half.update to i16
  %fuzz.cfg.halfblend.idiom.x.sext = sext i16 %fuzz.cfg.halfblend.idiom.x.i16 to i32
  %fuzz.cfg.halfblend.idiom.y.i16 = trunc i32 %fuzz.cfg.halfblend.idiom.half.update63 to i16
  %fuzz.cfg.halfblend.idiom.y.sext = sext i16 %fuzz.cfg.halfblend.idiom.y.i16 to i32
  %fuzz.cfg.halfblend.idiom.sgt = icmp sgt i32 %fuzz.cfg.halfblend.idiom.x.sext, %fuzz.cfg.halfblend.idiom.y.sext
  %fuzz.cfg.halfblend.idiom.lo67 = select i1 %fuzz.cfg.halfblend.idiom.sgt, i32 %fuzz.cfg.halfblend.idiom.half.update, i32 %fuzz.cfg.halfblend.idiom.half.update63
  %fuzz.cfg.halfblend.idiom.hi68 = select i1 %fuzz.cfg.halfblend.idiom.sgt, i32 %fuzz.cfg.halfblend.idiom.half.update63, i32 %fuzz.cfg.halfblend.idiom.half.update
  %fuzz.cfg.halfblend.idiom.hi.shl69 = shl i32 %fuzz.cfg.halfblend.idiom.hi68, 3
  %fuzz.cfg.halfblend.idiom.mix.xor70 = xor i32 %fuzz.cfg.halfblend.idiom.lo67, %fuzz.cfg.halfblend.idiom.hi.shl69
  %fuzz.cfg.halfblend.idiom.half.update71 = and i32 %fuzz.cfg.halfblend.idiom.mix.xor70, 65535
  %fuzz.cfg.halfblend.idiom.fold.add72 = add i32 %fuzz.cfg.halfblend.idiom.fold.next66, %fuzz.cfg.halfblend.idiom.mix.xor70
  %fuzz.cfg.halfblend.idiom.cmp.i3273 = zext i1 %fuzz.cfg.halfblend.idiom.sgt to i32
  %fuzz.cfg.halfblend.idiom.fold.next74 = xor i32 %fuzz.cfg.halfblend.idiom.fold.add72, %fuzz.cfg.halfblend.idiom.cmp.i3273
  %fuzz.cfg.halfblend.idiom.x.i1675 = trunc i32 %fuzz.cfg.halfblend.idiom.b.lo.zext to i16
  %fuzz.cfg.halfblend.idiom.x.sext76 = sext i16 %fuzz.cfg.halfblend.idiom.x.i1675 to i32
  %fuzz.cfg.halfblend.idiom.y.i1677 = trunc i32 %fuzz.cfg.halfblend.idiom.half.update63 to i16
  %fuzz.cfg.halfblend.idiom.y.sext78 = sext i16 %fuzz.cfg.halfblend.idiom.y.i1677 to i32
  %fuzz.cfg.halfblend.idiom.sgt79 = icmp sgt i32 %fuzz.cfg.halfblend.idiom.x.sext76, %fuzz.cfg.halfblend.idiom.y.sext78
  %fuzz.cfg.halfblend.idiom.lo80 = select i1 %fuzz.cfg.halfblend.idiom.sgt79, i32 %fuzz.cfg.halfblend.idiom.b.lo.zext, i32 %fuzz.cfg.halfblend.idiom.half.update63
  %fuzz.cfg.halfblend.idiom.hi81 = select i1 %fuzz.cfg.halfblend.idiom.sgt79, i32 %fuzz.cfg.halfblend.idiom.half.update63, i32 %fuzz.cfg.halfblend.idiom.b.lo.zext
  %fuzz.cfg.halfblend.idiom.lo.byte = and i32 %fuzz.cfg.halfblend.idiom.lo80, 255
  %fuzz.cfg.halfblend.idiom.hi.byte = and i32 %fuzz.cfg.halfblend.idiom.hi81, 255
  %fuzz.cfg.halfblend.idiom.hi.pack = shl i32 %fuzz.cfg.halfblend.idiom.hi.byte, 8
  %fuzz.cfg.halfblend.idiom.mix.pack = or i32 %fuzz.cfg.halfblend.idiom.lo.byte, %fuzz.cfg.halfblend.idiom.hi.pack
  %fuzz.cfg.halfblend.idiom.half.update82 = and i32 %fuzz.cfg.halfblend.idiom.mix.pack, 65535
  %fuzz.cfg.halfblend.idiom.fold.add83 = add i32 %fuzz.cfg.halfblend.idiom.fold.next74, %fuzz.cfg.halfblend.idiom.mix.pack
  %fuzz.cfg.halfblend.idiom.cmp.i3284 = zext i1 %fuzz.cfg.halfblend.idiom.sgt79 to i32
  %fuzz.cfg.halfblend.idiom.fold.next85 = xor i32 %fuzz.cfg.halfblend.idiom.fold.add83, %fuzz.cfg.halfblend.idiom.cmp.i3284
  %fuzz.cfg.halfblend.idiom.x.i1686 = trunc i32 %fuzz.cfg.halfblend.idiom.half.update82 to i16
  %fuzz.cfg.halfblend.idiom.x.sext87 = sext i16 %fuzz.cfg.halfblend.idiom.x.i1686 to i32
  %fuzz.cfg.halfblend.idiom.y.i1688 = trunc i32 %fuzz.cfg.halfblend.idiom.half.update63 to i16
  %fuzz.cfg.halfblend.idiom.y.sext89 = sext i16 %fuzz.cfg.halfblend.idiom.y.i1688 to i32
  %fuzz.cfg.halfblend.idiom.sgt90 = icmp sgt i32 %fuzz.cfg.halfblend.idiom.x.sext87, %fuzz.cfg.halfblend.idiom.y.sext89
  %fuzz.cfg.halfblend.idiom.lo91 = select i1 %fuzz.cfg.halfblend.idiom.sgt90, i32 %fuzz.cfg.halfblend.idiom.half.update82, i32 %fuzz.cfg.halfblend.idiom.half.update63
  %fuzz.cfg.halfblend.idiom.hi92 = select i1 %fuzz.cfg.halfblend.idiom.sgt90, i32 %fuzz.cfg.halfblend.idiom.half.update63, i32 %fuzz.cfg.halfblend.idiom.half.update82
  %fuzz.cfg.halfblend.idiom.mix.add = add i32 %fuzz.cfg.halfblend.idiom.lo91, %fuzz.cfg.halfblend.idiom.hi92
  %fuzz.cfg.halfblend.idiom.half.update93 = and i32 %fuzz.cfg.halfblend.idiom.mix.add, 65535
  %fuzz.cfg.halfblend.idiom.fold.add94 = add i32 %fuzz.cfg.halfblend.idiom.fold.next85, %fuzz.cfg.halfblend.idiom.mix.add
  %fuzz.cfg.halfblend.idiom.cmp.i3295 = zext i1 %fuzz.cfg.halfblend.idiom.sgt90 to i32
  %fuzz.cfg.halfblend.idiom.fold.next96 = xor i32 %fuzz.cfg.halfblend.idiom.fold.add94, %fuzz.cfg.halfblend.idiom.cmp.i3295
  %fuzz.cfg.halfblend.idiom.pack.lo.lo.mask = and i32 %fuzz.cfg.halfblend.idiom.a.lo.zext, 65535
  %fuzz.cfg.halfblend.idiom.pack.lo.hi.mask = and i32 %fuzz.cfg.halfblend.idiom.half.update71, 65535
  %fuzz.cfg.halfblend.idiom.pack.lo.hi.shift = shl i32 %fuzz.cfg.halfblend.idiom.pack.lo.hi.mask, 16
  %fuzz.cfg.halfblend.idiom.pack.lo.add = add i32 %fuzz.cfg.halfblend.idiom.pack.lo.lo.mask, %fuzz.cfg.halfblend.idiom.pack.lo.hi.shift
  %fuzz.cfg.halfblend.idiom.pack.hi.lo.mask = and i32 %fuzz.cfg.halfblend.idiom.half.update93, 65535
  %fuzz.cfg.halfblend.idiom.pack.hi.hi.mask = and i32 %fuzz.cfg.halfblend.idiom.half.update63, 65535
  %fuzz.cfg.halfblend.idiom.pack.hi.hi.shift = shl i32 %fuzz.cfg.halfblend.idiom.pack.hi.hi.mask, 16
  %fuzz.cfg.halfblend.idiom.pack.hi.or = or i32 %fuzz.cfg.halfblend.idiom.pack.hi.lo.mask, %fuzz.cfg.halfblend.idiom.pack.hi.hi.shift
  %fuzz.cfg.halfblend.idiom.fold.add97 = add i32 %fuzz.cfg.halfblend.idiom.pack.lo.add, %fuzz.cfg.halfblend.idiom.fold.next96
  %fuzz.loop.acc.inner.mix = xor i32 %fuzz.cfg.halfblend.idiom.fold.add97, %fuzz.loop.iv.inner
  %fuzz.loop.next.inner = add i32 %fuzz.loop.iv.inner, 1
  br label %fuzz.nested.loop.header

fuzz.nested.loop.exit:                            ; preds = %fuzz.nested.loop.header
  %fuzz.loop.nest.next = add i32 %fuzz.loop.nest.iv, 1
  br label %fuzz.loop.nest.header

fuzz.loop.nest.exit:                              ; preds = %fuzz.loop.nest.header
  store i32 %fuzz.loop.nest.acc, ptr addrspace(1) %out.ptr, align 4
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef i32 @llvm.amdgcn.workgroup.id.x() #1

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef range(i32 0, 1024) i32 @llvm.amdgcn.workitem.id.x() #1

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.ctpop.i32(i32) #2

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.ctlz.i32(i32, i1 immarg) #1

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.cttz.i32(i32, i1 immarg) #1

; uselistorder directives
uselistorder ptr @llvm.ctpop.i32, { 3, 2, 1, 0 }
uselistorder ptr @llvm.ctlz.i32, { 3, 2, 1, 0 }
uselistorder ptr @llvm.cttz.i32, { 3, 2, 1, 0 }

attributes #0 = { convergent nounwind "amdgpu-flat-work-group-size"="1,256" "target-cpu"="gfx950" "uniform-work-group-size"="true" }
attributes #1 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #2 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
