; RUN-INPUTS: 0x0
; RUN-LLVM-BUILD: build/llvm-fuzzer
; ModuleID = '<bc file>'
source_filename = "known-miscompiles/m061-ovmaskpack-o0-overflow-lowering/reduced.ll"
target datalayout = "e-m:e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128:128:48-p9:192:256:256:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9"
target triple = "amdgcn-amd-amdhsa"

; Function Attrs: convergent nounwind
define amdgpu_kernel void @fuzz_kernel(ptr addrspace(1) %in, ptr addrspace(1) %out) #0 {
entry:
  %wg = call i32 @llvm.amdgcn.workgroup.id.x()
  %wi = call i32 @llvm.amdgcn.workitem.id.x()
  %block.base = mul i32 %wg, 256
  %idx = add i32 %block.base, %wi
  %idx64 = zext i32 %idx to i64
  %in.ptr = getelementptr i32, ptr addrspace(1) %in, i64 %idx64
  %v = load i32, ptr addrspace(1) %in.ptr, align 4
  %salt = mul i32 %idx, -1640531527
  %mix = xor i32 %v, %salt
  %out.ptr = getelementptr i32, ptr addrspace(1) %out, i64 %idx64
  %fuzz.sdiv.num.mask = and i32 %mix, 8388607
  %fuzz.sdiv.den.mask = and i32 %wg, 255
  %fuzz.sdiv.den = or i32 %fuzz.sdiv.den.mask, 1
  %fuzz.sdiv.op = sdiv i32 %fuzz.sdiv.num.mask, %fuzz.sdiv.den
  %fuzz.loop.trip.mask = and i32 %block.base, 15
  %fuzz.loop.trip = add i32 %fuzz.loop.trip.mask, 1
  %fuzz.loop.cond = icmp ult i32 0, %fuzz.loop.trip
  %fuzz.ternary.idiom.not.a = xor i32 %fuzz.sdiv.op, -1
  %fuzz.ternary.idiom.not.b = xor i32 2, -1
  %fuzz.ternary.idiom.not.c = xor i32 1, -1
  %fuzz.ternary.idiom.cnf0 = or i32 %fuzz.sdiv.op, 2
  %fuzz.ternary.idiom.cnf1 = or i32 %fuzz.ternary.idiom.not.a, 1
  %fuzz.ternary.idiom.cnf2 = or i32 %fuzz.ternary.idiom.not.b, %fuzz.ternary.idiom.not.c
  %fuzz.ternary.idiom.cnf.and0 = and i32 %fuzz.ternary.idiom.cnf0, %fuzz.ternary.idiom.cnf1
  %fuzz.ternary.idiom.cnf = and i32 %fuzz.ternary.idiom.cnf.and0, %fuzz.ternary.idiom.cnf2
  br label %fuzz.loop.nest.header

fuzz.loop.nest.header:                            ; preds = %fuzz.nested.loop.exit, %entry
  %fuzz.loop.nest.iv = phi i32 [ 0, %entry ], [ %fuzz.loop.nest.next, %fuzz.nested.loop.exit ]
  %fuzz.loop.nest.acc = phi i32 [ %fuzz.ternary.idiom.cnf, %entry ], [ %fuzz.loop.nest.acc.xor, %fuzz.nested.loop.exit ]
  %fuzz.loop.nest.cond = icmp ult i32 %fuzz.loop.nest.iv, 3
  br i1 %fuzz.loop.nest.cond, label %fuzz.loop.nest.body, label %fuzz.loop.nest.exit

fuzz.loop.nest.body:                              ; preds = %fuzz.loop.nest.header
  %fuzz.loop.trip.inner.mask = and i32 %idx, 3
  %fuzz.loop.trip.inner = add i32 %fuzz.loop.trip.inner.mask, 1
  %fuzz.loop.cond.inner = icmp ult i32 0, %fuzz.loop.trip.inner
  br i1 %fuzz.loop.cond.inner, label %fuzz.nested.loop.body, label %fuzz.nested.loop.exit

fuzz.nested.loop.body:                            ; preds = %fuzz.loop.nest.body
  %fuzz.cfg.rotcascade.idiom.shift.seed = add i32 %idx, 1
  %fuzz.cfg.rotcascade.idiom.shift = and i32 %fuzz.cfg.rotcascade.idiom.shift.seed, 31
  %fuzz.cfg.rotcascade.idiom.inv.raw = sub i32 32, %fuzz.cfg.rotcascade.idiom.shift
  %fuzz.cfg.rotcascade.idiom.inv = and i32 %fuzz.cfg.rotcascade.idiom.inv.raw, 31
  %fuzz.cfg.rotcascade.idiom.rotl.lo = shl i32 %fuzz.loop.nest.acc, %fuzz.cfg.rotcascade.idiom.shift
  %fuzz.cfg.rotcascade.idiom.rotl.hi = lshr i32 %fuzz.loop.nest.acc, %fuzz.cfg.rotcascade.idiom.inv
  %fuzz.cfg.rotcascade.idiom.rotl = or i32 %fuzz.cfg.rotcascade.idiom.rotl.lo, %fuzz.cfg.rotcascade.idiom.rotl.hi
  %fuzz.cfg.rotcascade.idiom.rotr.lo = lshr i32 %idx, %fuzz.cfg.rotcascade.idiom.shift
  %fuzz.cfg.rotcascade.idiom.rotr.hi = shl i32 %idx, %fuzz.cfg.rotcascade.idiom.inv
  %fuzz.cfg.rotcascade.idiom.rotr = or i32 %fuzz.cfg.rotcascade.idiom.rotr.lo, %fuzz.cfg.rotcascade.idiom.rotr.hi
  %fuzz.cfg.rotcascade.idiom.pop = call i32 @llvm.ctpop.i32(i32 %fuzz.cfg.rotcascade.idiom.rotl)
  %fuzz.cfg.rotcascade.idiom.lt = icmp ult i32 %fuzz.cfg.rotcascade.idiom.pop, 17
  %fuzz.cfg.rotcascade.idiom.mask.sext = sext i1 %fuzz.cfg.rotcascade.idiom.lt to i32
  %fuzz.cfg.rotcascade.idiom.merge.l = and i32 %fuzz.cfg.rotcascade.idiom.rotl, %fuzz.cfg.rotcascade.idiom.mask.sext
  %fuzz.cfg.rotcascade.idiom.mask.not = xor i32 %fuzz.cfg.rotcascade.idiom.mask.sext, -1
  %fuzz.cfg.rotcascade.idiom.merge.r = and i32 %fuzz.cfg.rotcascade.idiom.rotr, %fuzz.cfg.rotcascade.idiom.mask.not
  %fuzz.cfg.rotcascade.idiom.merge = or i32 %fuzz.cfg.rotcascade.idiom.merge.l, %fuzz.cfg.rotcascade.idiom.merge.r
  %fuzz.cfg.rotcascade.idiom.acc.pop = add i32 %fuzz.loop.nest.acc, %fuzz.cfg.rotcascade.idiom.pop
  %fuzz.cfg.rotcascade.idiom.acc.next = xor i32 %fuzz.cfg.rotcascade.idiom.merge, %fuzz.cfg.rotcascade.idiom.acc.pop
  %fuzz.cfg.rotcascade.idiom.seed.next = add i32 %idx, %fuzz.cfg.rotcascade.idiom.rotl
  %fuzz.cfg.rotcascade.idiom.shift.seed1 = add i32 %fuzz.cfg.rotcascade.idiom.seed.next, 8
  %fuzz.cfg.rotcascade.idiom.shift2 = and i32 %fuzz.cfg.rotcascade.idiom.shift.seed1, 31
  %fuzz.cfg.rotcascade.idiom.inv.raw3 = sub i32 32, %fuzz.cfg.rotcascade.idiom.shift2
  %fuzz.cfg.rotcascade.idiom.inv4 = and i32 %fuzz.cfg.rotcascade.idiom.inv.raw3, 31
  %fuzz.cfg.rotcascade.idiom.rotl.lo5 = shl i32 %fuzz.cfg.rotcascade.idiom.acc.next, %fuzz.cfg.rotcascade.idiom.shift2
  %fuzz.cfg.rotcascade.idiom.rotl.hi6 = lshr i32 %fuzz.cfg.rotcascade.idiom.acc.next, %fuzz.cfg.rotcascade.idiom.inv4
  %fuzz.cfg.rotcascade.idiom.rotl7 = or i32 %fuzz.cfg.rotcascade.idiom.rotl.lo5, %fuzz.cfg.rotcascade.idiom.rotl.hi6
  %fuzz.cfg.rotcascade.idiom.rotr.lo8 = lshr i32 %fuzz.cfg.rotcascade.idiom.seed.next, %fuzz.cfg.rotcascade.idiom.shift2
  %fuzz.cfg.rotcascade.idiom.rotr.hi9 = shl i32 %fuzz.cfg.rotcascade.idiom.seed.next, %fuzz.cfg.rotcascade.idiom.inv4
  %fuzz.cfg.rotcascade.idiom.rotr10 = or i32 %fuzz.cfg.rotcascade.idiom.rotr.lo8, %fuzz.cfg.rotcascade.idiom.rotr.hi9
  %fuzz.cfg.rotcascade.idiom.pop11 = call i32 @llvm.ctpop.i32(i32 %fuzz.cfg.rotcascade.idiom.rotl7)
  %fuzz.cfg.rotcascade.idiom.lt12 = icmp ult i32 %fuzz.cfg.rotcascade.idiom.pop11, 17
  %fuzz.cfg.rotcascade.idiom.mask.sext13 = sext i1 %fuzz.cfg.rotcascade.idiom.lt12 to i32
  %fuzz.cfg.rotcascade.idiom.merge.l14 = and i32 %fuzz.cfg.rotcascade.idiom.rotl7, %fuzz.cfg.rotcascade.idiom.mask.sext13
  %fuzz.cfg.rotcascade.idiom.mask.not15 = xor i32 %fuzz.cfg.rotcascade.idiom.mask.sext13, -1
  %fuzz.cfg.rotcascade.idiom.merge.r16 = and i32 %fuzz.cfg.rotcascade.idiom.rotr10, %fuzz.cfg.rotcascade.idiom.mask.not15
  %fuzz.cfg.rotcascade.idiom.merge17 = or i32 %fuzz.cfg.rotcascade.idiom.merge.l14, %fuzz.cfg.rotcascade.idiom.merge.r16
  %fuzz.cfg.rotcascade.idiom.acc.pop18 = add i32 %fuzz.cfg.rotcascade.idiom.acc.next, %fuzz.cfg.rotcascade.idiom.pop11
  %fuzz.cfg.rotcascade.idiom.acc.next19 = xor i32 %fuzz.cfg.rotcascade.idiom.merge17, %fuzz.cfg.rotcascade.idiom.acc.pop18
  %fuzz.cfg.rotcascade.idiom.seed.next20 = add i32 %fuzz.cfg.rotcascade.idiom.seed.next, %fuzz.cfg.rotcascade.idiom.rotl7
  %fuzz.cfg.rotcascade.idiom.shift.seed21 = add i32 %fuzz.cfg.rotcascade.idiom.seed.next20, 15
  %fuzz.cfg.rotcascade.idiom.shift22 = and i32 %fuzz.cfg.rotcascade.idiom.shift.seed21, 31
  %fuzz.cfg.rotcascade.idiom.inv.raw23 = sub i32 32, %fuzz.cfg.rotcascade.idiom.shift22
  %fuzz.cfg.rotcascade.idiom.inv24 = and i32 %fuzz.cfg.rotcascade.idiom.inv.raw23, 31
  %fuzz.cfg.rotcascade.idiom.rotl.lo25 = shl i32 %fuzz.cfg.rotcascade.idiom.acc.next19, %fuzz.cfg.rotcascade.idiom.shift22
  %fuzz.cfg.rotcascade.idiom.rotl.hi26 = lshr i32 %fuzz.cfg.rotcascade.idiom.acc.next19, %fuzz.cfg.rotcascade.idiom.inv24
  %fuzz.cfg.rotcascade.idiom.rotl27 = or i32 %fuzz.cfg.rotcascade.idiom.rotl.lo25, %fuzz.cfg.rotcascade.idiom.rotl.hi26
  %fuzz.cfg.rotcascade.idiom.rotr.lo28 = lshr i32 %fuzz.cfg.rotcascade.idiom.seed.next20, %fuzz.cfg.rotcascade.idiom.shift22
  %fuzz.cfg.rotcascade.idiom.rotr.hi29 = shl i32 %fuzz.cfg.rotcascade.idiom.seed.next20, %fuzz.cfg.rotcascade.idiom.inv24
  %fuzz.cfg.rotcascade.idiom.rotr30 = or i32 %fuzz.cfg.rotcascade.idiom.rotr.lo28, %fuzz.cfg.rotcascade.idiom.rotr.hi29
  %fuzz.cfg.rotcascade.idiom.pop31 = call i32 @llvm.ctpop.i32(i32 %fuzz.cfg.rotcascade.idiom.rotl27)
  %fuzz.cfg.rotcascade.idiom.lt32 = icmp ult i32 %fuzz.cfg.rotcascade.idiom.pop31, 17
  %fuzz.cfg.rotcascade.idiom.mask.select = select i1 %fuzz.cfg.rotcascade.idiom.lt32, i32 -1, i32 0
  %fuzz.cfg.rotcascade.idiom.merge.l33 = and i32 %fuzz.cfg.rotcascade.idiom.rotl27, %fuzz.cfg.rotcascade.idiom.mask.select
  %fuzz.cfg.rotcascade.idiom.mask.not34 = xor i32 %fuzz.cfg.rotcascade.idiom.mask.select, -1
  %fuzz.cfg.rotcascade.idiom.merge.r35 = and i32 %fuzz.cfg.rotcascade.idiom.rotr30, %fuzz.cfg.rotcascade.idiom.mask.not34
  %fuzz.cfg.rotcascade.idiom.merge36 = or i32 %fuzz.cfg.rotcascade.idiom.merge.l33, %fuzz.cfg.rotcascade.idiom.merge.r35
  %fuzz.cfg.rotcascade.idiom.acc.pop37 = add i32 %fuzz.cfg.rotcascade.idiom.acc.next19, %fuzz.cfg.rotcascade.idiom.pop31
  %fuzz.cfg.rotcascade.idiom.acc.next38 = xor i32 %fuzz.cfg.rotcascade.idiom.merge36, %fuzz.cfg.rotcascade.idiom.acc.pop37
  %fuzz.cfg.rotcascade.idiom.seed.next39 = add i32 %fuzz.cfg.rotcascade.idiom.seed.next20, %fuzz.cfg.rotcascade.idiom.rotl27
  %fuzz.cfg.rotcascade.idiom.shift.seed40 = add i32 %fuzz.cfg.rotcascade.idiom.seed.next39, 22
  %fuzz.cfg.rotcascade.idiom.shift41 = and i32 %fuzz.cfg.rotcascade.idiom.shift.seed40, 31
  %fuzz.cfg.rotcascade.idiom.inv.raw42 = sub i32 32, %fuzz.cfg.rotcascade.idiom.shift41
  %fuzz.cfg.rotcascade.idiom.inv43 = and i32 %fuzz.cfg.rotcascade.idiom.inv.raw42, 31
  %fuzz.cfg.rotcascade.idiom.rotl.lo44 = shl i32 %fuzz.cfg.rotcascade.idiom.acc.next38, %fuzz.cfg.rotcascade.idiom.shift41
  %fuzz.cfg.rotcascade.idiom.rotl.hi45 = lshr i32 %fuzz.cfg.rotcascade.idiom.acc.next38, %fuzz.cfg.rotcascade.idiom.inv43
  %fuzz.cfg.rotcascade.idiom.rotl46 = or i32 %fuzz.cfg.rotcascade.idiom.rotl.lo44, %fuzz.cfg.rotcascade.idiom.rotl.hi45
  %fuzz.cfg.rotcascade.idiom.rotr.lo47 = lshr i32 %fuzz.cfg.rotcascade.idiom.seed.next39, %fuzz.cfg.rotcascade.idiom.shift41
  %fuzz.cfg.rotcascade.idiom.rotr.hi48 = shl i32 %fuzz.cfg.rotcascade.idiom.seed.next39, %fuzz.cfg.rotcascade.idiom.inv43
  %fuzz.cfg.rotcascade.idiom.rotr49 = or i32 %fuzz.cfg.rotcascade.idiom.rotr.lo47, %fuzz.cfg.rotcascade.idiom.rotr.hi48
  %fuzz.cfg.rotcascade.idiom.pop50 = call i32 @llvm.ctpop.i32(i32 %fuzz.cfg.rotcascade.idiom.rotl46)
  %fuzz.cfg.rotcascade.idiom.lt51 = icmp ult i32 %fuzz.cfg.rotcascade.idiom.pop50, 17
  %fuzz.cfg.rotcascade.idiom.mask.select52 = select i1 %fuzz.cfg.rotcascade.idiom.lt51, i32 -1, i32 0
  %fuzz.cfg.rotcascade.idiom.merge.l53 = and i32 %fuzz.cfg.rotcascade.idiom.rotl46, %fuzz.cfg.rotcascade.idiom.mask.select52
  %fuzz.cfg.rotcascade.idiom.mask.not54 = xor i32 %fuzz.cfg.rotcascade.idiom.mask.select52, -1
  %fuzz.cfg.rotcascade.idiom.merge.r55 = and i32 %fuzz.cfg.rotcascade.idiom.rotr49, %fuzz.cfg.rotcascade.idiom.mask.not54
  %fuzz.cfg.rotcascade.idiom.merge56 = or i32 %fuzz.cfg.rotcascade.idiom.merge.l53, %fuzz.cfg.rotcascade.idiom.merge.r55
  %fuzz.cfg.rotcascade.idiom.acc.pop57 = add i32 %fuzz.cfg.rotcascade.idiom.acc.next38, %fuzz.cfg.rotcascade.idiom.pop50
  %fuzz.cfg.rotcascade.idiom.acc.next58 = xor i32 %fuzz.cfg.rotcascade.idiom.merge56, %fuzz.cfg.rotcascade.idiom.acc.pop57
  %fuzz.cfg.rotcascade.idiom.seed.next59 = add i32 %fuzz.cfg.rotcascade.idiom.seed.next39, %fuzz.cfg.rotcascade.idiom.rotl46
  %fuzz.cfg.rotcascade.idiom.seed.sub = sub i32 %fuzz.cfg.rotcascade.idiom.seed.next59, %fuzz.cfg.rotcascade.idiom.acc.next58
  %fuzz.cfg.i64mulfold.idiom.a.byte.trunc = trunc i32 %fuzz.cfg.rotcascade.idiom.seed.sub to i8
  %fuzz.cfg.i64mulfold.idiom.a.byte.zext = zext i8 %fuzz.cfg.i64mulfold.idiom.a.byte.trunc to i32
  %fuzz.cfg.i64mulfold.idiom.b.half.trunc = trunc i32 1 to i16
  %fuzz.cfg.i64mulfold.idiom.b.half.zext = zext i16 %fuzz.cfg.i64mulfold.idiom.b.half.trunc to i32
  %fuzz.cfg.i64mulfold.idiom.a.i8 = trunc i32 %fuzz.cfg.i64mulfold.idiom.a.byte.zext to i8
  %fuzz.cfg.i64mulfold.idiom.a.sext = sext i8 %fuzz.cfg.i64mulfold.idiom.a.i8 to i64
  %fuzz.cfg.i64mulfold.idiom.b.zext = zext i32 %fuzz.cfg.i64mulfold.idiom.b.half.zext to i64
  %fuzz.cfg.i64mulfold.idiom.mul = mul i64 %fuzz.cfg.i64mulfold.idiom.a.sext, %fuzz.cfg.i64mulfold.idiom.b.zext
  %fuzz.cfg.i64mulfold.idiom.mul.shl = shl i64 %fuzz.cfg.i64mulfold.idiom.mul, 5
  %fuzz.cfg.i64mulfold.idiom.acc.add = add i64 64, %fuzz.cfg.i64mulfold.idiom.mul
  %fuzz.cfg.i64mulfold.idiom.a.byte.shr = lshr i32 %fuzz.cfg.rotcascade.idiom.seed.sub, 8
  %fuzz.cfg.i64mulfold.idiom.a.byte.trunc60 = trunc i32 %fuzz.cfg.i64mulfold.idiom.a.byte.shr to i8
  %fuzz.cfg.i64mulfold.idiom.a.byte.zext61 = zext i8 %fuzz.cfg.i64mulfold.idiom.a.byte.trunc60 to i32
  %fuzz.cfg.i64mulfold.idiom.b.half.shr = lshr i32 1, 16
  %fuzz.cfg.i64mulfold.idiom.b.half.trunc62 = trunc i32 %fuzz.cfg.i64mulfold.idiom.b.half.shr to i16
  %fuzz.cfg.i64mulfold.idiom.b.half.sext = sext i16 %fuzz.cfg.i64mulfold.idiom.b.half.trunc62 to i32
  %fuzz.cfg.i64mulfold.idiom.a.zext = zext i32 %fuzz.cfg.i64mulfold.idiom.a.byte.zext61 to i64
  %fuzz.cfg.i64mulfold.idiom.b.sext = sext i32 %fuzz.cfg.i64mulfold.idiom.b.half.sext to i64
  %fuzz.cfg.i64mulfold.idiom.mul63 = mul i64 %fuzz.cfg.i64mulfold.idiom.a.zext, %fuzz.cfg.i64mulfold.idiom.b.sext
  %fuzz.cfg.i64mulfold.idiom.mul.shl64 = shl i64 %fuzz.cfg.i64mulfold.idiom.mul63, 10
  %fuzz.cfg.i64mulfold.idiom.acc.add65 = add i64 %fuzz.cfg.i64mulfold.idiom.acc.add, %fuzz.cfg.i64mulfold.idiom.mul63
  %fuzz.cfg.i64mulfold.idiom.a.byte.shr66 = lshr i32 %fuzz.cfg.rotcascade.idiom.seed.sub, 16
  %fuzz.cfg.i64mulfold.idiom.a.byte.trunc67 = trunc i32 %fuzz.cfg.i64mulfold.idiom.a.byte.shr66 to i8
  %fuzz.cfg.i64mulfold.idiom.a.byte.zext68 = zext i8 %fuzz.cfg.i64mulfold.idiom.a.byte.trunc67 to i32
  %fuzz.cfg.i64mulfold.idiom.b.half.trunc69 = trunc i32 1 to i16
  %fuzz.cfg.i64mulfold.idiom.b.half.sext70 = sext i16 %fuzz.cfg.i64mulfold.idiom.b.half.trunc69 to i32
  %fuzz.cfg.i64mulfold.idiom.a.zext71 = zext i32 %fuzz.cfg.i64mulfold.idiom.a.byte.zext68 to i64
  %fuzz.cfg.i64mulfold.idiom.b.sext72 = sext i32 %fuzz.cfg.i64mulfold.idiom.b.half.sext70 to i64
  %fuzz.cfg.i64mulfold.idiom.mul73 = mul i64 %fuzz.cfg.i64mulfold.idiom.a.zext71, %fuzz.cfg.i64mulfold.idiom.b.sext72
  %fuzz.cfg.i64mulfold.idiom.mul.shl74 = shl i64 %fuzz.cfg.i64mulfold.idiom.mul73, 15
  %fuzz.cfg.i64mulfold.idiom.acc.sub = sub i64 %fuzz.cfg.i64mulfold.idiom.acc.add65, %fuzz.cfg.i64mulfold.idiom.mul73
  %fuzz.cfg.i64mulfold.idiom.a.byte.shr75 = lshr i32 %fuzz.cfg.rotcascade.idiom.seed.sub, 24
  %fuzz.cfg.i64mulfold.idiom.a.byte.trunc76 = trunc i32 %fuzz.cfg.i64mulfold.idiom.a.byte.shr75 to i8
  %fuzz.cfg.i64mulfold.idiom.a.byte.zext77 = zext i8 %fuzz.cfg.i64mulfold.idiom.a.byte.trunc76 to i32
  %fuzz.cfg.i64mulfold.idiom.b.half.shr78 = lshr i32 1, 16
  %fuzz.cfg.i64mulfold.idiom.b.half.trunc79 = trunc i32 %fuzz.cfg.i64mulfold.idiom.b.half.shr78 to i16
  %fuzz.cfg.i64mulfold.idiom.b.half.zext80 = zext i16 %fuzz.cfg.i64mulfold.idiom.b.half.trunc79 to i32
  %fuzz.cfg.i64mulfold.idiom.a.zext81 = zext i32 %fuzz.cfg.i64mulfold.idiom.a.byte.zext77 to i64
  %fuzz.cfg.i64mulfold.idiom.b.zext82 = zext i32 %fuzz.cfg.i64mulfold.idiom.b.half.zext80 to i64
  %fuzz.cfg.i64mulfold.idiom.mul83 = mul i64 %fuzz.cfg.i64mulfold.idiom.a.zext81, %fuzz.cfg.i64mulfold.idiom.b.zext82
  %fuzz.cfg.i64mulfold.idiom.mul.shl84 = shl i64 %fuzz.cfg.i64mulfold.idiom.mul83, 20
  %fuzz.cfg.i64mulfold.idiom.acc.shr = lshr i64 %fuzz.cfg.i64mulfold.idiom.acc.sub, 3
  %fuzz.cfg.i64mulfold.idiom.acc.shift.add = add i64 %fuzz.cfg.i64mulfold.idiom.acc.shr, %fuzz.cfg.i64mulfold.idiom.mul.shl84
  %fuzz.cfg.i64mulfold.idiom.lo = trunc i64 %fuzz.cfg.i64mulfold.idiom.acc.shift.add to i32
  %fuzz.cfg.i64mulfold.idiom.hi.shr = lshr i64 %fuzz.cfg.i64mulfold.idiom.acc.shift.add, 32
  %fuzz.cfg.i64mulfold.idiom.hi = trunc i64 %fuzz.cfg.i64mulfold.idiom.hi.shr to i32
  %fuzz.cfg.i64mulfold.idiom.rot.lo = shl i32 %fuzz.cfg.i64mulfold.idiom.lo, 13
  %fuzz.cfg.i64mulfold.idiom.rot.hi = lshr i32 %fuzz.cfg.i64mulfold.idiom.lo, 19
  %fuzz.cfg.i64mulfold.idiom.rot = or i32 %fuzz.cfg.i64mulfold.idiom.rot.lo, %fuzz.cfg.i64mulfold.idiom.rot.hi
  %fuzz.cfg.i64mulfold.idiom.rot.mask = and i32 %fuzz.cfg.i64mulfold.idiom.rot, -65536
  %fuzz.cfg.i64mulfold.idiom.hi.mask = and i32 %fuzz.cfg.i64mulfold.idiom.hi, 65535
  %fuzz.cfg.i64mulfold.idiom.pack = or i32 %fuzz.cfg.i64mulfold.idiom.rot.mask, %fuzz.cfg.i64mulfold.idiom.hi.mask
  %fuzz.cfg.lookup.idiom.index = and i32 %fuzz.cfg.i64mulfold.idiom.pack, 7
  %fuzz.cfg.lookup.idiom.entry.cmp = icmp ult i32 %idx, %fuzz.cfg.i64mulfold.idiom.pack
  %fuzz.cfg.lookup.idiom.entry.sel = select i1 %fuzz.cfg.lookup.idiom.entry.cmp, i32 %idx, i32 %fuzz.cfg.i64mulfold.idiom.pack
  %fuzz.cfg.lookup.idiom.entry.is = icmp eq i32 %fuzz.cfg.lookup.idiom.index, 0
  %fuzz.cfg.lookup.idiom.entry.pick = select i1 %fuzz.cfg.lookup.idiom.entry.is, i32 %fuzz.cfg.lookup.idiom.entry.sel, i32 -1136460955
  %fuzz.cfg.lookup.idiom.entry.add = add i32 %fuzz.cfg.i64mulfold.idiom.pack, 18
  %fuzz.cfg.lookup.idiom.entry.is85 = icmp eq i32 %fuzz.cfg.lookup.idiom.index, 1
  %fuzz.cfg.lookup.idiom.entry.pick86 = select i1 %fuzz.cfg.lookup.idiom.entry.is85, i32 %fuzz.cfg.lookup.idiom.entry.add, i32 %fuzz.cfg.lookup.idiom.entry.pick
  %fuzz.cfg.lookup.idiom.entry.shl = shl i32 %fuzz.cfg.i64mulfold.idiom.pack, 2
  %fuzz.cfg.lookup.idiom.entry.xor = xor i32 %idx, %fuzz.cfg.lookup.idiom.entry.shl
  %fuzz.cfg.lookup.idiom.entry.is87 = icmp eq i32 %fuzz.cfg.lookup.idiom.index, 2
  %fuzz.cfg.lookup.idiom.entry.pick88 = select i1 %fuzz.cfg.lookup.idiom.entry.is87, i32 %fuzz.cfg.lookup.idiom.entry.xor, i32 %fuzz.cfg.lookup.idiom.entry.pick86
  %fuzz.cfg.lookup.idiom.entry.cmp89 = icmp ult i32 %fuzz.cfg.i64mulfold.idiom.pack, %idx
  %fuzz.cfg.lookup.idiom.entry.sel90 = select i1 %fuzz.cfg.lookup.idiom.entry.cmp89, i32 %fuzz.cfg.i64mulfold.idiom.pack, i32 %idx
  %fuzz.cfg.lookup.idiom.entry.is91 = icmp eq i32 %fuzz.cfg.lookup.idiom.index, 3
  %fuzz.cfg.lookup.idiom.entry.pick92 = select i1 %fuzz.cfg.lookup.idiom.entry.is91, i32 %fuzz.cfg.lookup.idiom.entry.sel90, i32 %fuzz.cfg.lookup.idiom.entry.pick88
  %fuzz.cfg.lookup.idiom.entry.shl93 = shl i32 %fuzz.cfg.i64mulfold.idiom.pack, 4
  %fuzz.cfg.lookup.idiom.entry.xor94 = xor i32 %idx, %fuzz.cfg.lookup.idiom.entry.shl93
  %fuzz.cfg.lookup.idiom.entry.is95 = icmp eq i32 %fuzz.cfg.lookup.idiom.index, 4
  %fuzz.cfg.lookup.idiom.entry.pick96 = select i1 %fuzz.cfg.lookup.idiom.entry.is95, i32 %fuzz.cfg.lookup.idiom.entry.xor94, i32 %fuzz.cfg.lookup.idiom.entry.pick92
  %fuzz.cfg.lookup.idiom.entry.add97 = add i32 %fuzz.cfg.i64mulfold.idiom.pack, 86
  %fuzz.cfg.lookup.idiom.entry.is98 = icmp eq i32 %fuzz.cfg.lookup.idiom.index, 5
  %fuzz.cfg.lookup.idiom.entry.pick99 = select i1 %fuzz.cfg.lookup.idiom.entry.is98, i32 %fuzz.cfg.lookup.idiom.entry.add97, i32 %fuzz.cfg.lookup.idiom.entry.pick96
  %fuzz.cfg.lookup.idiom.entry.add100 = add i32 %idx, 103
  %fuzz.cfg.lookup.idiom.entry.is101 = icmp eq i32 %fuzz.cfg.lookup.idiom.index, 6
  %fuzz.cfg.lookup.idiom.entry.pick102 = select i1 %fuzz.cfg.lookup.idiom.entry.is101, i32 %fuzz.cfg.lookup.idiom.entry.add100, i32 %fuzz.cfg.lookup.idiom.entry.pick99
  %fuzz.cfg.lookup.idiom.entry.shr = lshr i32 %fuzz.cfg.i64mulfold.idiom.pack, 7
  %fuzz.cfg.lookup.idiom.entry.sub = sub i32 %fuzz.cfg.lookup.idiom.entry.shr, %idx
  %fuzz.cfg.lookup.idiom.entry.is103 = icmp eq i32 %fuzz.cfg.lookup.idiom.index, 7
  %fuzz.cfg.lookup.idiom.entry.pick104 = select i1 %fuzz.cfg.lookup.idiom.entry.is103, i32 %fuzz.cfg.lookup.idiom.entry.sub, i32 %fuzz.cfg.lookup.idiom.entry.pick102
  %fuzz.cfg.vecsplat.idiom.byte.trunc = trunc i32 %fuzz.cfg.lookup.idiom.entry.pick104 to i8
  %fuzz.cfg.vecsplat.idiom.byte.zext = zext i8 %fuzz.cfg.vecsplat.idiom.byte.trunc to i32
  %fuzz.cfg.vecsplat.idiom.elt = add i32 %fuzz.cfg.vecsplat.idiom.byte.zext, 4
  %fuzz.cfg.vecsplat.idiom.byte.shr = lshr i32 %idx, 8
  %fuzz.cfg.vecsplat.idiom.byte.trunc105 = trunc i32 %fuzz.cfg.vecsplat.idiom.byte.shr to i8
  %fuzz.cfg.vecsplat.idiom.byte.zext106 = zext i8 %fuzz.cfg.vecsplat.idiom.byte.trunc105 to i32
  %fuzz.cfg.vecsplat.idiom.elt107 = add i32 %fuzz.cfg.vecsplat.idiom.byte.zext106, 263
  %fuzz.cfg.vecsplat.idiom.byte.shr108 = lshr i32 %fuzz.cfg.lookup.idiom.entry.pick104, 16
  %fuzz.cfg.vecsplat.idiom.byte.trunc109 = trunc i32 %fuzz.cfg.vecsplat.idiom.byte.shr108 to i8
  %fuzz.cfg.vecsplat.idiom.byte.zext110 = zext i8 %fuzz.cfg.vecsplat.idiom.byte.trunc109 to i32
  %fuzz.cfg.vecsplat.idiom.elt111 = add i32 %fuzz.cfg.vecsplat.idiom.byte.zext110, 515
  %fuzz.cfg.vecsplat.idiom.byte.shr112 = lshr i32 %idx, 24
  %fuzz.cfg.vecsplat.idiom.byte.trunc113 = trunc i32 %fuzz.cfg.vecsplat.idiom.byte.shr112 to i8
  %fuzz.cfg.vecsplat.idiom.byte.zext114 = zext i8 %fuzz.cfg.vecsplat.idiom.byte.trunc113 to i32
  %fuzz.cfg.vecsplat.idiom.elt115 = add i32 %fuzz.cfg.vecsplat.idiom.byte.zext114, 774
  %fuzz.vec.ins = insertelement <4 x i32> zeroinitializer, i32 %fuzz.cfg.vecsplat.idiom.elt, i32 0
  %fuzz.vec.ins116 = insertelement <4 x i32> %fuzz.vec.ins, i32 %fuzz.cfg.vecsplat.idiom.elt107, i32 1
  %fuzz.vec.ins117 = insertelement <4 x i32> %fuzz.vec.ins116, i32 %fuzz.cfg.vecsplat.idiom.elt111, i32 2
  %fuzz.vec.ins118 = insertelement <4 x i32> %fuzz.vec.ins117, i32 %fuzz.cfg.vecsplat.idiom.elt115, i32 3
  %fuzz.cfg.vecsplat.idiom.splat = shufflevector <4 x i32> %fuzz.vec.ins118, <4 x i32> %fuzz.vec.ins118, <4 x i32> <i32 2, i32 2, i32 2, i32 2>
  %fuzz.cfg.vecsplat.idiom.rot = shufflevector <4 x i32> %fuzz.vec.ins118, <4 x i32> %fuzz.vec.ins118, <4 x i32> <i32 2, i32 3, i32 0, i32 1>
  %fuzz.cfg.vecsplat.idiom.rev = shufflevector <4 x i32> %fuzz.vec.ins118, <4 x i32> %fuzz.vec.ins118, <4 x i32> <i32 3, i32 2, i32 1, i32 0>
  %fuzz.cfg.vecsplat.idiom.cmp = icmp ult <4 x i32> %fuzz.cfg.vecsplat.idiom.rot, %fuzz.cfg.vecsplat.idiom.splat
  %fuzz.cfg.vecsplat.idiom.select = select <4 x i1> %fuzz.cfg.vecsplat.idiom.cmp, <4 x i32> %fuzz.cfg.vecsplat.idiom.rev, <4 x i32> %fuzz.cfg.vecsplat.idiom.splat
  %fuzz.cfg.vecsplat.idiom.xor = xor <4 x i32> %fuzz.cfg.vecsplat.idiom.select, %fuzz.cfg.vecsplat.idiom.rot
  %fuzz.cfg.vecsplat.idiom.lane = extractelement <4 x i32> %fuzz.cfg.vecsplat.idiom.xor, i32 0
  %fuzz.cfg.vecsplat.idiom.fold.xor = xor i32 0, %fuzz.cfg.vecsplat.idiom.lane
  %fuzz.cfg.vecsplat.idiom.lane.byte = lshr i32 %fuzz.cfg.vecsplat.idiom.lane, 0
  %fuzz.cfg.vecsplat.idiom.lane119 = extractelement <4 x i32> %fuzz.cfg.vecsplat.idiom.xor, i32 1
  %fuzz.cfg.vecsplat.idiom.fold.add = add i32 %fuzz.cfg.vecsplat.idiom.fold.xor, %fuzz.cfg.vecsplat.idiom.lane119
  %fuzz.cfg.vecsplat.idiom.lane.byte120 = lshr i32 %fuzz.cfg.vecsplat.idiom.lane119, 4
  %fuzz.cfg.vecsplat.idiom.lane121 = extractelement <4 x i32> %fuzz.cfg.vecsplat.idiom.xor, i32 2
  %fuzz.cfg.vecsplat.idiom.fold.xor122 = xor i32 %fuzz.cfg.vecsplat.idiom.fold.add, %fuzz.cfg.vecsplat.idiom.lane121
  %fuzz.cfg.vecsplat.idiom.lane.byte123 = lshr i32 %fuzz.cfg.vecsplat.idiom.lane121, 8
  %fuzz.cfg.vecsplat.idiom.lane124 = extractelement <4 x i32> %fuzz.cfg.vecsplat.idiom.xor, i32 3
  %fuzz.cfg.vecsplat.idiom.fold.add125 = add i32 %fuzz.cfg.vecsplat.idiom.fold.xor122, %fuzz.cfg.vecsplat.idiom.lane124
  %fuzz.cfg.vecsplat.idiom.lane.byte126 = lshr i32 %fuzz.cfg.vecsplat.idiom.lane124, 12
  %fuzz.cfg.vecsplat.idiom.pack.mask = and i32 %fuzz.cfg.vecsplat.idiom.lane.byte, 255
  %fuzz.cfg.vecsplat.idiom.pack.add = add i32 0, %fuzz.cfg.vecsplat.idiom.pack.mask
  %fuzz.cfg.vecsplat.idiom.pack.mask127 = and i32 %fuzz.cfg.vecsplat.idiom.lane.byte120, 255
  %fuzz.cfg.vecsplat.idiom.pack.shift = shl i32 %fuzz.cfg.vecsplat.idiom.pack.mask127, 8
  %fuzz.cfg.vecsplat.idiom.pack.add128 = add i32 %fuzz.cfg.vecsplat.idiom.pack.add, %fuzz.cfg.vecsplat.idiom.pack.shift
  %fuzz.cfg.vecsplat.idiom.pack.mask129 = and i32 %fuzz.cfg.vecsplat.idiom.lane.byte123, 255
  %fuzz.cfg.vecsplat.idiom.pack.shift130 = shl i32 %fuzz.cfg.vecsplat.idiom.pack.mask129, 16
  %fuzz.cfg.vecsplat.idiom.pack.add131 = add i32 %fuzz.cfg.vecsplat.idiom.pack.add128, %fuzz.cfg.vecsplat.idiom.pack.shift130
  %fuzz.cfg.vecsplat.idiom.pack.mask132 = and i32 %fuzz.cfg.vecsplat.idiom.lane.byte126, 255
  %fuzz.cfg.vecsplat.idiom.pack.shift133 = shl i32 %fuzz.cfg.vecsplat.idiom.pack.mask132, 24
  %fuzz.cfg.vecsplat.idiom.pack.add134 = add i32 %fuzz.cfg.vecsplat.idiom.pack.add131, %fuzz.cfg.vecsplat.idiom.pack.shift133
  %fuzz.cfg.vecsplat.idiom.fold.sub = sub i32 %fuzz.cfg.vecsplat.idiom.fold.add125, %fuzz.cfg.vecsplat.idiom.pack.add134
  %fuzz.cfg.bitslice.idiom.shift.add = add i32 %fuzz.cfg.vecsplat.idiom.fold.sub, 15
  %fuzz.cfg.bitslice.idiom.shift = and i32 %fuzz.cfg.bitslice.idiom.shift.add, 31
  %fuzz.cfg.bitslice.idiom.inv.raw = sub i32 32, %fuzz.cfg.bitslice.idiom.shift
  %fuzz.cfg.bitslice.idiom.inv = and i32 %fuzz.cfg.bitslice.idiom.inv.raw, 31
  %fuzz.cfg.bitslice.idiom.rot.lo = shl i32 %fuzz.cfg.vecsplat.idiom.fold.sub, %fuzz.cfg.bitslice.idiom.shift
  %fuzz.cfg.bitslice.idiom.rot.hi = lshr i32 %fuzz.cfg.vecsplat.idiom.fold.sub, %fuzz.cfg.bitslice.idiom.inv
  %fuzz.cfg.bitslice.idiom.rot = or i32 %fuzz.cfg.bitslice.idiom.rot.lo, %fuzz.cfg.bitslice.idiom.rot.hi
  %fuzz.cfg.bitslice.idiom.a.shr1 = lshr i32 %fuzz.cfg.vecsplat.idiom.fold.sub, 1
  %fuzz.cfg.bitslice.idiom.d = xor i32 %idx, %fuzz.cfg.bitslice.idiom.a.shr1
  %fuzz.cfg.bitslice.idiom.ab = and i32 %fuzz.cfg.vecsplat.idiom.fold.sub, %idx
  %fuzz.cfg.bitslice.idiom.ac = and i32 %fuzz.cfg.vecsplat.idiom.fold.sub, %fuzz.cfg.bitslice.idiom.rot
  %fuzz.cfg.bitslice.idiom.bc = and i32 %idx, %fuzz.cfg.bitslice.idiom.rot
  %fuzz.cfg.bitslice.idiom.or2 = or i32 %fuzz.cfg.bitslice.idiom.ac, %fuzz.cfg.bitslice.idiom.bc
  %fuzz.cfg.bitslice.idiom.majority = or i32 %fuzz.cfg.bitslice.idiom.ab, %fuzz.cfg.bitslice.idiom.or2
  %fuzz.cfg.bitslice.idiom.choose.t = and i32 %fuzz.cfg.vecsplat.idiom.fold.sub, %idx
  %fuzz.cfg.bitslice.idiom.not.a = xor i32 %fuzz.cfg.vecsplat.idiom.fold.sub, -1
  %fuzz.cfg.bitslice.idiom.choose.f = and i32 %fuzz.cfg.bitslice.idiom.not.a, %fuzz.cfg.bitslice.idiom.rot
  %fuzz.cfg.bitslice.idiom.choose = or i32 %fuzz.cfg.bitslice.idiom.choose.t, %fuzz.cfg.bitslice.idiom.choose.f
  %fuzz.cfg.bitslice.idiom.xor.ab = xor i32 %fuzz.cfg.vecsplat.idiom.fold.sub, %idx
  %fuzz.cfg.bitslice.idiom.parity = xor i32 %fuzz.cfg.bitslice.idiom.xor.ab, %fuzz.cfg.bitslice.idiom.rot
  %fuzz.cfg.bitslice.idiom.lo = and i32 %fuzz.cfg.bitslice.idiom.parity, -1
  %fuzz.cfg.bitslice.idiom.not.mask = xor i32 -1, -1
  %fuzz.cfg.bitslice.idiom.hi = and i32 %fuzz.cfg.bitslice.idiom.parity, %fuzz.cfg.bitslice.idiom.not.mask
  %fuzz.cfg.bitslice.idiom.mask.select = or i32 %fuzz.cfg.bitslice.idiom.lo, %fuzz.cfg.bitslice.idiom.hi
  %fuzz.cfg.shift = and i32 %fuzz.cfg.bitslice.idiom.mask.select, 31
  %fuzz.cfg.fshr.dyn = call i32 @llvm.fshr.i32(i32 %fuzz.cfg.bitslice.idiom.mask.select, i32 3, i32 %fuzz.cfg.shift)
  %fuzz.nested.branch = icmp ugt i32 %fuzz.cfg.fshr.dyn, %idx
  %fuzz.cfg.i64pair.idiom.a64 = zext i32 %fuzz.cfg.fshr.dyn to i64
  %fuzz.cfg.i64pair.idiom.b64 = zext i32 31 to i64
  %fuzz.cfg.i64pair.idiom.pair.hi = shl i64 %fuzz.cfg.i64pair.idiom.a64, 32
  %fuzz.cfg.i64pair.idiom.pair = or i64 %fuzz.cfg.i64pair.idiom.pair.hi, %fuzz.cfg.i64pair.idiom.b64
  %fuzz.cfg.i64pair.idiom.mask64 = and i64 %fuzz.cfg.i64pair.idiom.pair, 71777214294589695
  %fuzz.cfg.i64pair.idiom.spread = mul i64 %fuzz.cfg.i64pair.idiom.mask64, 65793
  %fuzz.cfg.i64pair.idiom.spread.hi.shr = lshr i64 %fuzz.cfg.i64pair.idiom.spread, 32
  %fuzz.cfg.i64pair.idiom.spread.hi.i32 = trunc i64 %fuzz.cfg.i64pair.idiom.spread.hi.shr to i32
  %fuzz.cfg.i64pair.idiom.spread.lo.i32 = trunc i64 %fuzz.cfg.i64pair.idiom.spread to i32
  %fuzz.cfg.i64pair.idiom.spread.fold = xor i32 %fuzz.cfg.i64pair.idiom.spread.hi.i32, %fuzz.cfg.i64pair.idiom.spread.lo.i32
  %fuzz.cfg.nibblecarry.idiom.x.nib.mask = and i32 %fuzz.cfg.i64pair.idiom.spread.fold, 15
  %fuzz.cfg.nibblecarry.idiom.y.nib.shr = lshr i32 %idx, 12
  %fuzz.cfg.nibblecarry.idiom.y.nib.mask = and i32 %fuzz.cfg.nibblecarry.idiom.y.nib.shr, 15
  %fuzz.cfg.nibblecarry.idiom.carry.in = and i32 0, 1
  %fuzz.cfg.nibblecarry.idiom.sum.xy = add i32 %fuzz.cfg.nibblecarry.idiom.x.nib.mask, %fuzz.cfg.nibblecarry.idiom.y.nib.mask
  %fuzz.cfg.nibblecarry.idiom.sum = add i32 %fuzz.cfg.nibblecarry.idiom.sum.xy, %fuzz.cfg.nibblecarry.idiom.carry.in
  %fuzz.cfg.nibblecarry.idiom.sum.nib = and i32 %fuzz.cfg.nibblecarry.idiom.sum, 15
  %fuzz.cfg.nibblecarry.idiom.carry.raw = lshr i32 %fuzz.cfg.nibblecarry.idiom.sum, 4
  %fuzz.cfg.nibblecarry.idiom.carry.out = and i32 %fuzz.cfg.nibblecarry.idiom.carry.raw, 1
  %fuzz.cfg.nibblecarry.idiom.carry.cmp = icmp ugt i32 %fuzz.cfg.nibblecarry.idiom.sum, 15
  %fuzz.cfg.nibblecarry.idiom.carry.bit = shl i32 %fuzz.cfg.nibblecarry.idiom.carry.out, 3
  %fuzz.cfg.nibblecarry.idiom.nib.xor = xor i32 %fuzz.cfg.nibblecarry.idiom.sum.nib, %fuzz.cfg.nibblecarry.idiom.carry.bit
  %fuzz.cfg.nibblecarry.idiom.lane.nib = and i32 %fuzz.cfg.nibblecarry.idiom.nib.xor, 15
  %fuzz.cfg.nibblecarry.idiom.fold.add = add i32 0, %fuzz.cfg.nibblecarry.idiom.lane.nib
  %fuzz.cfg.nibblecarry.idiom.fold.next = xor i32 %fuzz.cfg.nibblecarry.idiom.fold.add, %fuzz.cfg.nibblecarry.idiom.carry.out
  %fuzz.cfg.nibblecarry.idiom.x.nib.shr = lshr i32 %fuzz.cfg.i64pair.idiom.spread.fold, 4
  %fuzz.cfg.nibblecarry.idiom.x.nib.mask135 = and i32 %fuzz.cfg.nibblecarry.idiom.x.nib.shr, 15
  %fuzz.cfg.nibblecarry.idiom.y.nib.shr136 = lshr i32 %idx, 16
  %fuzz.cfg.nibblecarry.idiom.y.nib.mask137 = and i32 %fuzz.cfg.nibblecarry.idiom.y.nib.shr136, 15
  %fuzz.cfg.nibblecarry.idiom.carry.in138 = and i32 %fuzz.cfg.nibblecarry.idiom.carry.out, 1
  %fuzz.cfg.nibblecarry.idiom.sum.xy139 = add i32 %fuzz.cfg.nibblecarry.idiom.x.nib.mask135, %fuzz.cfg.nibblecarry.idiom.y.nib.mask137
  %fuzz.cfg.nibblecarry.idiom.sum140 = add i32 %fuzz.cfg.nibblecarry.idiom.sum.xy139, %fuzz.cfg.nibblecarry.idiom.carry.in138
  %fuzz.cfg.nibblecarry.idiom.sum.nib141 = and i32 %fuzz.cfg.nibblecarry.idiom.sum140, 15
  %fuzz.cfg.nibblecarry.idiom.carry.raw142 = lshr i32 %fuzz.cfg.nibblecarry.idiom.sum140, 4
  %fuzz.cfg.nibblecarry.idiom.carry.out143 = and i32 %fuzz.cfg.nibblecarry.idiom.carry.raw142, 1
  %fuzz.cfg.nibblecarry.idiom.carry.cmp144 = icmp ugt i32 %fuzz.cfg.nibblecarry.idiom.sum140, 15
  %fuzz.cfg.nibblecarry.idiom.carry.bit145 = shl i32 %fuzz.cfg.nibblecarry.idiom.carry.out143, 3
  %fuzz.cfg.nibblecarry.idiom.nib.xor146 = xor i32 %fuzz.cfg.nibblecarry.idiom.sum.nib141, %fuzz.cfg.nibblecarry.idiom.carry.bit145
  %fuzz.cfg.nibblecarry.idiom.lane.nib147 = and i32 %fuzz.cfg.nibblecarry.idiom.nib.xor146, 15
  %fuzz.cfg.nibblecarry.idiom.hi.nib = shl i32 %fuzz.cfg.nibblecarry.idiom.lane.nib147, 4
  %fuzz.cfg.nibblecarry.idiom.byte.pack = or i32 %fuzz.cfg.nibblecarry.idiom.lane.nib, %fuzz.cfg.nibblecarry.idiom.hi.nib
  %fuzz.cfg.nibblecarry.idiom.fold.add148 = add i32 %fuzz.cfg.nibblecarry.idiom.fold.next, %fuzz.cfg.nibblecarry.idiom.lane.nib147
  %fuzz.cfg.nibblecarry.idiom.fold.next149 = xor i32 %fuzz.cfg.nibblecarry.idiom.fold.add148, %fuzz.cfg.nibblecarry.idiom.carry.out143
  %fuzz.cfg.nibblecarry.idiom.x.nib.shr150 = lshr i32 %fuzz.cfg.i64pair.idiom.spread.fold, 8
  %fuzz.cfg.nibblecarry.idiom.x.nib.mask151 = and i32 %fuzz.cfg.nibblecarry.idiom.x.nib.shr150, 15
  %fuzz.cfg.nibblecarry.idiom.y.nib.shr152 = lshr i32 %idx, 20
  %fuzz.cfg.nibblecarry.idiom.y.nib.mask153 = and i32 %fuzz.cfg.nibblecarry.idiom.y.nib.shr152, 15
  %fuzz.cfg.nibblecarry.idiom.carry.in154 = and i32 %fuzz.cfg.nibblecarry.idiom.carry.out143, 1
  %fuzz.cfg.nibblecarry.idiom.sum.xy155 = add i32 %fuzz.cfg.nibblecarry.idiom.x.nib.mask151, %fuzz.cfg.nibblecarry.idiom.y.nib.mask153
  %fuzz.cfg.nibblecarry.idiom.sum156 = add i32 %fuzz.cfg.nibblecarry.idiom.sum.xy155, %fuzz.cfg.nibblecarry.idiom.carry.in154
  %fuzz.cfg.nibblecarry.idiom.sum.nib157 = and i32 %fuzz.cfg.nibblecarry.idiom.sum156, 15
  %fuzz.cfg.nibblecarry.idiom.carry.raw158 = lshr i32 %fuzz.cfg.nibblecarry.idiom.sum156, 4
  %fuzz.cfg.nibblecarry.idiom.carry.out159 = and i32 %fuzz.cfg.nibblecarry.idiom.carry.raw158, 1
  %fuzz.cfg.nibblecarry.idiom.carry.cmp160 = icmp ugt i32 %fuzz.cfg.nibblecarry.idiom.sum156, 15
  %fuzz.cfg.nibblecarry.idiom.fold.nib = and i32 %fuzz.cfg.nibblecarry.idiom.fold.next149, 15
  %fuzz.cfg.nibblecarry.idiom.nib.add = add i32 %fuzz.cfg.nibblecarry.idiom.sum.nib157, %fuzz.cfg.nibblecarry.idiom.fold.nib
  %fuzz.cfg.nibblecarry.idiom.lane.nib161 = and i32 %fuzz.cfg.nibblecarry.idiom.nib.add, 15
  %fuzz.cfg.nibblecarry.idiom.fold.add162 = add i32 %fuzz.cfg.nibblecarry.idiom.fold.next149, %fuzz.cfg.nibblecarry.idiom.lane.nib161
  %fuzz.cfg.nibblecarry.idiom.fold.next163 = xor i32 %fuzz.cfg.nibblecarry.idiom.fold.add162, %fuzz.cfg.nibblecarry.idiom.carry.out159
  %fuzz.cfg.nibblecarry.idiom.x.nib.shr164 = lshr i32 %fuzz.cfg.i64pair.idiom.spread.fold, 12
  %fuzz.cfg.nibblecarry.idiom.x.nib.mask165 = and i32 %fuzz.cfg.nibblecarry.idiom.x.nib.shr164, 15
  %fuzz.cfg.nibblecarry.idiom.y.nib.shr166 = lshr i32 %idx, 24
  %fuzz.cfg.nibblecarry.idiom.y.nib.mask167 = and i32 %fuzz.cfg.nibblecarry.idiom.y.nib.shr166, 15
  %fuzz.cfg.nibblecarry.idiom.carry.in168 = and i32 %fuzz.cfg.nibblecarry.idiom.carry.out159, 1
  %fuzz.cfg.nibblecarry.idiom.sum.xy169 = add i32 %fuzz.cfg.nibblecarry.idiom.x.nib.mask165, %fuzz.cfg.nibblecarry.idiom.y.nib.mask167
  %fuzz.cfg.nibblecarry.idiom.sum170 = add i32 %fuzz.cfg.nibblecarry.idiom.sum.xy169, %fuzz.cfg.nibblecarry.idiom.carry.in168
  %fuzz.cfg.nibblecarry.idiom.sum.nib171 = and i32 %fuzz.cfg.nibblecarry.idiom.sum170, 15
  %fuzz.cfg.nibblecarry.idiom.carry.raw172 = lshr i32 %fuzz.cfg.nibblecarry.idiom.sum170, 4
  %fuzz.cfg.nibblecarry.idiom.carry.out173 = and i32 %fuzz.cfg.nibblecarry.idiom.carry.raw172, 1
  %fuzz.cfg.nibblecarry.idiom.carry.cmp174 = icmp ugt i32 %fuzz.cfg.nibblecarry.idiom.sum170, 15
  %fuzz.cfg.nibblecarry.idiom.carry.select = select i1 %fuzz.cfg.nibblecarry.idiom.carry.cmp174, i32 %fuzz.cfg.nibblecarry.idiom.x.nib.mask165, i32 %fuzz.cfg.nibblecarry.idiom.sum.nib171
  %fuzz.cfg.nibblecarry.idiom.lane.nib175 = and i32 %fuzz.cfg.nibblecarry.idiom.carry.select, 15
  %fuzz.cfg.nibblecarry.idiom.hi.nib176 = shl i32 %fuzz.cfg.nibblecarry.idiom.lane.nib175, 4
  %fuzz.cfg.nibblecarry.idiom.byte.pack177 = or i32 %fuzz.cfg.nibblecarry.idiom.lane.nib161, %fuzz.cfg.nibblecarry.idiom.hi.nib176
  %fuzz.cfg.nibblecarry.idiom.fold.add178 = add i32 %fuzz.cfg.nibblecarry.idiom.fold.next163, %fuzz.cfg.nibblecarry.idiom.lane.nib175
  %fuzz.cfg.nibblecarry.idiom.fold.next179 = xor i32 %fuzz.cfg.nibblecarry.idiom.fold.add178, %fuzz.cfg.nibblecarry.idiom.carry.out173
  %fuzz.cfg.nibblecarry.idiom.x.nib.shr180 = lshr i32 %fuzz.cfg.i64pair.idiom.spread.fold, 16
  %fuzz.cfg.nibblecarry.idiom.x.nib.mask181 = and i32 %fuzz.cfg.nibblecarry.idiom.x.nib.shr180, 15
  %fuzz.cfg.nibblecarry.idiom.y.nib.shr182 = lshr i32 %idx, 28
  %fuzz.cfg.nibblecarry.idiom.y.nib.mask183 = and i32 %fuzz.cfg.nibblecarry.idiom.y.nib.shr182, 15
  %fuzz.cfg.nibblecarry.idiom.carry.in184 = and i32 %fuzz.cfg.nibblecarry.idiom.carry.out173, 1
  %fuzz.cfg.nibblecarry.idiom.sum.xy185 = add i32 %fuzz.cfg.nibblecarry.idiom.x.nib.mask181, %fuzz.cfg.nibblecarry.idiom.y.nib.mask183
  %fuzz.cfg.nibblecarry.idiom.sum186 = add i32 %fuzz.cfg.nibblecarry.idiom.sum.xy185, %fuzz.cfg.nibblecarry.idiom.carry.in184
  %fuzz.cfg.nibblecarry.idiom.sum.nib187 = and i32 %fuzz.cfg.nibblecarry.idiom.sum186, 15
  %fuzz.cfg.nibblecarry.idiom.carry.raw188 = lshr i32 %fuzz.cfg.nibblecarry.idiom.sum186, 4
  %fuzz.cfg.nibblecarry.idiom.carry.out189 = and i32 %fuzz.cfg.nibblecarry.idiom.carry.raw188, 1
  %fuzz.cfg.nibblecarry.idiom.carry.cmp190 = icmp ugt i32 %fuzz.cfg.nibblecarry.idiom.sum186, 15
  %fuzz.cfg.nibblecarry.idiom.carry.select191 = select i1 %fuzz.cfg.nibblecarry.idiom.carry.cmp190, i32 %fuzz.cfg.nibblecarry.idiom.x.nib.mask181, i32 %fuzz.cfg.nibblecarry.idiom.sum.nib187
  %fuzz.cfg.nibblecarry.idiom.lane.nib192 = and i32 %fuzz.cfg.nibblecarry.idiom.carry.select191, 15
  %fuzz.cfg.nibblecarry.idiom.fold.add193 = add i32 %fuzz.cfg.nibblecarry.idiom.fold.next179, %fuzz.cfg.nibblecarry.idiom.lane.nib192
  %fuzz.cfg.nibblecarry.idiom.fold.next194 = xor i32 %fuzz.cfg.nibblecarry.idiom.fold.add193, %fuzz.cfg.nibblecarry.idiom.carry.out189
  %fuzz.cfg.nibblecarry.idiom.x.nib.shr195 = lshr i32 %fuzz.cfg.i64pair.idiom.spread.fold, 20
  %fuzz.cfg.nibblecarry.idiom.x.nib.mask196 = and i32 %fuzz.cfg.nibblecarry.idiom.x.nib.shr195, 15
  %fuzz.cfg.nibblecarry.idiom.y.nib.mask197 = and i32 %idx, 15
  %fuzz.cfg.nibblecarry.idiom.carry.in198 = and i32 %fuzz.cfg.nibblecarry.idiom.carry.out189, 1
  %fuzz.cfg.nibblecarry.idiom.sum.xy199 = add i32 %fuzz.cfg.nibblecarry.idiom.x.nib.mask196, %fuzz.cfg.nibblecarry.idiom.y.nib.mask197
  %fuzz.cfg.nibblecarry.idiom.sum200 = add i32 %fuzz.cfg.nibblecarry.idiom.sum.xy199, %fuzz.cfg.nibblecarry.idiom.carry.in198
  %fuzz.cfg.nibblecarry.idiom.sum.nib201 = and i32 %fuzz.cfg.nibblecarry.idiom.sum200, 15
  %fuzz.cfg.nibblecarry.idiom.carry.raw202 = lshr i32 %fuzz.cfg.nibblecarry.idiom.sum200, 4
  %fuzz.cfg.nibblecarry.idiom.carry.out203 = and i32 %fuzz.cfg.nibblecarry.idiom.carry.raw202, 1
  %fuzz.cfg.nibblecarry.idiom.carry.cmp204 = icmp ugt i32 %fuzz.cfg.nibblecarry.idiom.sum200, 15
  %fuzz.cfg.nibblecarry.idiom.lane.nib205 = and i32 %fuzz.cfg.nibblecarry.idiom.sum.nib201, 15
  %fuzz.cfg.nibblecarry.idiom.hi.nib206 = shl i32 %fuzz.cfg.nibblecarry.idiom.lane.nib205, 4
  %fuzz.cfg.nibblecarry.idiom.byte.pack207 = or i32 %fuzz.cfg.nibblecarry.idiom.lane.nib192, %fuzz.cfg.nibblecarry.idiom.hi.nib206
  %fuzz.cfg.nibblecarry.idiom.fold.add208 = add i32 %fuzz.cfg.nibblecarry.idiom.fold.next194, %fuzz.cfg.nibblecarry.idiom.lane.nib205
  %fuzz.cfg.nibblecarry.idiom.fold.next209 = xor i32 %fuzz.cfg.nibblecarry.idiom.fold.add208, %fuzz.cfg.nibblecarry.idiom.carry.out203
  %fuzz.cfg.nibblecarry.idiom.x.nib.shr210 = lshr i32 %fuzz.cfg.i64pair.idiom.spread.fold, 24
  %fuzz.cfg.nibblecarry.idiom.x.nib.mask211 = and i32 %fuzz.cfg.nibblecarry.idiom.x.nib.shr210, 15
  %fuzz.cfg.nibblecarry.idiom.y.nib.shr212 = lshr i32 %idx, 4
  %fuzz.cfg.nibblecarry.idiom.y.nib.mask213 = and i32 %fuzz.cfg.nibblecarry.idiom.y.nib.shr212, 15
  %fuzz.cfg.nibblecarry.idiom.carry.in214 = and i32 %fuzz.cfg.nibblecarry.idiom.carry.out203, 1
  %fuzz.cfg.nibblecarry.idiom.sum.xy215 = add i32 %fuzz.cfg.nibblecarry.idiom.x.nib.mask211, %fuzz.cfg.nibblecarry.idiom.y.nib.mask213
  %fuzz.cfg.nibblecarry.idiom.sum216 = add i32 %fuzz.cfg.nibblecarry.idiom.sum.xy215, %fuzz.cfg.nibblecarry.idiom.carry.in214
  %fuzz.cfg.nibblecarry.idiom.sum.nib217 = and i32 %fuzz.cfg.nibblecarry.idiom.sum216, 15
  %fuzz.cfg.nibblecarry.idiom.carry.raw218 = lshr i32 %fuzz.cfg.nibblecarry.idiom.sum216, 4
  %fuzz.cfg.nibblecarry.idiom.carry.out219 = and i32 %fuzz.cfg.nibblecarry.idiom.carry.raw218, 1
  %fuzz.cfg.nibblecarry.idiom.carry.cmp220 = icmp ugt i32 %fuzz.cfg.nibblecarry.idiom.sum216, 15
  %fuzz.cfg.nibblecarry.idiom.carry.bit221 = shl i32 %fuzz.cfg.nibblecarry.idiom.carry.out219, 3
  %fuzz.cfg.nibblecarry.idiom.nib.xor222 = xor i32 %fuzz.cfg.nibblecarry.idiom.sum.nib217, %fuzz.cfg.nibblecarry.idiom.carry.bit221
  %fuzz.cfg.nibblecarry.idiom.lane.nib223 = and i32 %fuzz.cfg.nibblecarry.idiom.nib.xor222, 15
  %fuzz.cfg.nibblecarry.idiom.fold.add224 = add i32 %fuzz.cfg.nibblecarry.idiom.fold.next209, %fuzz.cfg.nibblecarry.idiom.lane.nib223
  %fuzz.cfg.nibblecarry.idiom.fold.next225 = xor i32 %fuzz.cfg.nibblecarry.idiom.fold.add224, %fuzz.cfg.nibblecarry.idiom.carry.out219
  %fuzz.cfg.nibblecarry.idiom.x.nib.shr226 = lshr i32 %fuzz.cfg.i64pair.idiom.spread.fold, 28
  %fuzz.cfg.nibblecarry.idiom.x.nib.mask227 = and i32 %fuzz.cfg.nibblecarry.idiom.x.nib.shr226, 15
  %fuzz.cfg.nibblecarry.idiom.y.nib.shr228 = lshr i32 %idx, 8
  %fuzz.cfg.nibblecarry.idiom.y.nib.mask229 = and i32 %fuzz.cfg.nibblecarry.idiom.y.nib.shr228, 15
  %fuzz.cfg.nibblecarry.idiom.carry.in230 = and i32 %fuzz.cfg.nibblecarry.idiom.carry.out219, 1
  %fuzz.cfg.nibblecarry.idiom.sum.xy231 = add i32 %fuzz.cfg.nibblecarry.idiom.x.nib.mask227, %fuzz.cfg.nibblecarry.idiom.y.nib.mask229
  %fuzz.cfg.nibblecarry.idiom.sum232 = add i32 %fuzz.cfg.nibblecarry.idiom.sum.xy231, %fuzz.cfg.nibblecarry.idiom.carry.in230
  %fuzz.cfg.nibblecarry.idiom.sum.nib233 = and i32 %fuzz.cfg.nibblecarry.idiom.sum232, 15
  %fuzz.cfg.nibblecarry.idiom.carry.raw234 = lshr i32 %fuzz.cfg.nibblecarry.idiom.sum232, 4
  %fuzz.cfg.nibblecarry.idiom.carry.out235 = and i32 %fuzz.cfg.nibblecarry.idiom.carry.raw234, 1
  %fuzz.cfg.nibblecarry.idiom.carry.cmp236 = icmp ugt i32 %fuzz.cfg.nibblecarry.idiom.sum232, 15
  %fuzz.cfg.nibblecarry.idiom.lane.nib237 = and i32 %fuzz.cfg.nibblecarry.idiom.sum.nib233, 15
  %fuzz.cfg.nibblecarry.idiom.hi.nib238 = shl i32 %fuzz.cfg.nibblecarry.idiom.lane.nib237, 4
  %fuzz.cfg.nibblecarry.idiom.byte.pack239 = or i32 %fuzz.cfg.nibblecarry.idiom.lane.nib223, %fuzz.cfg.nibblecarry.idiom.hi.nib238
  %fuzz.cfg.nibblecarry.idiom.fold.add240 = add i32 %fuzz.cfg.nibblecarry.idiom.fold.next225, %fuzz.cfg.nibblecarry.idiom.lane.nib237
  %fuzz.cfg.nibblecarry.idiom.fold.next241 = xor i32 %fuzz.cfg.nibblecarry.idiom.fold.add240, %fuzz.cfg.nibblecarry.idiom.carry.out235
  %fuzz.cfg.nibblecarry.idiom.pack.mask = and i32 %fuzz.cfg.nibblecarry.idiom.byte.pack, 255
  %fuzz.cfg.nibblecarry.idiom.pack.add = add i32 0, %fuzz.cfg.nibblecarry.idiom.pack.mask
  %fuzz.cfg.nibblecarry.idiom.pack.mask242 = and i32 %fuzz.cfg.nibblecarry.idiom.byte.pack177, 255
  %fuzz.cfg.nibblecarry.idiom.pack.shift = shl i32 %fuzz.cfg.nibblecarry.idiom.pack.mask242, 8
  %fuzz.cfg.nibblecarry.idiom.pack.add243 = add i32 %fuzz.cfg.nibblecarry.idiom.pack.add, %fuzz.cfg.nibblecarry.idiom.pack.shift
  %fuzz.cfg.nibblecarry.idiom.pack.mask244 = and i32 %fuzz.cfg.nibblecarry.idiom.byte.pack207, 255
  %fuzz.cfg.nibblecarry.idiom.pack.shift245 = shl i32 %fuzz.cfg.nibblecarry.idiom.pack.mask244, 16
  %fuzz.cfg.nibblecarry.idiom.pack.add246 = add i32 %fuzz.cfg.nibblecarry.idiom.pack.add243, %fuzz.cfg.nibblecarry.idiom.pack.shift245
  %fuzz.cfg.nibblecarry.idiom.pack.mask247 = and i32 %fuzz.cfg.nibblecarry.idiom.byte.pack239, 255
  %fuzz.cfg.nibblecarry.idiom.pack.shift248 = shl i32 %fuzz.cfg.nibblecarry.idiom.pack.mask247, 24
  %fuzz.cfg.nibblecarry.idiom.pack.add249 = add i32 %fuzz.cfg.nibblecarry.idiom.pack.add246, %fuzz.cfg.nibblecarry.idiom.pack.shift248
  %fuzz.cfg.nibblecarry.idiom.fold.sub = sub i32 %fuzz.cfg.nibblecarry.idiom.fold.next241, %fuzz.cfg.nibblecarry.idiom.pack.add249
  %fuzz.cfg.bytehorner.idiom.a.byte.trunc = trunc i32 %fuzz.cfg.nibblecarry.idiom.fold.sub to i8
  %fuzz.cfg.bytehorner.idiom.a.byte.zext = zext i8 %fuzz.cfg.bytehorner.idiom.a.byte.trunc to i32
  %fuzz.cfg.bytehorner.idiom.b.byte.shr = lshr i32 %idx, 24
  %fuzz.cfg.bytehorner.idiom.b.byte.trunc = trunc i32 %fuzz.cfg.bytehorner.idiom.b.byte.shr to i8
  %fuzz.cfg.bytehorner.idiom.b.byte.zext = zext i8 %fuzz.cfg.bytehorner.idiom.b.byte.trunc to i32
  %fuzz.cfg.bytehorner.idiom.term.add = add i32 %fuzz.cfg.bytehorner.idiom.a.byte.zext, %fuzz.cfg.bytehorner.idiom.b.byte.zext
  %fuzz.cfg.bytehorner.idiom.horner.mul = mul i32 235, 17
  %fuzz.cfg.bytehorner.idiom.horner.add = add i32 %fuzz.cfg.bytehorner.idiom.horner.mul, %fuzz.cfg.bytehorner.idiom.term.add
  %fuzz.cfg.bytehorner.idiom.byte.mix = xor i32 %fuzz.cfg.bytehorner.idiom.horner.add, %fuzz.cfg.bytehorner.idiom.term.add
  %fuzz.cfg.bytehorner.idiom.a.byte.shr = lshr i32 %fuzz.cfg.nibblecarry.idiom.fold.sub, 8
  %fuzz.cfg.bytehorner.idiom.a.byte.trunc250 = trunc i32 %fuzz.cfg.bytehorner.idiom.a.byte.shr to i8
  %fuzz.cfg.bytehorner.idiom.a.byte.zext251 = zext i8 %fuzz.cfg.bytehorner.idiom.a.byte.trunc250 to i32
  %fuzz.cfg.bytehorner.idiom.b.byte.shr252 = lshr i32 %idx, 16
  %fuzz.cfg.bytehorner.idiom.b.byte.trunc253 = trunc i32 %fuzz.cfg.bytehorner.idiom.b.byte.shr252 to i8
  %fuzz.cfg.bytehorner.idiom.b.byte.zext254 = zext i8 %fuzz.cfg.bytehorner.idiom.b.byte.trunc253 to i32
  %fuzz.cfg.bytehorner.idiom.term.cmp = icmp ult i32 %fuzz.cfg.bytehorner.idiom.a.byte.zext251, %fuzz.cfg.bytehorner.idiom.b.byte.zext254
  %fuzz.cfg.bytehorner.idiom.term.max = select i1 %fuzz.cfg.bytehorner.idiom.term.cmp, i32 %fuzz.cfg.bytehorner.idiom.b.byte.zext254, i32 %fuzz.cfg.bytehorner.idiom.a.byte.zext251
  %fuzz.cfg.bytehorner.idiom.horner.mul255 = mul i32 %fuzz.cfg.bytehorner.idiom.horner.add, 19
  %fuzz.cfg.bytehorner.idiom.horner.add256 = add i32 %fuzz.cfg.bytehorner.idiom.horner.mul255, %fuzz.cfg.bytehorner.idiom.term.max
  %fuzz.cfg.bytehorner.idiom.byte.mix257 = xor i32 %fuzz.cfg.bytehorner.idiom.horner.add256, %fuzz.cfg.bytehorner.idiom.term.max
  %fuzz.cfg.bytehorner.idiom.a.byte.shr258 = lshr i32 %fuzz.cfg.nibblecarry.idiom.fold.sub, 16
  %fuzz.cfg.bytehorner.idiom.a.byte.trunc259 = trunc i32 %fuzz.cfg.bytehorner.idiom.a.byte.shr258 to i8
  %fuzz.cfg.bytehorner.idiom.a.byte.zext260 = zext i8 %fuzz.cfg.bytehorner.idiom.a.byte.trunc259 to i32
  %fuzz.cfg.bytehorner.idiom.b.byte.shr261 = lshr i32 %idx, 8
  %fuzz.cfg.bytehorner.idiom.b.byte.trunc262 = trunc i32 %fuzz.cfg.bytehorner.idiom.b.byte.shr261 to i8
  %fuzz.cfg.bytehorner.idiom.b.byte.zext263 = zext i8 %fuzz.cfg.bytehorner.idiom.b.byte.trunc262 to i32
  %fuzz.cfg.bytehorner.idiom.term.shl = shl i32 %fuzz.cfg.bytehorner.idiom.b.byte.zext263, 2
  %fuzz.cfg.bytehorner.idiom.term.xor = xor i32 %fuzz.cfg.bytehorner.idiom.a.byte.zext260, %fuzz.cfg.bytehorner.idiom.term.shl
  %fuzz.cfg.bytehorner.idiom.horner.mul264 = mul i32 %fuzz.cfg.bytehorner.idiom.horner.add256, 21
  %fuzz.cfg.bytehorner.idiom.horner.add265 = add i32 %fuzz.cfg.bytehorner.idiom.horner.mul264, %fuzz.cfg.bytehorner.idiom.term.xor
  %fuzz.cfg.bytehorner.idiom.byte.mix266 = xor i32 %fuzz.cfg.bytehorner.idiom.horner.add265, %fuzz.cfg.bytehorner.idiom.term.xor
  %fuzz.cfg.bytehorner.idiom.a.byte.shr267 = lshr i32 %fuzz.cfg.nibblecarry.idiom.fold.sub, 24
  %fuzz.cfg.bytehorner.idiom.a.byte.trunc268 = trunc i32 %fuzz.cfg.bytehorner.idiom.a.byte.shr267 to i8
  %fuzz.cfg.bytehorner.idiom.a.byte.zext269 = zext i8 %fuzz.cfg.bytehorner.idiom.a.byte.trunc268 to i32
  %fuzz.cfg.bytehorner.idiom.b.byte.trunc270 = trunc i32 %idx to i8
  %fuzz.cfg.bytehorner.idiom.b.byte.zext271 = zext i8 %fuzz.cfg.bytehorner.idiom.b.byte.trunc270 to i32
  %fuzz.cfg.bytehorner.idiom.term.mul = mul i32 %fuzz.cfg.bytehorner.idiom.a.byte.zext269, 6
  %fuzz.cfg.bytehorner.idiom.term.bias = add i32 %fuzz.cfg.bytehorner.idiom.term.mul, %fuzz.cfg.bytehorner.idiom.b.byte.zext271
  %fuzz.cfg.bytehorner.idiom.horner.mul272 = mul i32 %fuzz.cfg.bytehorner.idiom.horner.add265, 23
  %fuzz.cfg.bytehorner.idiom.horner.add273 = add i32 %fuzz.cfg.bytehorner.idiom.horner.mul272, %fuzz.cfg.bytehorner.idiom.term.bias
  %fuzz.cfg.bytehorner.idiom.byte.mix274 = xor i32 %fuzz.cfg.bytehorner.idiom.horner.add273, %fuzz.cfg.bytehorner.idiom.term.bias
  %fuzz.cfg.bytehorner.idiom.pack.mask = and i32 %fuzz.cfg.bytehorner.idiom.byte.mix, 255
  %fuzz.cfg.bytehorner.idiom.pack.or = or i32 0, %fuzz.cfg.bytehorner.idiom.pack.mask
  %fuzz.cfg.bytehorner.idiom.pack.mask275 = and i32 %fuzz.cfg.bytehorner.idiom.byte.mix257, 255
  %fuzz.cfg.bytehorner.idiom.pack.shift = shl i32 %fuzz.cfg.bytehorner.idiom.pack.mask275, 8
  %fuzz.cfg.bytehorner.idiom.pack.or276 = or i32 %fuzz.cfg.bytehorner.idiom.pack.or, %fuzz.cfg.bytehorner.idiom.pack.shift
  %fuzz.cfg.bytehorner.idiom.pack.mask277 = and i32 %fuzz.cfg.bytehorner.idiom.byte.mix266, 255
  %fuzz.cfg.bytehorner.idiom.pack.shift278 = shl i32 %fuzz.cfg.bytehorner.idiom.pack.mask277, 16
  %fuzz.cfg.bytehorner.idiom.pack.or279 = or i32 %fuzz.cfg.bytehorner.idiom.pack.or276, %fuzz.cfg.bytehorner.idiom.pack.shift278
  %fuzz.cfg.bytehorner.idiom.pack.mask280 = and i32 %fuzz.cfg.bytehorner.idiom.byte.mix274, 255
  %fuzz.cfg.bytehorner.idiom.pack.shift281 = shl i32 %fuzz.cfg.bytehorner.idiom.pack.mask280, 24
  %fuzz.cfg.bytehorner.idiom.pack.or282 = or i32 %fuzz.cfg.bytehorner.idiom.pack.or279, %fuzz.cfg.bytehorner.idiom.pack.shift281
  %fuzz.cfg.bytehorner.idiom.acc.xor = xor i32 %fuzz.cfg.bytehorner.idiom.pack.or282, %fuzz.cfg.bytehorner.idiom.horner.add273
  %fuzz.cfg.bytehorner.idiom.a.byte.trunc283 = trunc i32 %fuzz.cfg.bytehorner.idiom.acc.xor to i8
  %fuzz.cfg.bytehorner.idiom.a.byte.zext284 = zext i8 %fuzz.cfg.bytehorner.idiom.a.byte.trunc283 to i32
  %fuzz.cfg.bytehorner.idiom.b.byte.shr285 = lshr i32 %idx, 24
  %fuzz.cfg.bytehorner.idiom.b.byte.trunc286 = trunc i32 %fuzz.cfg.bytehorner.idiom.b.byte.shr285 to i8
  %fuzz.cfg.bytehorner.idiom.b.byte.zext287 = zext i8 %fuzz.cfg.bytehorner.idiom.b.byte.trunc286 to i32
  %fuzz.cfg.bytehorner.idiom.term.cmp288 = icmp ult i32 %fuzz.cfg.bytehorner.idiom.a.byte.zext284, %fuzz.cfg.bytehorner.idiom.b.byte.zext287
  %fuzz.cfg.bytehorner.idiom.term.max289 = select i1 %fuzz.cfg.bytehorner.idiom.term.cmp288, i32 %fuzz.cfg.bytehorner.idiom.b.byte.zext287, i32 %fuzz.cfg.bytehorner.idiom.a.byte.zext284
  %fuzz.cfg.bytehorner.idiom.horner.mul290 = mul i32 180, 17
  %fuzz.cfg.bytehorner.idiom.horner.add291 = add i32 %fuzz.cfg.bytehorner.idiom.horner.mul290, %fuzz.cfg.bytehorner.idiom.term.max289
  %fuzz.cfg.bytehorner.idiom.byte.mix292 = xor i32 %fuzz.cfg.bytehorner.idiom.horner.add291, %fuzz.cfg.bytehorner.idiom.term.max289
  %fuzz.cfg.bytehorner.idiom.a.byte.shr293 = lshr i32 %fuzz.cfg.bytehorner.idiom.acc.xor, 8
  %fuzz.cfg.bytehorner.idiom.a.byte.trunc294 = trunc i32 %fuzz.cfg.bytehorner.idiom.a.byte.shr293 to i8
  %fuzz.cfg.bytehorner.idiom.a.byte.zext295 = zext i8 %fuzz.cfg.bytehorner.idiom.a.byte.trunc294 to i32
  %fuzz.cfg.bytehorner.idiom.b.byte.shr296 = lshr i32 %idx, 16
  %fuzz.cfg.bytehorner.idiom.b.byte.trunc297 = trunc i32 %fuzz.cfg.bytehorner.idiom.b.byte.shr296 to i8
  %fuzz.cfg.bytehorner.idiom.b.byte.zext298 = zext i8 %fuzz.cfg.bytehorner.idiom.b.byte.trunc297 to i32
  %fuzz.cfg.bytehorner.idiom.term.mul299 = mul i32 %fuzz.cfg.bytehorner.idiom.a.byte.zext295, 4
  %fuzz.cfg.bytehorner.idiom.term.bias300 = add i32 %fuzz.cfg.bytehorner.idiom.term.mul299, %fuzz.cfg.bytehorner.idiom.b.byte.zext298
  %fuzz.cfg.bytehorner.idiom.horner.mul301 = mul i32 %fuzz.cfg.bytehorner.idiom.horner.add291, 19
  %fuzz.cfg.bytehorner.idiom.horner.add302 = add i32 %fuzz.cfg.bytehorner.idiom.horner.mul301, %fuzz.cfg.bytehorner.idiom.term.bias300
  %fuzz.cfg.bytehorner.idiom.byte.mix303 = xor i32 %fuzz.cfg.bytehorner.idiom.horner.add302, %fuzz.cfg.bytehorner.idiom.term.bias300
  %fuzz.cfg.bytehorner.idiom.a.byte.shr304 = lshr i32 %fuzz.cfg.bytehorner.idiom.acc.xor, 16
  %fuzz.cfg.bytehorner.idiom.a.byte.trunc305 = trunc i32 %fuzz.cfg.bytehorner.idiom.a.byte.shr304 to i8
  %fuzz.cfg.bytehorner.idiom.a.byte.zext306 = zext i8 %fuzz.cfg.bytehorner.idiom.a.byte.trunc305 to i32
  %fuzz.cfg.bytehorner.idiom.b.byte.shr307 = lshr i32 %idx, 8
  %fuzz.cfg.bytehorner.idiom.b.byte.trunc308 = trunc i32 %fuzz.cfg.bytehorner.idiom.b.byte.shr307 to i8
  %fuzz.cfg.bytehorner.idiom.b.byte.zext309 = zext i8 %fuzz.cfg.bytehorner.idiom.b.byte.trunc308 to i32
  %fuzz.cfg.bytehorner.idiom.term.add310 = add i32 %fuzz.cfg.bytehorner.idiom.a.byte.zext306, %fuzz.cfg.bytehorner.idiom.b.byte.zext309
  %fuzz.cfg.bytehorner.idiom.horner.mul311 = mul i32 %fuzz.cfg.bytehorner.idiom.horner.add302, 21
  %fuzz.cfg.bytehorner.idiom.horner.add312 = add i32 %fuzz.cfg.bytehorner.idiom.horner.mul311, %fuzz.cfg.bytehorner.idiom.term.add310
  %fuzz.cfg.bytehorner.idiom.byte.mix313 = xor i32 %fuzz.cfg.bytehorner.idiom.horner.add312, %fuzz.cfg.bytehorner.idiom.term.add310
  %fuzz.cfg.bytehorner.idiom.a.byte.shr314 = lshr i32 %fuzz.cfg.bytehorner.idiom.acc.xor, 24
  %fuzz.cfg.bytehorner.idiom.a.byte.trunc315 = trunc i32 %fuzz.cfg.bytehorner.idiom.a.byte.shr314 to i8
  %fuzz.cfg.bytehorner.idiom.a.byte.zext316 = zext i8 %fuzz.cfg.bytehorner.idiom.a.byte.trunc315 to i32
  %fuzz.cfg.bytehorner.idiom.b.byte.trunc317 = trunc i32 %idx to i8
  %fuzz.cfg.bytehorner.idiom.b.byte.zext318 = zext i8 %fuzz.cfg.bytehorner.idiom.b.byte.trunc317 to i32
  %fuzz.cfg.bytehorner.idiom.term.cmp319 = icmp ult i32 %fuzz.cfg.bytehorner.idiom.a.byte.zext316, %fuzz.cfg.bytehorner.idiom.b.byte.zext318
  %fuzz.cfg.bytehorner.idiom.term.max320 = select i1 %fuzz.cfg.bytehorner.idiom.term.cmp319, i32 %fuzz.cfg.bytehorner.idiom.b.byte.zext318, i32 %fuzz.cfg.bytehorner.idiom.a.byte.zext316
  %fuzz.cfg.bytehorner.idiom.horner.mul321 = mul i32 %fuzz.cfg.bytehorner.idiom.horner.add312, 23
  %fuzz.cfg.bytehorner.idiom.horner.add322 = add i32 %fuzz.cfg.bytehorner.idiom.horner.mul321, %fuzz.cfg.bytehorner.idiom.term.max320
  %fuzz.cfg.bytehorner.idiom.byte.mix323 = xor i32 %fuzz.cfg.bytehorner.idiom.horner.add322, %fuzz.cfg.bytehorner.idiom.term.max320
  %fuzz.cfg.bytehorner.idiom.pack.mask324 = and i32 %fuzz.cfg.bytehorner.idiom.byte.mix292, 255
  %fuzz.cfg.bytehorner.idiom.pack.or325 = or i32 0, %fuzz.cfg.bytehorner.idiom.pack.mask324
  %fuzz.cfg.bytehorner.idiom.pack.mask326 = and i32 %fuzz.cfg.bytehorner.idiom.byte.mix303, 255
  %fuzz.cfg.bytehorner.idiom.pack.shift327 = shl i32 %fuzz.cfg.bytehorner.idiom.pack.mask326, 8
  %fuzz.cfg.bytehorner.idiom.pack.or328 = or i32 %fuzz.cfg.bytehorner.idiom.pack.or325, %fuzz.cfg.bytehorner.idiom.pack.shift327
  %fuzz.cfg.bytehorner.idiom.pack.mask329 = and i32 %fuzz.cfg.bytehorner.idiom.byte.mix313, 255
  %fuzz.cfg.bytehorner.idiom.pack.shift330 = shl i32 %fuzz.cfg.bytehorner.idiom.pack.mask329, 16
  %fuzz.cfg.bytehorner.idiom.pack.or331 = or i32 %fuzz.cfg.bytehorner.idiom.pack.or328, %fuzz.cfg.bytehorner.idiom.pack.shift330
  %fuzz.cfg.bytehorner.idiom.pack.mask332 = and i32 %fuzz.cfg.bytehorner.idiom.byte.mix323, 255
  %fuzz.cfg.bytehorner.idiom.pack.shift333 = shl i32 %fuzz.cfg.bytehorner.idiom.pack.mask332, 24
  %fuzz.cfg.bytehorner.idiom.pack.or334 = or i32 %fuzz.cfg.bytehorner.idiom.pack.or331, %fuzz.cfg.bytehorner.idiom.pack.shift333
  %fuzz.cfg.bytehorner.idiom.pack.lo = and i32 %fuzz.cfg.bytehorner.idiom.pack.or334, 16711935
  %fuzz.cfg.bytehorner.idiom.acc.hi = and i32 %fuzz.cfg.bytehorner.idiom.horner.add322, -16711936
  %fuzz.cfg.bytehorner.idiom.merge = or i32 %fuzz.cfg.bytehorner.idiom.pack.lo, %fuzz.cfg.bytehorner.idiom.acc.hi
  %fuzz.loop.break.inner = icmp ule i32 %fuzz.cfg.bytehorner.idiom.merge, 255
  br label %fuzz.nested.loop.exit

fuzz.nested.loop.exit:                            ; preds = %fuzz.nested.loop.body, %fuzz.loop.nest.body
  %fuzz.loop.exit.value.inner = phi i32 [ %fuzz.loop.nest.acc, %fuzz.loop.nest.body ], [ %fuzz.cfg.bytehorner.idiom.merge, %fuzz.nested.loop.body ]
  %fuzz.loop.nest.acc.xor = xor i32 %fuzz.loop.exit.value.inner, %fuzz.loop.nest.iv
  %fuzz.loop.nest.next = add i32 %fuzz.loop.nest.iv, 1
  br label %fuzz.loop.nest.header

fuzz.loop.nest.exit:                              ; preds = %fuzz.loop.nest.header
  %fuzz.ternary.idiom.not.a1 = xor i32 %fuzz.loop.nest.acc, -1
  %fuzz.ternary.idiom.not.b2 = xor i32 %fuzz.sdiv.den, -1
  %fuzz.ternary.idiom.not.c3 = xor i32 -1, -1
  %fuzz.ternary.idiom.blend.mask = xor i32 %fuzz.loop.nest.acc, %fuzz.sdiv.den
  %fuzz.ternary.idiom.blend.left = and i32 -1, %fuzz.ternary.idiom.blend.mask
  %fuzz.ternary.idiom.blend.not = xor i32 %fuzz.ternary.idiom.blend.mask, -1
  %fuzz.ternary.idiom.blend.right = and i32 %fuzz.sdiv.den, %fuzz.ternary.idiom.blend.not
  %fuzz.ternary.idiom.blend = or i32 %fuzz.ternary.idiom.blend.left, %fuzz.ternary.idiom.blend.right
  %fuzz.ovmaskpack.idiom.x.byte.trunc = trunc i32 %fuzz.ternary.idiom.blend to i8
  %fuzz.ovmaskpack.idiom.x.byte.zext = zext i8 %fuzz.ovmaskpack.idiom.x.byte.trunc to i32
  %fuzz.ovmaskpack.idiom.y.byte.shr = lshr i32 255, 8
  %fuzz.ovmaskpack.idiom.y.byte.trunc = trunc i32 %fuzz.ovmaskpack.idiom.y.byte.shr to i8
  %fuzz.ovmaskpack.idiom.y.byte.zext = zext i8 %fuzz.ovmaskpack.idiom.y.byte.trunc to i32
  %fuzz.ovmaskpack.idiom.x.wide = shl i32 %fuzz.ovmaskpack.idiom.x.byte.zext, 5
  %fuzz.ovmaskpack.idiom.y.wide = shl i32 %fuzz.ovmaskpack.idiom.y.byte.zext, 21
  %fuzz.ovmaskpack.idiom.ov.call = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 %fuzz.ovmaskpack.idiom.x.wide, i32 %fuzz.ovmaskpack.idiom.y.wide)
  %fuzz.ovmaskpack.idiom.ov.value = extractvalue { i32, i1 } %fuzz.ovmaskpack.idiom.ov.call, 0
  %fuzz.ovmaskpack.idiom.ov.bit = extractvalue { i32, i1 } %fuzz.ovmaskpack.idiom.ov.call, 1
  %fuzz.ovmaskpack.idiom.ov.i32 = zext i1 %fuzz.ovmaskpack.idiom.ov.bit to i32
  %fuzz.ovmaskpack.idiom.mask.shl = shl i32 %fuzz.ovmaskpack.idiom.ov.i32, 0
  %fuzz.ovmaskpack.idiom.mask = or i32 0, %fuzz.ovmaskpack.idiom.mask.shl
  %fuzz.ovmaskpack.idiom.result.byte.trunc = trunc i32 %fuzz.ovmaskpack.idiom.ov.value to i8
  %fuzz.ovmaskpack.idiom.result.byte.zext = zext i8 %fuzz.ovmaskpack.idiom.result.byte.trunc to i32
  %fuzz.ovmaskpack.idiom.fallback.byte.shr = lshr i32 255, 24
  %fuzz.ovmaskpack.idiom.fallback.byte.trunc = trunc i32 %fuzz.ovmaskpack.idiom.fallback.byte.shr to i8
  %fuzz.ovmaskpack.idiom.fallback.byte.zext = zext i8 %fuzz.ovmaskpack.idiom.fallback.byte.trunc to i32
  %fuzz.ovmaskpack.idiom.lane.select = select i1 %fuzz.ovmaskpack.idiom.ov.bit, i32 %fuzz.ovmaskpack.idiom.fallback.byte.zext, i32 %fuzz.ovmaskpack.idiom.result.byte.zext
  %fuzz.ovmaskpack.idiom.lane.byte = and i32 %fuzz.ovmaskpack.idiom.lane.select, 255
  %fuzz.ovmaskpack.idiom.fold.add = add i32 0, %fuzz.ovmaskpack.idiom.ov.value
  %fuzz.ovmaskpack.idiom.fold.ov = shl i32 %fuzz.ovmaskpack.idiom.ov.i32, 0
  %fuzz.ovmaskpack.idiom.fold = xor i32 %fuzz.ovmaskpack.idiom.fold.add, %fuzz.ovmaskpack.idiom.fold.ov
  %fuzz.ovmaskpack.idiom.x.byte.shr = lshr i32 255, 8
  %fuzz.ovmaskpack.idiom.x.byte.trunc1 = trunc i32 %fuzz.ovmaskpack.idiom.x.byte.shr to i8
  %fuzz.ovmaskpack.idiom.x.byte.zext2 = zext i8 %fuzz.ovmaskpack.idiom.x.byte.trunc1 to i32
  %fuzz.ovmaskpack.idiom.y.byte.shr3 = lshr i32 %fuzz.ternary.idiom.blend, 16
  %fuzz.ovmaskpack.idiom.y.byte.trunc4 = trunc i32 %fuzz.ovmaskpack.idiom.y.byte.shr3 to i8
  %fuzz.ovmaskpack.idiom.y.byte.zext5 = zext i8 %fuzz.ovmaskpack.idiom.y.byte.trunc4 to i32
  %fuzz.ovmaskpack.idiom.x.wide6 = shl i32 %fuzz.ovmaskpack.idiom.x.byte.zext2, 10
  %fuzz.ovmaskpack.idiom.y.wide7 = shl i32 %fuzz.ovmaskpack.idiom.y.byte.zext5, 28
  %fuzz.ovmaskpack.idiom.ov.call8 = call { i32, i1 } @llvm.ssub.with.overflow.i32(i32 %fuzz.ovmaskpack.idiom.x.wide6, i32 %fuzz.ovmaskpack.idiom.y.wide7)
  %fuzz.ovmaskpack.idiom.ov.value9 = extractvalue { i32, i1 } %fuzz.ovmaskpack.idiom.ov.call8, 0
  %fuzz.ovmaskpack.idiom.ov.bit10 = extractvalue { i32, i1 } %fuzz.ovmaskpack.idiom.ov.call8, 1
  %fuzz.ovmaskpack.idiom.ov.i3211 = zext i1 %fuzz.ovmaskpack.idiom.ov.bit10 to i32
  %fuzz.ovmaskpack.idiom.mask.shl12 = shl i32 %fuzz.ovmaskpack.idiom.ov.i3211, 1
  %fuzz.ovmaskpack.idiom.mask13 = or i32 %fuzz.ovmaskpack.idiom.mask, %fuzz.ovmaskpack.idiom.mask.shl12
  %fuzz.ovmaskpack.idiom.result.byte.shr = lshr i32 %fuzz.ovmaskpack.idiom.ov.value9, 8
  %fuzz.ovmaskpack.idiom.result.byte.trunc14 = trunc i32 %fuzz.ovmaskpack.idiom.result.byte.shr to i8
  %fuzz.ovmaskpack.idiom.result.byte.zext15 = zext i8 %fuzz.ovmaskpack.idiom.result.byte.trunc14 to i32
  %fuzz.ovmaskpack.idiom.fallback.byte.shr16 = lshr i32 %fuzz.ternary.idiom.blend, 16
  %fuzz.ovmaskpack.idiom.fallback.byte.trunc17 = trunc i32 %fuzz.ovmaskpack.idiom.fallback.byte.shr16 to i8
  %fuzz.ovmaskpack.idiom.fallback.byte.zext18 = zext i8 %fuzz.ovmaskpack.idiom.fallback.byte.trunc17 to i32
  %fuzz.ovmaskpack.idiom.lane.select19 = select i1 %fuzz.ovmaskpack.idiom.ov.bit10, i32 %fuzz.ovmaskpack.idiom.fallback.byte.zext18, i32 %fuzz.ovmaskpack.idiom.result.byte.zext15
  %fuzz.ovmaskpack.idiom.lane.byte20 = and i32 %fuzz.ovmaskpack.idiom.lane.select19, 255
  %fuzz.ovmaskpack.idiom.fold.add21 = add i32 %fuzz.ovmaskpack.idiom.fold, %fuzz.ovmaskpack.idiom.ov.value9
  %fuzz.ovmaskpack.idiom.fold.ov22 = shl i32 %fuzz.ovmaskpack.idiom.ov.i3211, 7
  %fuzz.ovmaskpack.idiom.fold23 = xor i32 %fuzz.ovmaskpack.idiom.fold.add21, %fuzz.ovmaskpack.idiom.fold.ov22
  %fuzz.ovmaskpack.idiom.x.byte.shr24 = lshr i32 %fuzz.ternary.idiom.blend, 16
  %fuzz.ovmaskpack.idiom.x.byte.trunc25 = trunc i32 %fuzz.ovmaskpack.idiom.x.byte.shr24 to i8
  %fuzz.ovmaskpack.idiom.x.byte.zext26 = zext i8 %fuzz.ovmaskpack.idiom.x.byte.trunc25 to i32
  %fuzz.ovmaskpack.idiom.y.byte.shr27 = lshr i32 255, 24
  %fuzz.ovmaskpack.idiom.y.byte.trunc28 = trunc i32 %fuzz.ovmaskpack.idiom.y.byte.shr27 to i8
  %fuzz.ovmaskpack.idiom.y.byte.zext29 = zext i8 %fuzz.ovmaskpack.idiom.y.byte.trunc28 to i32
  %fuzz.ovmaskpack.idiom.x.wide30 = shl i32 %fuzz.ovmaskpack.idiom.x.byte.zext26, 15
  %fuzz.ovmaskpack.idiom.y.wide31 = shl i32 %fuzz.ovmaskpack.idiom.y.byte.zext29, 3
  %fuzz.ovmaskpack.idiom.ov.call32 = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 %fuzz.ovmaskpack.idiom.x.wide30, i32 %fuzz.ovmaskpack.idiom.y.wide31)
  %fuzz.ovmaskpack.idiom.ov.value33 = extractvalue { i32, i1 } %fuzz.ovmaskpack.idiom.ov.call32, 0
  %fuzz.ovmaskpack.idiom.ov.bit34 = extractvalue { i32, i1 } %fuzz.ovmaskpack.idiom.ov.call32, 1
  %fuzz.ovmaskpack.idiom.ov.i3235 = zext i1 %fuzz.ovmaskpack.idiom.ov.bit34 to i32
  %fuzz.ovmaskpack.idiom.mask.shl36 = shl i32 %fuzz.ovmaskpack.idiom.ov.i3235, 2
  %fuzz.ovmaskpack.idiom.mask37 = or i32 %fuzz.ovmaskpack.idiom.mask13, %fuzz.ovmaskpack.idiom.mask.shl36
  %fuzz.ovmaskpack.idiom.result.byte.shr38 = lshr i32 %fuzz.ovmaskpack.idiom.ov.value33, 16
  %fuzz.ovmaskpack.idiom.result.byte.trunc39 = trunc i32 %fuzz.ovmaskpack.idiom.result.byte.shr38 to i8
  %fuzz.ovmaskpack.idiom.result.byte.zext40 = zext i8 %fuzz.ovmaskpack.idiom.result.byte.trunc39 to i32
  %fuzz.ovmaskpack.idiom.fallback.byte.shr41 = lshr i32 255, 8
  %fuzz.ovmaskpack.idiom.fallback.byte.trunc42 = trunc i32 %fuzz.ovmaskpack.idiom.fallback.byte.shr41 to i8
  %fuzz.ovmaskpack.idiom.fallback.byte.zext43 = zext i8 %fuzz.ovmaskpack.idiom.fallback.byte.trunc42 to i32
  %fuzz.ovmaskpack.idiom.lane.select44 = select i1 %fuzz.ovmaskpack.idiom.ov.bit34, i32 %fuzz.ovmaskpack.idiom.fallback.byte.zext43, i32 %fuzz.ovmaskpack.idiom.result.byte.zext40
  %fuzz.ovmaskpack.idiom.lane.byte45 = and i32 %fuzz.ovmaskpack.idiom.lane.select44, 255
  %fuzz.ovmaskpack.idiom.fold.add46 = add i32 %fuzz.ovmaskpack.idiom.fold23, %fuzz.ovmaskpack.idiom.ov.value33
  %fuzz.ovmaskpack.idiom.fold.ov47 = shl i32 %fuzz.ovmaskpack.idiom.ov.i3235, 14
  %fuzz.ovmaskpack.idiom.fold48 = xor i32 %fuzz.ovmaskpack.idiom.fold.add46, %fuzz.ovmaskpack.idiom.fold.ov47
  %fuzz.ovmaskpack.idiom.x.byte.shr49 = lshr i32 255, 24
  %fuzz.ovmaskpack.idiom.x.byte.trunc50 = trunc i32 %fuzz.ovmaskpack.idiom.x.byte.shr49 to i8
  %fuzz.ovmaskpack.idiom.x.byte.zext51 = zext i8 %fuzz.ovmaskpack.idiom.x.byte.trunc50 to i32
  %fuzz.ovmaskpack.idiom.y.byte.trunc52 = trunc i32 %fuzz.ternary.idiom.blend to i8
  %fuzz.ovmaskpack.idiom.y.byte.zext53 = zext i8 %fuzz.ovmaskpack.idiom.y.byte.trunc52 to i32
  %fuzz.ovmaskpack.idiom.x.wide54 = shl i32 %fuzz.ovmaskpack.idiom.x.byte.zext51, 20
  %fuzz.ovmaskpack.idiom.y.wide55 = shl i32 %fuzz.ovmaskpack.idiom.y.byte.zext53, 10
  %fuzz.ovmaskpack.idiom.ov.call56 = call { i32, i1 } @llvm.usub.with.overflow.i32(i32 %fuzz.ovmaskpack.idiom.x.wide54, i32 %fuzz.ovmaskpack.idiom.y.wide55)
  %fuzz.ovmaskpack.idiom.ov.value57 = extractvalue { i32, i1 } %fuzz.ovmaskpack.idiom.ov.call56, 0
  %fuzz.ovmaskpack.idiom.ov.bit58 = extractvalue { i32, i1 } %fuzz.ovmaskpack.idiom.ov.call56, 1
  %fuzz.ovmaskpack.idiom.ov.i3259 = zext i1 %fuzz.ovmaskpack.idiom.ov.bit58 to i32
  %fuzz.ovmaskpack.idiom.mask.shl60 = shl i32 %fuzz.ovmaskpack.idiom.ov.i3259, 3
  %fuzz.ovmaskpack.idiom.mask61 = or i32 %fuzz.ovmaskpack.idiom.mask37, %fuzz.ovmaskpack.idiom.mask.shl60
  %fuzz.ovmaskpack.idiom.result.byte.shr62 = lshr i32 %fuzz.ovmaskpack.idiom.ov.value57, 24
  %fuzz.ovmaskpack.idiom.result.byte.trunc63 = trunc i32 %fuzz.ovmaskpack.idiom.result.byte.shr62 to i8
  %fuzz.ovmaskpack.idiom.result.byte.zext64 = zext i8 %fuzz.ovmaskpack.idiom.result.byte.trunc63 to i32
  %fuzz.ovmaskpack.idiom.fallback.byte.trunc65 = trunc i32 %fuzz.ternary.idiom.blend to i8
  %fuzz.ovmaskpack.idiom.fallback.byte.zext66 = zext i8 %fuzz.ovmaskpack.idiom.fallback.byte.trunc65 to i32
  %fuzz.ovmaskpack.idiom.lane.select67 = select i1 %fuzz.ovmaskpack.idiom.ov.bit58, i32 %fuzz.ovmaskpack.idiom.fallback.byte.zext66, i32 %fuzz.ovmaskpack.idiom.result.byte.zext64
  %fuzz.ovmaskpack.idiom.lane.byte68 = and i32 %fuzz.ovmaskpack.idiom.lane.select67, 255
  %fuzz.ovmaskpack.idiom.fold.add69 = add i32 %fuzz.ovmaskpack.idiom.fold48, %fuzz.ovmaskpack.idiom.ov.value57
  %fuzz.ovmaskpack.idiom.fold.ov70 = shl i32 %fuzz.ovmaskpack.idiom.ov.i3259, 21
  %fuzz.ovmaskpack.idiom.fold71 = xor i32 %fuzz.ovmaskpack.idiom.fold.add69, %fuzz.ovmaskpack.idiom.fold.ov70
  %fuzz.ovmaskpack.idiom.pack.mask = and i32 %fuzz.ovmaskpack.idiom.lane.byte, 255
  %fuzz.ovmaskpack.idiom.pack.add = add i32 0, %fuzz.ovmaskpack.idiom.pack.mask
  %fuzz.ovmaskpack.idiom.pack.mask72 = and i32 %fuzz.ovmaskpack.idiom.lane.byte20, 255
  %fuzz.ovmaskpack.idiom.pack.shift = shl i32 %fuzz.ovmaskpack.idiom.pack.mask72, 8
  %fuzz.ovmaskpack.idiom.pack.add73 = add i32 %fuzz.ovmaskpack.idiom.pack.add, %fuzz.ovmaskpack.idiom.pack.shift
  %fuzz.ovmaskpack.idiom.pack.mask74 = and i32 %fuzz.ovmaskpack.idiom.lane.byte45, 255
  %fuzz.ovmaskpack.idiom.pack.shift75 = shl i32 %fuzz.ovmaskpack.idiom.pack.mask74, 16
  %fuzz.ovmaskpack.idiom.pack.add76 = add i32 %fuzz.ovmaskpack.idiom.pack.add73, %fuzz.ovmaskpack.idiom.pack.shift75
  %fuzz.ovmaskpack.idiom.pack.mask77 = and i32 %fuzz.ovmaskpack.idiom.lane.byte68, 255
  %fuzz.ovmaskpack.idiom.pack.shift78 = shl i32 %fuzz.ovmaskpack.idiom.pack.mask77, 24
  %fuzz.ovmaskpack.idiom.pack.add79 = add i32 %fuzz.ovmaskpack.idiom.pack.add76, %fuzz.ovmaskpack.idiom.pack.shift78
  %fuzz.ovmaskpack.idiom.fold.xor = xor i32 %fuzz.ovmaskpack.idiom.pack.add79, %fuzz.ovmaskpack.idiom.fold71
  store i32 %fuzz.ovmaskpack.idiom.fold.xor, ptr addrspace(1) %out.ptr, align 4
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef i32 @llvm.amdgcn.workgroup.id.x() #1

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef range(i32 0, 1024) i32 @llvm.amdgcn.workitem.id.x() #1

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.ctpop.i32(i32) #2

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.fshr.i32(i32, i32, i32) #2

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.smax.i32(i32, i32) #2

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare { i32, i1 } @llvm.smul.with.overflow.i32(i32, i32) #2

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare { i32, i1 } @llvm.ssub.with.overflow.i32(i32, i32) #2

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare { i32, i1 } @llvm.usub.with.overflow.i32(i32, i32) #2

; uselistorder directives
uselistorder ptr @llvm.ctpop.i32, { 3, 2, 1, 0 }
uselistorder ptr @llvm.smul.with.overflow.i32, { 1, 0 }

attributes #0 = { convergent nounwind "amdgpu-flat-work-group-size"="1,256" "target-cpu"="gfx950" "uniform-work-group-size" }
attributes #1 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #2 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
