; RUN-INPUTS: 0x0,0x1
; RUN-LLVM-BUILD: build/llvm-fuzzer
source_filename = "known-miscompiles/m060-packunpack-bytedot-dot4/reduced.ll"
target datalayout = "e-m:e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128:128:48-p9:192:256:256:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9"
target triple = "amdgcn-amd-amdhsa"

; Function Attrs: convergent nounwind
define amdgpu_kernel void @fuzz_kernel(ptr addrspace(1) %in, ptr addrspace(1) %out) #0 {
entry:
  %wg = call i32 @llvm.amdgcn.workgroup.id.x()
  %wi = call i32 @llvm.amdgcn.workitem.id.x()
  %block.base = mul i32 %wg, 256
  %idx = add i32 %block.base, %wi
  %idx64 = zext i32 %idx to i64
  %in.ptr = getelementptr i32, ptr addrspace(1) %in, i64 %idx64
  %v = load i32, ptr addrspace(1) %in.ptr, align 4
  %salt = mul i32 %idx, -1640531527
  %mix = xor i32 %v, %salt
  %out.ptr = getelementptr i32, ptr addrspace(1) %out, i64 %idx64
  %fuzz.halfdot.idiom.a.half.trunc = trunc i32 %mix to i16
  %fuzz.halfdot.idiom.a.half.zext = zext i16 %fuzz.halfdot.idiom.a.half.trunc to i32
  %fuzz.halfdot.idiom.b.half.shr = lshr i32 %mix, 16
  %fuzz.halfdot.idiom.b.half.trunc = trunc i32 %fuzz.halfdot.idiom.b.half.shr to i16
  %fuzz.halfdot.idiom.b.half.zext = zext i16 %fuzz.halfdot.idiom.b.half.trunc to i32
  %fuzz.halfdot.idiom.a.wide.u = zext i32 %fuzz.halfdot.idiom.a.half.zext to i64
  %fuzz.halfdot.idiom.b.wide.u = zext i32 %fuzz.halfdot.idiom.b.half.zext to i64
  %fuzz.halfdot.idiom.mul = mul i64 %fuzz.halfdot.idiom.a.wide.u, %fuzz.halfdot.idiom.b.wide.u
  %fuzz.halfdot.idiom.acc.sub = sub i64 27691, %fuzz.halfdot.idiom.mul
  %fuzz.halfdot.idiom.mul.i32 = trunc i64 %fuzz.halfdot.idiom.mul to i32
  %fuzz.halfdot.idiom.mul.byte = lshr i32 %fuzz.halfdot.idiom.mul.i32, 0
  %fuzz.halfdot.idiom.a.half.shr = lshr i32 %mix, 16
  %fuzz.halfdot.idiom.a.half.trunc1 = trunc i32 %fuzz.halfdot.idiom.a.half.shr to i16
  %fuzz.halfdot.idiom.a.half.sext = sext i16 %fuzz.halfdot.idiom.a.half.trunc1 to i32
  %fuzz.halfdot.idiom.b.half.trunc2 = trunc i32 %mix to i16
  %fuzz.halfdot.idiom.b.half.sext = sext i16 %fuzz.halfdot.idiom.b.half.trunc2 to i32
  %fuzz.halfdot.idiom.a.wide.s = sext i32 %fuzz.halfdot.idiom.a.half.sext to i64
  %fuzz.halfdot.idiom.b.wide.s = sext i32 %fuzz.halfdot.idiom.b.half.sext to i64
  %fuzz.halfdot.idiom.mul3 = mul i64 %fuzz.halfdot.idiom.a.wide.s, %fuzz.halfdot.idiom.b.wide.s
  %fuzz.halfdot.idiom.acc.sub4 = sub i64 %fuzz.halfdot.idiom.acc.sub, %fuzz.halfdot.idiom.mul3
  %fuzz.halfdot.idiom.mul.i325 = trunc i64 %fuzz.halfdot.idiom.mul3 to i32
  %fuzz.halfdot.idiom.mul.byte6 = lshr i32 %fuzz.halfdot.idiom.mul.i325, 15
  %fuzz.halfdot.idiom.a.half.trunc7 = trunc i32 %mix to i16
  %fuzz.halfdot.idiom.a.half.zext8 = zext i16 %fuzz.halfdot.idiom.a.half.trunc7 to i32
  %fuzz.halfdot.idiom.b.half.shr9 = lshr i32 %mix, 16
  %fuzz.halfdot.idiom.b.half.trunc10 = trunc i32 %fuzz.halfdot.idiom.b.half.shr9 to i16
  %fuzz.halfdot.idiom.b.half.zext11 = zext i16 %fuzz.halfdot.idiom.b.half.trunc10 to i32
  %fuzz.halfdot.idiom.a.wide.u12 = zext i32 %fuzz.halfdot.idiom.a.half.zext8 to i64
  %fuzz.halfdot.idiom.b.wide.u13 = zext i32 %fuzz.halfdot.idiom.b.half.zext11 to i64
  %fuzz.halfdot.idiom.mul14 = mul i64 %fuzz.halfdot.idiom.a.wide.u12, %fuzz.halfdot.idiom.b.wide.u13
  %fuzz.halfdot.idiom.mul.lo = and i64 %fuzz.halfdot.idiom.mul14, 65535
  %fuzz.halfdot.idiom.acc.add.lo = add i64 %fuzz.halfdot.idiom.acc.sub4, %fuzz.halfdot.idiom.mul.lo
  %fuzz.halfdot.idiom.mul.i3215 = trunc i64 %fuzz.halfdot.idiom.mul14 to i32
  %fuzz.halfdot.idiom.mul.byte16 = lshr i32 %fuzz.halfdot.idiom.mul.i3215, 0
  %fuzz.halfdot.idiom.a.half.shr17 = lshr i32 %mix, 16
  %fuzz.halfdot.idiom.a.half.trunc18 = trunc i32 %fuzz.halfdot.idiom.a.half.shr17 to i16
  %fuzz.halfdot.idiom.a.half.zext19 = zext i16 %fuzz.halfdot.idiom.a.half.trunc18 to i32
  %fuzz.halfdot.idiom.b.half.trunc20 = trunc i32 %mix to i16
  %fuzz.halfdot.idiom.b.half.zext21 = zext i16 %fuzz.halfdot.idiom.b.half.trunc20 to i32
  %fuzz.halfdot.idiom.a.wide.u22 = zext i32 %fuzz.halfdot.idiom.a.half.zext19 to i64
  %fuzz.halfdot.idiom.b.wide.u23 = zext i32 %fuzz.halfdot.idiom.b.half.zext21 to i64
  %fuzz.halfdot.idiom.mul24 = mul i64 %fuzz.halfdot.idiom.a.wide.u22, %fuzz.halfdot.idiom.b.wide.u23
  %fuzz.halfdot.idiom.acc.sub25 = sub i64 %fuzz.halfdot.idiom.acc.add.lo, %fuzz.halfdot.idiom.mul24
  %fuzz.halfdot.idiom.mul.i3226 = trunc i64 %fuzz.halfdot.idiom.mul24 to i32
  %fuzz.halfdot.idiom.mul.byte27 = lshr i32 %fuzz.halfdot.idiom.mul.i3226, 8
  %fuzz.halfdot.idiom.lo = trunc i64 %fuzz.halfdot.idiom.acc.sub25 to i32
  %fuzz.halfdot.idiom.hi.shr = lshr i64 %fuzz.halfdot.idiom.acc.sub25, 32
  %fuzz.halfdot.idiom.pack.mask = and i32 %fuzz.halfdot.idiom.mul.byte, 255
  %fuzz.halfdot.idiom.pack.add = add i32 0, %fuzz.halfdot.idiom.pack.mask
  %fuzz.halfdot.idiom.pack.mask28 = and i32 %fuzz.halfdot.idiom.mul.byte6, 255
  %fuzz.halfdot.idiom.pack.shift = shl i32 %fuzz.halfdot.idiom.pack.mask28, 8
  %fuzz.halfdot.idiom.pack.add29 = add i32 %fuzz.halfdot.idiom.pack.add, %fuzz.halfdot.idiom.pack.shift
  %fuzz.halfdot.idiom.pack.mask30 = and i32 %fuzz.halfdot.idiom.mul.byte16, 255
  %fuzz.halfdot.idiom.pack.shift31 = shl i32 %fuzz.halfdot.idiom.pack.mask30, 16
  %fuzz.halfdot.idiom.pack.add32 = add i32 %fuzz.halfdot.idiom.pack.add29, %fuzz.halfdot.idiom.pack.shift31
  %fuzz.halfdot.idiom.pack.mask33 = and i32 %fuzz.halfdot.idiom.mul.byte27, 255
  %fuzz.halfdot.idiom.pack.shift34 = shl i32 %fuzz.halfdot.idiom.pack.mask33, 24
  %fuzz.halfdot.idiom.pack.add35 = add i32 %fuzz.halfdot.idiom.pack.add32, %fuzz.halfdot.idiom.pack.shift34
  %fuzz.halfdot.idiom.pack.sub = sub i32 %fuzz.halfdot.idiom.lo, %fuzz.halfdot.idiom.pack.add35
  %fuzz.loop.cond = icmp ult i32 0, 3
  %fuzz.loop.acc.mix = add i32 %fuzz.halfdot.idiom.pack.sub, %fuzz.halfdot.idiom.b.half.shr9
  %fuzz.ashr = ashr i32 %fuzz.loop.acc.mix, 27
  %fuzz.bitrunmask.idiom.count.a.add = add i32 %fuzz.ashr, 5
  %fuzz.bitrunmask.idiom.count.a = and i32 %fuzz.bitrunmask.idiom.count.a.add, 31
  %fuzz.bitrunmask.idiom.count.b.xor = xor i32 2, 14
  %fuzz.bitrunmask.idiom.count.b = and i32 %fuzz.bitrunmask.idiom.count.b.xor, 31
  %fuzz.bitrunmask.idiom.run.a.shl = shl i32 1, %fuzz.bitrunmask.idiom.count.a
  %fuzz.bitrunmask.idiom.run.a = sub i32 %fuzz.bitrunmask.idiom.run.a.shl, 1
  %fuzz.bitrunmask.idiom.run.b.shl = shl i32 1, %fuzz.bitrunmask.idiom.count.b
  %fuzz.bitrunmask.idiom.run.b = sub i32 %fuzz.bitrunmask.idiom.run.b.shl, 1
  %fuzz.bitrunmask.idiom.inv.a.raw = sub i32 32, %fuzz.bitrunmask.idiom.count.a
  %fuzz.bitrunmask.idiom.inv.a = and i32 %fuzz.bitrunmask.idiom.inv.a.raw, 31
  %fuzz.bitrunmask.idiom.left = shl i32 %fuzz.ashr, %fuzz.bitrunmask.idiom.count.b
  %fuzz.bitrunmask.idiom.right = lshr i32 2, %fuzz.bitrunmask.idiom.inv.a
  %fuzz.bitrunmask.idiom.window = or i32 %fuzz.bitrunmask.idiom.left, %fuzz.bitrunmask.idiom.right
  %fuzz.bitrunmask.idiom.masked.a = and i32 %fuzz.bitrunmask.idiom.window, %fuzz.bitrunmask.idiom.run.a
  %fuzz.bitrunmask.idiom.window.xor = xor i32 %fuzz.bitrunmask.idiom.window, 2
  %fuzz.bitrunmask.idiom.masked.b = and i32 %fuzz.bitrunmask.idiom.window.xor, %fuzz.bitrunmask.idiom.run.b
  %fuzz.bitrunmask.idiom.lt = icmp ult i32 %fuzz.bitrunmask.idiom.count.a, %fuzz.bitrunmask.idiom.count.b
  %fuzz.bitrunmask.idiom.select = select i1 %fuzz.bitrunmask.idiom.lt, i32 %fuzz.bitrunmask.idiom.masked.a, i32 %fuzz.bitrunmask.idiom.masked.b
  %fuzz.bitrunmask.idiom.sub = sub i32 %fuzz.bitrunmask.idiom.window, %fuzz.bitrunmask.idiom.select
  %fuzz.nibbletable.idiom.nib.shr = lshr i32 %fuzz.bitrunmask.idiom.sub, 0
  %fuzz.nibbletable.idiom.nib = and i32 %fuzz.nibbletable.idiom.nib.shr, 15
  %fuzz.nibbletable.idiom.case = icmp eq i32 %fuzz.nibbletable.idiom.nib, 0
  %fuzz.nibbletable.idiom.entry = select i1 %fuzz.nibbletable.idiom.case, i32 152, i32 209
  %fuzz.nibbletable.idiom.case1 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 1
  %fuzz.nibbletable.idiom.entry2 = select i1 %fuzz.nibbletable.idiom.case1, i32 194, i32 %fuzz.nibbletable.idiom.entry
  %fuzz.nibbletable.idiom.case3 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 2
  %fuzz.nibbletable.idiom.entry4 = select i1 %fuzz.nibbletable.idiom.case3, i32 181, i32 %fuzz.nibbletable.idiom.entry2
  %fuzz.nibbletable.idiom.case5 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 3
  %fuzz.nibbletable.idiom.entry6 = select i1 %fuzz.nibbletable.idiom.case5, i32 163, i32 %fuzz.nibbletable.idiom.entry4
  %fuzz.nibbletable.idiom.case7 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 4
  %fuzz.nibbletable.idiom.entry8 = select i1 %fuzz.nibbletable.idiom.case7, i32 185, i32 %fuzz.nibbletable.idiom.entry6
  %fuzz.nibbletable.idiom.case9 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 5
  %fuzz.nibbletable.idiom.entry10 = select i1 %fuzz.nibbletable.idiom.case9, i32 73, i32 %fuzz.nibbletable.idiom.entry8
  %fuzz.nibbletable.idiom.case11 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 6
  %fuzz.nibbletable.idiom.entry12 = select i1 %fuzz.nibbletable.idiom.case11, i32 147, i32 %fuzz.nibbletable.idiom.entry10
  %fuzz.nibbletable.idiom.case13 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 7
  %fuzz.nibbletable.idiom.entry14 = select i1 %fuzz.nibbletable.idiom.case13, i32 137, i32 %fuzz.nibbletable.idiom.entry12
  %fuzz.nibbletable.idiom.case15 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 8
  %fuzz.nibbletable.idiom.entry16 = select i1 %fuzz.nibbletable.idiom.case15, i32 199, i32 %fuzz.nibbletable.idiom.entry14
  %fuzz.nibbletable.idiom.case17 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 9
  %fuzz.nibbletable.idiom.entry18 = select i1 %fuzz.nibbletable.idiom.case17, i32 189, i32 %fuzz.nibbletable.idiom.entry16
  %fuzz.nibbletable.idiom.case19 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 10
  %fuzz.nibbletable.idiom.entry20 = select i1 %fuzz.nibbletable.idiom.case19, i32 219, i32 %fuzz.nibbletable.idiom.entry18
  %fuzz.nibbletable.idiom.case21 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 11
  %fuzz.nibbletable.idiom.entry22 = select i1 %fuzz.nibbletable.idiom.case21, i32 51, i32 %fuzz.nibbletable.idiom.entry20
  %fuzz.nibbletable.idiom.case23 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 12
  %fuzz.nibbletable.idiom.entry24 = select i1 %fuzz.nibbletable.idiom.case23, i32 110, i32 %fuzz.nibbletable.idiom.entry22
  %fuzz.nibbletable.idiom.case25 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 13
  %fuzz.nibbletable.idiom.entry26 = select i1 %fuzz.nibbletable.idiom.case25, i32 151, i32 %fuzz.nibbletable.idiom.entry24
  %fuzz.nibbletable.idiom.case27 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 14
  %fuzz.nibbletable.idiom.entry28 = select i1 %fuzz.nibbletable.idiom.case27, i32 241, i32 %fuzz.nibbletable.idiom.entry26
  %fuzz.nibbletable.idiom.case29 = icmp eq i32 %fuzz.nibbletable.idiom.nib, 15
  %fuzz.nibbletable.idiom.entry30 = select i1 %fuzz.nibbletable.idiom.case29, i32 19, i32 %fuzz.nibbletable.idiom.entry28
  %fuzz.nibbletable.idiom.pop = call i32 @llvm.ctpop.i32(i32 %fuzz.nibbletable.idiom.entry30)
  %fuzz.nibbletable.idiom.pop.shl = shl i32 %fuzz.nibbletable.idiom.pop, 1
  %fuzz.nibbletable.idiom.mix.xor = xor i32 %fuzz.nibbletable.idiom.entry30, %fuzz.nibbletable.idiom.pop.shl
  %fuzz.nibbletable.idiom.fold.add = add i32 179, %fuzz.nibbletable.idiom.mix.xor
  %fuzz.nibbletable.idiom.fold.xor = xor i32 %fuzz.nibbletable.idiom.fold.add, %fuzz.nibbletable.idiom.nib
  %fuzz.nibbletable.idiom.nib.shr31 = lshr i32 %fuzz.bitrunmask.idiom.count.b.xor, 4
  %fuzz.nibbletable.idiom.nib32 = and i32 %fuzz.nibbletable.idiom.nib.shr31, 15
  %fuzz.nibbletable.idiom.case33 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 0
  %fuzz.nibbletable.idiom.entry34 = select i1 %fuzz.nibbletable.idiom.case33, i32 130, i32 5
  %fuzz.nibbletable.idiom.case35 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 1
  %fuzz.nibbletable.idiom.entry36 = select i1 %fuzz.nibbletable.idiom.case35, i32 57, i32 %fuzz.nibbletable.idiom.entry34
  %fuzz.nibbletable.idiom.case37 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 2
  %fuzz.nibbletable.idiom.entry38 = select i1 %fuzz.nibbletable.idiom.case37, i32 9, i32 %fuzz.nibbletable.idiom.entry36
  %fuzz.nibbletable.idiom.case39 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 3
  %fuzz.nibbletable.idiom.entry40 = select i1 %fuzz.nibbletable.idiom.case39, i32 126, i32 %fuzz.nibbletable.idiom.entry38
  %fuzz.nibbletable.idiom.case41 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 4
  %fuzz.nibbletable.idiom.entry42 = select i1 %fuzz.nibbletable.idiom.case41, i32 59, i32 %fuzz.nibbletable.idiom.entry40
  %fuzz.nibbletable.idiom.case43 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 5
  %fuzz.nibbletable.idiom.entry44 = select i1 %fuzz.nibbletable.idiom.case43, i32 203, i32 %fuzz.nibbletable.idiom.entry42
  %fuzz.nibbletable.idiom.case45 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 6
  %fuzz.nibbletable.idiom.entry46 = select i1 %fuzz.nibbletable.idiom.case45, i32 50, i32 %fuzz.nibbletable.idiom.entry44
  %fuzz.nibbletable.idiom.case47 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 7
  %fuzz.nibbletable.idiom.entry48 = select i1 %fuzz.nibbletable.idiom.case47, i32 127, i32 %fuzz.nibbletable.idiom.entry46
  %fuzz.nibbletable.idiom.case49 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 8
  %fuzz.nibbletable.idiom.entry50 = select i1 %fuzz.nibbletable.idiom.case49, i32 169, i32 %fuzz.nibbletable.idiom.entry48
  %fuzz.nibbletable.idiom.case51 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 9
  %fuzz.nibbletable.idiom.entry52 = select i1 %fuzz.nibbletable.idiom.case51, i32 30, i32 %fuzz.nibbletable.idiom.entry50
  %fuzz.nibbletable.idiom.case53 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 10
  %fuzz.nibbletable.idiom.entry54 = select i1 %fuzz.nibbletable.idiom.case53, i32 244, i32 %fuzz.nibbletable.idiom.entry52
  %fuzz.nibbletable.idiom.case55 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 11
  %fuzz.nibbletable.idiom.entry56 = select i1 %fuzz.nibbletable.idiom.case55, i32 200, i32 %fuzz.nibbletable.idiom.entry54
  %fuzz.nibbletable.idiom.case57 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 12
  %fuzz.nibbletable.idiom.entry58 = select i1 %fuzz.nibbletable.idiom.case57, i32 112, i32 %fuzz.nibbletable.idiom.entry56
  %fuzz.nibbletable.idiom.case59 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 13
  %fuzz.nibbletable.idiom.entry60 = select i1 %fuzz.nibbletable.idiom.case59, i32 130, i32 %fuzz.nibbletable.idiom.entry58
  %fuzz.nibbletable.idiom.case61 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 14
  %fuzz.nibbletable.idiom.entry62 = select i1 %fuzz.nibbletable.idiom.case61, i32 95, i32 %fuzz.nibbletable.idiom.entry60
  %fuzz.nibbletable.idiom.case63 = icmp eq i32 %fuzz.nibbletable.idiom.nib32, 15
  %fuzz.nibbletable.idiom.entry64 = select i1 %fuzz.nibbletable.idiom.case63, i32 248, i32 %fuzz.nibbletable.idiom.entry62
  %fuzz.nibbletable.idiom.pop65 = call i32 @llvm.ctpop.i32(i32 %fuzz.nibbletable.idiom.entry64)
  %fuzz.nibbletable.idiom.entry.hi = and i32 %fuzz.nibbletable.idiom.entry64, 240
  %fuzz.nibbletable.idiom.fold.lo = and i32 %fuzz.nibbletable.idiom.fold.xor, 15
  %fuzz.nibbletable.idiom.mix.or = or i32 %fuzz.nibbletable.idiom.entry.hi, %fuzz.nibbletable.idiom.fold.lo
  %fuzz.nibbletable.idiom.fold.add66 = add i32 %fuzz.nibbletable.idiom.fold.xor, %fuzz.nibbletable.idiom.mix.or
  %fuzz.nibbletable.idiom.fold.xor67 = xor i32 %fuzz.nibbletable.idiom.fold.add66, %fuzz.nibbletable.idiom.nib32
  %fuzz.nibbletable.idiom.nib.shr68 = lshr i32 %fuzz.bitrunmask.idiom.sub, 8
  %fuzz.nibbletable.idiom.nib69 = and i32 %fuzz.nibbletable.idiom.nib.shr68, 15
  %fuzz.nibbletable.idiom.case70 = icmp eq i32 %fuzz.nibbletable.idiom.nib69, 0
  %fuzz.nibbletable.idiom.entry71 = select i1 %fuzz.nibbletable.idiom.case70, i32 52, i32 230
  %fuzz.nibbletable.idiom.case72 = icmp eq i32 %fuzz.nibbletable.idiom.nib69, 1
  %fuzz.nibbletable.idiom.entry73 = select i1 %fuzz.nibbletable.idiom.case72, i32 120, i32 %fuzz.nibbletable.idiom.entry71
  %fuzz.nibbletable.idiom.case74 = icmp eq i32 %fuzz.nibbletable.idiom.nib69, 2
  %fuzz.nibbletable.idiom.entry75 = select i1 %fuzz.nibbletable.idiom.case74, i32 31, i32 %fuzz.nibbletable.idiom.entry73
  %fuzz.nibbletable.idiom.case76 = icmp eq i32 %fuzz.nibbletable.idiom.nib69, 3
  %fuzz.nibbletable.idiom.entry77 = select i1 %fuzz.nibbletable.idiom.case76, i32 89, i32 %fuzz.nibbletable.idiom.entry75
  %fuzz.nibbletable.idiom.case78 = icmp eq i32 %fuzz.nibbletable.idiom.nib69, 4
  %fuzz.nibbletable.idiom.entry79 = select i1 %fuzz.nibbletable.idiom.case78, i32 84, i32 %fuzz.nibbletable.idiom.entry77
  %fuzz.nibbletable.idiom.case80 = icmp eq i32 %fuzz.nibbletable.idiom.nib69, 5
  %fuzz.nibbletable.idiom.entry81 = select i1 %fuzz.nibbletable.idiom.case80, i32 222, i32 %fuzz.nibbletable.idiom.entry79
  %fuzz.nibbletable.idiom.case82 = icmp eq i32 %fuzz.nibbletable.idiom.nib69, 6
  %fuzz.nibbletable.idiom.entry83 = select i1 %fuzz.nibbletable.idiom.case82, i32 18, i32 %fuzz.nibbletable.idiom.entry81
  %fuzz.nibbletable.idiom.case84 = icmp eq i32 %fuzz.nibbletable.idiom.nib69, 7
  %fuzz.nibbletable.idiom.entry85 = select i1 %fuzz.nibbletable.idiom.case84, i32 139, i32 %fuzz.nibbletable.idiom.entry83
  %fuzz.nibbletable.idiom.case86 = icmp eq i32 %fuzz.nibbletable.idiom.nib69, 8
  %fuzz.nibbletable.idiom.entry87 = select i1 %fuzz.nibbletable.idiom.case86, i32 217, i32 %fuzz.nibbletable.idiom.entry85
  %fuzz.nibbletable.idiom.case88 = icmp eq i32 %fuzz.nibbletable.idiom.nib69, 9
  %fuzz.nibbletable.idiom.entry89 = select i1 %fuzz.nibbletable.idiom.case88, i32 98, i32 %fuzz.nibbletable.idiom.entry87
  %fuzz.nibbletable.idiom.case90 = icmp eq i32 %fuzz.nibbletable.idiom.nib69, 10
  %fuzz.nibbletable.idiom.entry91 = select i1 %fuzz.nibbletable.idiom.case90, i32 122, i32 %fuzz.nibbletable.idiom.entry89
  %fuzz.nibbletable.idiom.case92 = icmp eq i32 %fuzz.nibbletable.idiom.nib69, 11
  %fuzz.nibbletable.idiom.entry93 = select i1 %fuzz.nibbletable.idiom.case92, i32 181, i32 %fuzz.nibbletable.idiom.entry91
  %fuzz.nibbletable.idiom.case94 = icmp eq i32 %fuzz.nibbletable.idiom.nib69, 12
  %fuzz.nibbletable.idiom.entry95 = select i1 %fuzz.nibbletable.idiom.case94, i32 21, i32 %fuzz.nibbletable.idiom.entry93
  %fuzz.nibbletable.idiom.case96 = icmp eq i32 %fuzz.nibbletable.idiom.nib69, 13
  %fuzz.nibbletable.idiom.entry97 = select i1 %fuzz.nibbletable.idiom.case96, i32 9, i32 %fuzz.nibbletable.idiom.entry95
  %fuzz.nibbletable.idiom.case98 = icmp eq i32 %fuzz.nibbletable.idiom.nib69, 14
  %fuzz.nibbletable.idiom.entry99 = select i1 %fuzz.nibbletable.idiom.case98, i32 78, i32 %fuzz.nibbletable.idiom.entry97
  %fuzz.nibbletable.idiom.case100 = icmp eq i32 %fuzz.nibbletable.idiom.nib69, 15
  %fuzz.nibbletable.idiom.entry101 = select i1 %fuzz.nibbletable.idiom.case100, i32 82, i32 %fuzz.nibbletable.idiom.entry99
  %fuzz.nibbletable.idiom.pop102 = call i32 @llvm.ctpop.i32(i32 %fuzz.nibbletable.idiom.entry101)
  %fuzz.nibbletable.idiom.entry.nz = or i32 %fuzz.nibbletable.idiom.entry101, 1
  %fuzz.nibbletable.idiom.mix.sub = sub i32 %fuzz.nibbletable.idiom.entry.nz, %fuzz.nibbletable.idiom.pop102
  %fuzz.nibbletable.idiom.fold.add103 = add i32 %fuzz.nibbletable.idiom.fold.xor67, %fuzz.nibbletable.idiom.mix.sub
  %fuzz.nibbletable.idiom.fold.xor104 = xor i32 %fuzz.nibbletable.idiom.fold.add103, %fuzz.nibbletable.idiom.nib69
  %fuzz.nibbletable.idiom.nib.shr105 = lshr i32 %fuzz.bitrunmask.idiom.count.b.xor, 12
  %fuzz.nibbletable.idiom.nib106 = and i32 %fuzz.nibbletable.idiom.nib.shr105, 15
  %fuzz.nibbletable.idiom.case107 = icmp eq i32 %fuzz.nibbletable.idiom.nib106, 0
  %fuzz.nibbletable.idiom.entry108 = select i1 %fuzz.nibbletable.idiom.case107, i32 225, i32 78
  %fuzz.nibbletable.idiom.case109 = icmp eq i32 %fuzz.nibbletable.idiom.nib106, 1
  %fuzz.nibbletable.idiom.entry110 = select i1 %fuzz.nibbletable.idiom.case109, i32 126, i32 %fuzz.nibbletable.idiom.entry108
  %fuzz.nibbletable.idiom.case111 = icmp eq i32 %fuzz.nibbletable.idiom.nib106, 2
  %fuzz.nibbletable.idiom.entry112 = select i1 %fuzz.nibbletable.idiom.case111, i32 235, i32 %fuzz.nibbletable.idiom.entry110
  %fuzz.nibbletable.idiom.case113 = icmp eq i32 %fuzz.nibbletable.idiom.nib106, 3
  %fuzz.nibbletable.idiom.entry114 = select i1 %fuzz.nibbletable.idiom.case113, i32 88, i32 %fuzz.nibbletable.idiom.entry112
  %fuzz.nibbletable.idiom.case115 = icmp eq i32 %fuzz.nibbletable.idiom.nib106, 4
  %fuzz.nibbletable.idiom.entry116 = select i1 %fuzz.nibbletable.idiom.case115, i32 46, i32 %fuzz.nibbletable.idiom.entry114
  %fuzz.nibbletable.idiom.case117 = icmp eq i32 %fuzz.nibbletable.idiom.nib106, 5
  %fuzz.nibbletable.idiom.entry118 = select i1 %fuzz.nibbletable.idiom.case117, i32 144, i32 %fuzz.nibbletable.idiom.entry116
  %fuzz.nibbletable.idiom.case119 = icmp eq i32 %fuzz.nibbletable.idiom.nib106, 6
  %fuzz.nibbletable.idiom.entry120 = select i1 %fuzz.nibbletable.idiom.case119, i32 190, i32 %fuzz.nibbletable.idiom.entry118
  %fuzz.nibbletable.idiom.case121 = icmp eq i32 %fuzz.nibbletable.idiom.nib106, 7
  %fuzz.nibbletable.idiom.entry122 = select i1 %fuzz.nibbletable.idiom.case121, i32 54, i32 %fuzz.nibbletable.idiom.entry120
  %fuzz.nibbletable.idiom.case123 = icmp eq i32 %fuzz.nibbletable.idiom.nib106, 8
  %fuzz.nibbletable.idiom.entry124 = select i1 %fuzz.nibbletable.idiom.case123, i32 23, i32 %fuzz.nibbletable.idiom.entry122
  %fuzz.nibbletable.idiom.case125 = icmp eq i32 %fuzz.nibbletable.idiom.nib106, 9
  %fuzz.nibbletable.idiom.entry126 = select i1 %fuzz.nibbletable.idiom.case125, i32 253, i32 %fuzz.nibbletable.idiom.entry124
  %fuzz.nibbletable.idiom.case127 = icmp eq i32 %fuzz.nibbletable.idiom.nib106, 10
  %fuzz.nibbletable.idiom.entry128 = select i1 %fuzz.nibbletable.idiom.case127, i32 10, i32 %fuzz.nibbletable.idiom.entry126
  %fuzz.nibbletable.idiom.case129 = icmp eq i32 %fuzz.nibbletable.idiom.nib106, 11
  %fuzz.nibbletable.idiom.entry130 = select i1 %fuzz.nibbletable.idiom.case129, i32 193, i32 %fuzz.nibbletable.idiom.entry128
  %fuzz.nibbletable.idiom.case131 = icmp eq i32 %fuzz.nibbletable.idiom.nib106, 12
  %fuzz.nibbletable.idiom.entry132 = select i1 %fuzz.nibbletable.idiom.case131, i32 5, i32 %fuzz.nibbletable.idiom.entry130
  %fuzz.nibbletable.idiom.case133 = icmp eq i32 %fuzz.nibbletable.idiom.nib106, 13
  %fuzz.nibbletable.idiom.entry134 = select i1 %fuzz.nibbletable.idiom.case133, i32 244, i32 %fuzz.nibbletable.idiom.entry132
  %fuzz.nibbletable.idiom.case135 = icmp eq i32 %fuzz.nibbletable.idiom.nib106, 14
  %fuzz.nibbletable.idiom.entry136 = select i1 %fuzz.nibbletable.idiom.case135, i32 16, i32 %fuzz.nibbletable.idiom.entry134
  %fuzz.nibbletable.idiom.case137 = icmp eq i32 %fuzz.nibbletable.idiom.nib106, 15
  %fuzz.nibbletable.idiom.entry138 = select i1 %fuzz.nibbletable.idiom.case137, i32 246, i32 %fuzz.nibbletable.idiom.entry136
  %fuzz.nibbletable.idiom.pop139 = call i32 @llvm.ctpop.i32(i32 %fuzz.nibbletable.idiom.entry138)
  %fuzz.nibbletable.idiom.mix.add = add i32 %fuzz.nibbletable.idiom.entry138, %fuzz.nibbletable.idiom.fold.xor104
  %fuzz.nibbletable.idiom.fold.add140 = add i32 %fuzz.nibbletable.idiom.fold.xor104, %fuzz.nibbletable.idiom.mix.add
  %fuzz.nibbletable.idiom.fold.xor141 = xor i32 %fuzz.nibbletable.idiom.fold.add140, %fuzz.nibbletable.idiom.nib106
  %fuzz.nibbletable.idiom.pack.mask = and i32 %fuzz.nibbletable.idiom.mix.xor, 255
  %fuzz.nibbletable.idiom.pack.add = add i32 0, %fuzz.nibbletable.idiom.pack.mask
  %fuzz.nibbletable.idiom.pack.mask142 = and i32 %fuzz.nibbletable.idiom.mix.or, 255
  %fuzz.nibbletable.idiom.pack.shift = shl i32 %fuzz.nibbletable.idiom.pack.mask142, 8
  %fuzz.nibbletable.idiom.pack.add143 = add i32 %fuzz.nibbletable.idiom.pack.add, %fuzz.nibbletable.idiom.pack.shift
  %fuzz.nibbletable.idiom.pack.mask144 = and i32 %fuzz.nibbletable.idiom.mix.sub, 255
  %fuzz.nibbletable.idiom.pack.shift145 = shl i32 %fuzz.nibbletable.idiom.pack.mask144, 16
  %fuzz.nibbletable.idiom.pack.add146 = add i32 %fuzz.nibbletable.idiom.pack.add143, %fuzz.nibbletable.idiom.pack.shift145
  %fuzz.nibbletable.idiom.pack.mask147 = and i32 %fuzz.nibbletable.idiom.mix.add, 255
  %fuzz.nibbletable.idiom.pack.shift148 = shl i32 %fuzz.nibbletable.idiom.pack.mask147, 24
  %fuzz.nibbletable.idiom.pack.add149 = add i32 %fuzz.nibbletable.idiom.pack.add146, %fuzz.nibbletable.idiom.pack.shift148
  %fuzz.nibbletable.idiom.packed.xor = xor i32 %fuzz.nibbletable.idiom.pack.add149, %fuzz.nibbletable.idiom.fold.xor141
  %fuzz.carry.idiom.not.a = xor i32 %fuzz.nibbletable.idiom.packed.xor, -1
  %fuzz.carry.idiom.not.b = xor i32 %fuzz.halfdot.idiom.mul.byte16, -1
  %fuzz.carry.idiom.mask.seed = and i32 %fuzz.nibbletable.idiom.packed.xor, -2147483648
  %fuzz.carry.idiom.keep.a = and i32 %fuzz.nibbletable.idiom.packed.xor, %fuzz.carry.idiom.mask.seed
  %fuzz.carry.idiom.mask.not = xor i32 %fuzz.carry.idiom.mask.seed, -1
  %fuzz.carry.idiom.keep.b = and i32 %fuzz.halfdot.idiom.mul.byte16, %fuzz.carry.idiom.mask.not
  %fuzz.carry.idiom.masked.merge = or i32 %fuzz.carry.idiom.keep.a, %fuzz.carry.idiom.keep.b
  %fuzz.vecpairbyte.idiom.a.byte.trunc = trunc i32 %fuzz.carry.idiom.masked.merge to i8
  %fuzz.vecpairbyte.idiom.a.byte.zext = zext i8 %fuzz.vecpairbyte.idiom.a.byte.trunc to i32
  %fuzz.vecpairbyte.idiom.b.byte.shr = lshr i32 31, 8
  %fuzz.vecpairbyte.idiom.b.byte.trunc = trunc i32 %fuzz.vecpairbyte.idiom.b.byte.shr to i8
  %fuzz.vecpairbyte.idiom.b.byte.zext = zext i8 %fuzz.vecpairbyte.idiom.b.byte.trunc to i32
  %fuzz.vecpairbyte.idiom.a16 = trunc i32 %fuzz.vecpairbyte.idiom.a.byte.zext to i16
  %fuzz.vecpairbyte.idiom.b.xor = xor i32 %fuzz.vecpairbyte.idiom.b.byte.zext, 0
  %fuzz.vecpairbyte.idiom.b16 = trunc i32 %fuzz.vecpairbyte.idiom.b.xor to i16
  %fuzz.vecpairbyte.idiom.a.byte.shr = lshr i32 31, 8
  %fuzz.vecpairbyte.idiom.a.byte.trunc1 = trunc i32 %fuzz.vecpairbyte.idiom.a.byte.shr to i8
  %fuzz.vecpairbyte.idiom.a.byte.zext2 = zext i8 %fuzz.vecpairbyte.idiom.a.byte.trunc1 to i32
  %fuzz.vecpairbyte.idiom.b.byte.shr3 = lshr i32 %fuzz.carry.idiom.masked.merge, 16
  %fuzz.vecpairbyte.idiom.b.byte.trunc4 = trunc i32 %fuzz.vecpairbyte.idiom.b.byte.shr3 to i8
  %fuzz.vecpairbyte.idiom.b.byte.zext5 = zext i8 %fuzz.vecpairbyte.idiom.b.byte.trunc4 to i32
  %fuzz.vecpairbyte.idiom.a166 = trunc i32 %fuzz.vecpairbyte.idiom.a.byte.zext2 to i16
  %fuzz.vecpairbyte.idiom.b.xor7 = xor i32 %fuzz.vecpairbyte.idiom.b.byte.zext5, 13
  %fuzz.vecpairbyte.idiom.b168 = trunc i32 %fuzz.vecpairbyte.idiom.b.xor7 to i16
  %fuzz.vecpairbyte.idiom.a.byte.shr9 = lshr i32 %fuzz.carry.idiom.masked.merge, 16
  %fuzz.vecpairbyte.idiom.a.byte.trunc10 = trunc i32 %fuzz.vecpairbyte.idiom.a.byte.shr9 to i8
  %fuzz.vecpairbyte.idiom.a.byte.zext11 = zext i8 %fuzz.vecpairbyte.idiom.a.byte.trunc10 to i32
  %fuzz.vecpairbyte.idiom.b.byte.shr12 = lshr i32 31, 24
  %fuzz.vecpairbyte.idiom.b.byte.trunc13 = trunc i32 %fuzz.vecpairbyte.idiom.b.byte.shr12 to i8
  %fuzz.vecpairbyte.idiom.b.byte.zext14 = zext i8 %fuzz.vecpairbyte.idiom.b.byte.trunc13 to i32
  %fuzz.vecpairbyte.idiom.a1615 = trunc i32 %fuzz.vecpairbyte.idiom.a.byte.zext11 to i16
  %fuzz.vecpairbyte.idiom.b.xor16 = xor i32 %fuzz.vecpairbyte.idiom.b.byte.zext14, 26
  %fuzz.vecpairbyte.idiom.b1617 = trunc i32 %fuzz.vecpairbyte.idiom.b.xor16 to i16
  %fuzz.vecpairbyte.idiom.a.byte.shr18 = lshr i32 31, 24
  %fuzz.vecpairbyte.idiom.a.byte.trunc19 = trunc i32 %fuzz.vecpairbyte.idiom.a.byte.shr18 to i8
  %fuzz.vecpairbyte.idiom.a.byte.zext20 = zext i8 %fuzz.vecpairbyte.idiom.a.byte.trunc19 to i32
  %fuzz.vecpairbyte.idiom.b.byte.trunc21 = trunc i32 %fuzz.carry.idiom.masked.merge to i8
  %fuzz.vecpairbyte.idiom.b.byte.zext22 = zext i8 %fuzz.vecpairbyte.idiom.b.byte.trunc21 to i32
  %fuzz.vecpairbyte.idiom.a1623 = trunc i32 %fuzz.vecpairbyte.idiom.a.byte.zext20 to i16
  %fuzz.vecpairbyte.idiom.b.xor24 = xor i32 %fuzz.vecpairbyte.idiom.b.byte.zext22, 39
  %fuzz.vecpairbyte.idiom.b1625 = trunc i32 %fuzz.vecpairbyte.idiom.b.xor24 to i16
  %fuzz.vecpairbyte.idiom.a.byte.trunc26 = trunc i32 %fuzz.carry.idiom.masked.merge to i8
  %fuzz.vecpairbyte.idiom.a.byte.zext27 = zext i8 %fuzz.vecpairbyte.idiom.a.byte.trunc26 to i32
  %fuzz.vecpairbyte.idiom.b.byte.shr28 = lshr i32 31, 8
  %fuzz.vecpairbyte.idiom.b.byte.trunc29 = trunc i32 %fuzz.vecpairbyte.idiom.b.byte.shr28 to i8
  %fuzz.vecpairbyte.idiom.b.byte.zext30 = zext i8 %fuzz.vecpairbyte.idiom.b.byte.trunc29 to i32
  %fuzz.vecpairbyte.idiom.a1631 = trunc i32 %fuzz.vecpairbyte.idiom.a.byte.zext27 to i16
  %fuzz.vecpairbyte.idiom.b.xor32 = xor i32 %fuzz.vecpairbyte.idiom.b.byte.zext30, 52
  %fuzz.vecpairbyte.idiom.b1633 = trunc i32 %fuzz.vecpairbyte.idiom.b.xor32 to i16
  %fuzz.vecpairbyte.idiom.a.byte.shr34 = lshr i32 31, 8
  %fuzz.vecpairbyte.idiom.a.byte.trunc35 = trunc i32 %fuzz.vecpairbyte.idiom.a.byte.shr34 to i8
  %fuzz.vecpairbyte.idiom.a.byte.zext36 = zext i8 %fuzz.vecpairbyte.idiom.a.byte.trunc35 to i32
  %fuzz.vecpairbyte.idiom.b.byte.shr37 = lshr i32 %fuzz.carry.idiom.masked.merge, 16
  %fuzz.vecpairbyte.idiom.b.byte.trunc38 = trunc i32 %fuzz.vecpairbyte.idiom.b.byte.shr37 to i8
  %fuzz.vecpairbyte.idiom.b.byte.zext39 = zext i8 %fuzz.vecpairbyte.idiom.b.byte.trunc38 to i32
  %fuzz.vecpairbyte.idiom.a1640 = trunc i32 %fuzz.vecpairbyte.idiom.a.byte.zext36 to i16
  %fuzz.vecpairbyte.idiom.b.xor41 = xor i32 %fuzz.vecpairbyte.idiom.b.byte.zext39, 65
  %fuzz.vecpairbyte.idiom.b1642 = trunc i32 %fuzz.vecpairbyte.idiom.b.xor41 to i16
  %fuzz.vecpairbyte.idiom.a.byte.shr43 = lshr i32 %fuzz.carry.idiom.masked.merge, 16
  %fuzz.vecpairbyte.idiom.a.byte.trunc44 = trunc i32 %fuzz.vecpairbyte.idiom.a.byte.shr43 to i8
  %fuzz.vecpairbyte.idiom.a.byte.zext45 = zext i8 %fuzz.vecpairbyte.idiom.a.byte.trunc44 to i32
  %fuzz.vecpairbyte.idiom.b.byte.shr46 = lshr i32 31, 24
  %fuzz.vecpairbyte.idiom.b.byte.trunc47 = trunc i32 %fuzz.vecpairbyte.idiom.b.byte.shr46 to i8
  %fuzz.vecpairbyte.idiom.b.byte.zext48 = zext i8 %fuzz.vecpairbyte.idiom.b.byte.trunc47 to i32
  %fuzz.vecpairbyte.idiom.a1649 = trunc i32 %fuzz.vecpairbyte.idiom.a.byte.zext45 to i16
  %fuzz.vecpairbyte.idiom.b.xor50 = xor i32 %fuzz.vecpairbyte.idiom.b.byte.zext48, 78
  %fuzz.vecpairbyte.idiom.b1651 = trunc i32 %fuzz.vecpairbyte.idiom.b.xor50 to i16
  %fuzz.vecpairbyte.idiom.a.byte.shr52 = lshr i32 31, 24
  %fuzz.vecpairbyte.idiom.a.byte.trunc53 = trunc i32 %fuzz.vecpairbyte.idiom.a.byte.shr52 to i8
  %fuzz.vecpairbyte.idiom.a.byte.zext54 = zext i8 %fuzz.vecpairbyte.idiom.a.byte.trunc53 to i32
  %fuzz.vecpairbyte.idiom.b.byte.trunc55 = trunc i32 %fuzz.carry.idiom.masked.merge to i8
  %fuzz.vecpairbyte.idiom.b.byte.zext56 = zext i8 %fuzz.vecpairbyte.idiom.b.byte.trunc55 to i32
  %fuzz.vecpairbyte.idiom.a1657 = trunc i32 %fuzz.vecpairbyte.idiom.a.byte.zext54 to i16
  %fuzz.vecpairbyte.idiom.b.xor58 = xor i32 %fuzz.vecpairbyte.idiom.b.byte.zext56, 91
  %fuzz.vecpairbyte.idiom.b1659 = trunc i32 %fuzz.vecpairbyte.idiom.b.xor58 to i16
  %fuzz.vec.ins60 = insertelement <8 x i16> zeroinitializer, i16 %fuzz.vecpairbyte.idiom.a16, i32 0
  %fuzz.vec.ins61 = insertelement <8 x i16> %fuzz.vec.ins60, i16 %fuzz.vecpairbyte.idiom.a166, i32 1
  %fuzz.vec.ins62 = insertelement <8 x i16> %fuzz.vec.ins61, i16 %fuzz.vecpairbyte.idiom.a1615, i32 2
  %fuzz.vec.ins63 = insertelement <8 x i16> %fuzz.vec.ins62, i16 %fuzz.vecpairbyte.idiom.a1623, i32 3
  %fuzz.vec.ins64 = insertelement <8 x i16> %fuzz.vec.ins63, i16 %fuzz.vecpairbyte.idiom.a1631, i32 4
  %fuzz.vec.ins65 = insertelement <8 x i16> %fuzz.vec.ins64, i16 %fuzz.vecpairbyte.idiom.a1640, i32 5
  %fuzz.vec.ins66 = insertelement <8 x i16> %fuzz.vec.ins65, i16 %fuzz.vecpairbyte.idiom.a1649, i32 6
  %fuzz.vec.ins67 = insertelement <8 x i16> %fuzz.vec.ins66, i16 %fuzz.vecpairbyte.idiom.a1657, i32 7
  %fuzz.vec.ins68 = insertelement <8 x i16> zeroinitializer, i16 %fuzz.vecpairbyte.idiom.b16, i32 0
  %fuzz.vec.ins69 = insertelement <8 x i16> %fuzz.vec.ins68, i16 %fuzz.vecpairbyte.idiom.b168, i32 1
  %fuzz.vec.ins70 = insertelement <8 x i16> %fuzz.vec.ins69, i16 %fuzz.vecpairbyte.idiom.b1617, i32 2
  %fuzz.vec.ins71 = insertelement <8 x i16> %fuzz.vec.ins70, i16 %fuzz.vecpairbyte.idiom.b1625, i32 3
  %fuzz.vec.ins72 = insertelement <8 x i16> %fuzz.vec.ins71, i16 %fuzz.vecpairbyte.idiom.b1633, i32 4
  %fuzz.vec.ins73 = insertelement <8 x i16> %fuzz.vec.ins72, i16 %fuzz.vecpairbyte.idiom.b1642, i32 5
  %fuzz.vec.ins74 = insertelement <8 x i16> %fuzz.vec.ins73, i16 %fuzz.vecpairbyte.idiom.b1651, i32 6
  %fuzz.vec.ins75 = insertelement <8 x i16> %fuzz.vec.ins74, i16 %fuzz.vecpairbyte.idiom.b1659, i32 7
  %fuzz.vecpairbyte.idiom.pair = shufflevector <8 x i16> %fuzz.vec.ins67, <8 x i16> %fuzz.vec.ins67, <8 x i32> <i32 1, i32 0, i32 3, i32 2, i32 5, i32 4, i32 7, i32 6>
  %fuzz.vecpairbyte.idiom.rev = shufflevector <8 x i16> %fuzz.vec.ins75, <8 x i16> %fuzz.vec.ins75, <8 x i32> <i32 7, i32 6, i32 5, i32 4, i32 3, i32 2, i32 1, i32 0>
  %fuzz.vecpairbyte.idiom.cmp = icmp ult <8 x i16> %fuzz.vec.ins67, %fuzz.vecpairbyte.idiom.rev
  %fuzz.vecpairbyte.idiom.lo = select <8 x i1> %fuzz.vecpairbyte.idiom.cmp, <8 x i16> %fuzz.vec.ins67, <8 x i16> %fuzz.vecpairbyte.idiom.rev
  %fuzz.vecpairbyte.idiom.hi = select <8 x i1> %fuzz.vecpairbyte.idiom.cmp, <8 x i16> %fuzz.vecpairbyte.idiom.rev, <8 x i16> %fuzz.vec.ins67
  %fuzz.vecpairbyte.idiom.lo.shl = shl <8 x i16> %fuzz.vecpairbyte.idiom.lo, <i16 1, i16 2, i16 3, i16 4, i16 5, i16 6, i16 7, i16 1>
  %fuzz.vecpairbyte.idiom.hi.shr = lshr <8 x i16> %fuzz.vecpairbyte.idiom.hi, <i16 1, i16 2, i16 3, i16 4, i16 5, i16 6, i16 7, i16 1>
  %fuzz.vecpairbyte.idiom.shift.or = or <8 x i16> %fuzz.vecpairbyte.idiom.lo.shl, %fuzz.vecpairbyte.idiom.hi.shr
  %fuzz.vecpairbyte.idiom.lane = extractelement <8 x i16> %fuzz.vecpairbyte.idiom.shift.or, i32 0
  %fuzz.vecpairbyte.idiom.zext = zext i16 %fuzz.vecpairbyte.idiom.lane to i32
  %fuzz.vecpairbyte.idiom.fold.xor = xor i32 0, %fuzz.vecpairbyte.idiom.zext
  %fuzz.vecpairbyte.idiom.byte = lshr i32 %fuzz.vecpairbyte.idiom.zext, 0
  %fuzz.vecpairbyte.idiom.lane76 = extractelement <8 x i16> %fuzz.vecpairbyte.idiom.shift.or, i32 1
  %fuzz.vecpairbyte.idiom.zext77 = zext i16 %fuzz.vecpairbyte.idiom.lane76 to i32
  %fuzz.vecpairbyte.idiom.fold.add = add i32 %fuzz.vecpairbyte.idiom.fold.xor, %fuzz.vecpairbyte.idiom.zext77
  %fuzz.vecpairbyte.idiom.lane78 = extractelement <8 x i16> %fuzz.vecpairbyte.idiom.shift.or, i32 2
  %fuzz.vecpairbyte.idiom.zext79 = zext i16 %fuzz.vecpairbyte.idiom.lane78 to i32
  %fuzz.vecpairbyte.idiom.fold.xor80 = xor i32 %fuzz.vecpairbyte.idiom.fold.add, %fuzz.vecpairbyte.idiom.zext79
  %fuzz.vecpairbyte.idiom.byte81 = lshr i32 %fuzz.vecpairbyte.idiom.zext79, 8
  %fuzz.vecpairbyte.idiom.lane82 = extractelement <8 x i16> %fuzz.vecpairbyte.idiom.shift.or, i32 3
  %fuzz.vecpairbyte.idiom.zext83 = zext i16 %fuzz.vecpairbyte.idiom.lane82 to i32
  %fuzz.vecpairbyte.idiom.fold.add84 = add i32 %fuzz.vecpairbyte.idiom.fold.xor80, %fuzz.vecpairbyte.idiom.zext83
  %fuzz.vecpairbyte.idiom.lane85 = extractelement <8 x i16> %fuzz.vecpairbyte.idiom.shift.or, i32 4
  %fuzz.vecpairbyte.idiom.zext86 = zext i16 %fuzz.vecpairbyte.idiom.lane85 to i32
  %fuzz.vecpairbyte.idiom.fold.xor87 = xor i32 %fuzz.vecpairbyte.idiom.fold.add84, %fuzz.vecpairbyte.idiom.zext86
  %fuzz.vecpairbyte.idiom.byte88 = lshr i32 %fuzz.vecpairbyte.idiom.zext86, 0
  %fuzz.vecpairbyte.idiom.lane89 = extractelement <8 x i16> %fuzz.vecpairbyte.idiom.shift.or, i32 5
  %fuzz.vecpairbyte.idiom.zext90 = zext i16 %fuzz.vecpairbyte.idiom.lane89 to i32
  %fuzz.vecpairbyte.idiom.fold.add91 = add i32 %fuzz.vecpairbyte.idiom.fold.xor87, %fuzz.vecpairbyte.idiom.zext90
  %fuzz.vecpairbyte.idiom.lane92 = extractelement <8 x i16> %fuzz.vecpairbyte.idiom.shift.or, i32 6
  %fuzz.vecpairbyte.idiom.zext93 = zext i16 %fuzz.vecpairbyte.idiom.lane92 to i32
  %fuzz.vecpairbyte.idiom.fold.xor94 = xor i32 %fuzz.vecpairbyte.idiom.fold.add91, %fuzz.vecpairbyte.idiom.zext93
  %fuzz.vecpairbyte.idiom.byte95 = lshr i32 %fuzz.vecpairbyte.idiom.zext93, 8
  %fuzz.vecpairbyte.idiom.lane96 = extractelement <8 x i16> %fuzz.vecpairbyte.idiom.shift.or, i32 7
  %fuzz.vecpairbyte.idiom.zext97 = zext i16 %fuzz.vecpairbyte.idiom.lane96 to i32
  %fuzz.vecpairbyte.idiom.fold.add98 = add i32 %fuzz.vecpairbyte.idiom.fold.xor94, %fuzz.vecpairbyte.idiom.zext97
  %fuzz.vecpairbyte.idiom.pack.mask = and i32 %fuzz.vecpairbyte.idiom.byte, 255
  %fuzz.vecpairbyte.idiom.pack.add = add i32 0, %fuzz.vecpairbyte.idiom.pack.mask
  %fuzz.vecpairbyte.idiom.pack.mask99 = and i32 %fuzz.vecpairbyte.idiom.byte81, 255
  %fuzz.vecpairbyte.idiom.pack.shift = shl i32 %fuzz.vecpairbyte.idiom.pack.mask99, 8
  %fuzz.vecpairbyte.idiom.pack.add100 = add i32 %fuzz.vecpairbyte.idiom.pack.add, %fuzz.vecpairbyte.idiom.pack.shift
  %fuzz.vecpairbyte.idiom.pack.mask101 = and i32 %fuzz.vecpairbyte.idiom.byte88, 255
  %fuzz.vecpairbyte.idiom.pack.shift102 = shl i32 %fuzz.vecpairbyte.idiom.pack.mask101, 16
  %fuzz.vecpairbyte.idiom.pack.add103 = add i32 %fuzz.vecpairbyte.idiom.pack.add100, %fuzz.vecpairbyte.idiom.pack.shift102
  %fuzz.vecpairbyte.idiom.pack.mask104 = and i32 %fuzz.vecpairbyte.idiom.byte95, 255
  %fuzz.vecpairbyte.idiom.pack.shift105 = shl i32 %fuzz.vecpairbyte.idiom.pack.mask104, 24
  %fuzz.vecpairbyte.idiom.pack.add106 = add i32 %fuzz.vecpairbyte.idiom.pack.add103, %fuzz.vecpairbyte.idiom.pack.shift105
  %fuzz.packunpack.idiom.a0.trunc = trunc i32 %fuzz.vecpairbyte.idiom.pack.add106 to i8
  %fuzz.packunpack.idiom.a0.zext = zext i8 %fuzz.packunpack.idiom.a0.trunc to i32
  %fuzz.packunpack.idiom.a1.shr = lshr i32 %fuzz.vecpairbyte.idiom.pack.add106, 8
  %fuzz.packunpack.idiom.a1.trunc = trunc i32 %fuzz.packunpack.idiom.a1.shr to i8
  %fuzz.packunpack.idiom.a1.zext = zext i8 %fuzz.packunpack.idiom.a1.trunc to i32
  %fuzz.packunpack.idiom.a2.shr = lshr i32 %fuzz.vecpairbyte.idiom.pack.add106, 16
  %fuzz.packunpack.idiom.a2.trunc = trunc i32 %fuzz.packunpack.idiom.a2.shr to i8
  %fuzz.packunpack.idiom.a2.zext = zext i8 %fuzz.packunpack.idiom.a2.trunc to i32
  %fuzz.packunpack.idiom.b0.trunc = trunc i32 %fuzz.halfdot.idiom.a.half.sext to i8
  %fuzz.packunpack.idiom.b0.zext = zext i8 %fuzz.packunpack.idiom.b0.trunc to i32
  %fuzz.packunpack.idiom.b1.shr = lshr i32 %fuzz.halfdot.idiom.a.half.sext, 8
  %fuzz.packunpack.idiom.b1.trunc = trunc i32 %fuzz.packunpack.idiom.b1.shr to i8
  %fuzz.packunpack.idiom.b1.zext = zext i8 %fuzz.packunpack.idiom.b1.trunc to i32
  %fuzz.packunpack.idiom.b2.shr = lshr i32 %fuzz.halfdot.idiom.a.half.sext, 16
  %fuzz.packunpack.idiom.b2.trunc = trunc i32 %fuzz.packunpack.idiom.b2.shr to i8
  %fuzz.packunpack.idiom.b2.zext = zext i8 %fuzz.packunpack.idiom.b2.trunc to i32
  %fuzz.packunpack.idiom.byte.mul0 = mul i32 %fuzz.packunpack.idiom.a0.zext, %fuzz.packunpack.idiom.b0.zext
  %fuzz.packunpack.idiom.byte.mul1 = mul i32 %fuzz.packunpack.idiom.a1.zext, %fuzz.packunpack.idiom.b1.zext
  %fuzz.packunpack.idiom.byte.mul2 = mul i32 %fuzz.packunpack.idiom.a2.zext, %fuzz.packunpack.idiom.b2.zext
  %fuzz.packunpack.idiom.byte.sum01 = add i32 %fuzz.packunpack.idiom.byte.mul0, %fuzz.packunpack.idiom.byte.mul1
  %fuzz.packunpack.idiom.byte.sum = add i32 %fuzz.packunpack.idiom.byte.sum01, %fuzz.packunpack.idiom.byte.mul2
  store i32 %fuzz.packunpack.idiom.byte.sum, ptr addrspace(1) %out.ptr, align 4
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef i32 @llvm.amdgcn.workgroup.id.x() #1

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef range(i32 0, 1024) i32 @llvm.amdgcn.workitem.id.x() #1

; Function Attrs: nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none)

; Function Attrs: nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.ctpop.i32(i32) #1

; uselistorder directives
uselistorder ptr @llvm.ctpop.i32, { 3, 2, 1, 0 }

attributes #0 = { convergent nounwind "amdgpu-flat-work-group-size"="1,256" "target-cpu"="gfx950" "uniform-work-group-size"="true" }
attributes #1 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
