export const meta = {
  name: 'nvptx-author-tests',
  description: 'For each remaining NVPTX bug, design a regression test in the canonical existing test file',
  phases: [{ title: 'AuthorTests' }],
}

const BUGS_DIR = '/Users/justinlebar/code/FuzzX/NVPTX/bugs'
const TESTROOT = '/Users/justinlebar/code/llvm2/llvm/test'   // existing NVPTX tests live here
const LLC = '/Users/justinlebar/code/llvm2/build/bin/llc'    // FIXED build (all fixes)
const OPT = '/Users/justinlebar/code/llvm2/build/bin/opt'

const BUGS = Array.isArray(args) ? args : []

const SCHEMA = {
  type: 'object', additionalProperties: false,
  properties: {
    bug: { type: 'string' },
    tool: { type: 'string', enum: ['llc', 'opt'] },
    kind: { type: 'string', enum: ['codegen', 'error', 'compiles'] },
    target_file: { type: 'string' },          // path under .../llvm/test/... ; existing file preferred
    target_is_autogenerated: { type: 'boolean' },
    run_line: { type: 'string' },              // exact "; RUN: ..." line for THIS test
    function_ir: { type: 'string' },           // the test IR (include `target triple` if run_line lacks -mtriple/-march)
    error_checks: { type: 'array', items: { type: 'string' } }, // for kind=error: the "; CHECK..." lines
    check_prefix: { type: 'string' },
    rationale: { type: 'string' },
  },
  required: ['bug', 'tool', 'kind', 'target_file', 'target_is_autogenerated', 'run_line', 'function_ir', 'error_checks', 'check_prefix', 'rationale'],
}

function prompt(bug) {
  return `Design a REGRESSION TEST for one fixed LLVM NVPTX bug. The fix is ALREADY committed; the tools at ${LLC} / ${OPT} are the FIXED build.

Bug folder: ${BUGS_DIR}/${bug}/  — read NOTES.md, repro.ll, cmd.sh.

STEP 1 — run the fixed tool on the repro to see current behavior:
  ${LLC} <flags-from-cmd.sh> ${BUGS_DIR}/${bug}/repro.ll -o -      (or ${OPT} ... for the opt-pass bugs like nvvm-intr-range)
Decide the test KIND:
  - 'codegen': the tool now emits PTX/IR and the test should FileCheck specific output (most miscompiles, and crashes that now compile). The KEY assertion is the corrected instruction/bytes/range.
  - 'error': the tool now exits non-zero with a clean diagnostic ("LLVM ERROR: ..." / "Cannot select" / "cannot be lowered"). Test with \`not llc/opt ... 2>&1 | FileCheck\` and CHECK the diagnostic substring.
  - 'compiles': a crash fix where the meaningful assertion is just "no crash, emits a sane instruction" — treat as 'codegen' with a minimal CHECK.

STEP 2 — pick the TARGET FILE. STRONGLY PREFER an existing canonical NVPTX test file for this feature (search ${TESTROOT}/CodeGen/NVPTX/ and ${TESTROOT}/Transforms/ for the relevant intrinsic/pass/feature; e.g. atomics-*.ll, cvt*.ll, surf*.ll, tex*.ll, ld-st*.ll, param*.ll, aggregate-*.ll, nvvm-intr-range*.ll, global-*.ll, etc.). Report target_is_autogenerated=true if the file's first line is the "; NOTE: Assertions have been autogenerated by utils/update_*_test_checks.py" header.
  IMPORTANT: an 'error' test uses \`not ... | FileCheck\` and CANNOT live in an autogenerated codegen file (update_*_test_checks would clobber it). For an 'error' test, choose an existing NON-autogenerated file for the feature, or if none fits, a focused new file path ${TESTROOT}/CodeGen/NVPTX/<short-name>.ll (note this in rationale).

STEP 3 — produce:
  - tool: llc or opt.
  - run_line: the exact "; RUN: ..." line for THIS test. For codegen it should match the target file's existing RUN flags (so the CHECK prefix lines up). For error: "; RUN: not ${'${'}llc-or-opt} <flags> %s 2>&1 | FileCheck %s" (use plain 'llc'/'opt' in the text; the harness substitutes).
  - function_ir: minimal self-contained IR with a UNIQUELY-NAMED function (prefix it with the feature, e.g. @<feature>_<bug-ish>), plus any needed declares. If run_line has no -mtriple/-march, include \`target triple = "nvptx64-nvidia-cuda"\` at the top (it will be stripped from the appended body for codegen, kept for error).
  - error_checks: for kind='error', the "; CHECK: <substring>" lines asserting the diagnostic (use a stable substring of the real message you observed). Empty array otherwise.
  - check_prefix: usually "CHECK".

Verify your function_ir actually triggers the right behavior by running the fixed tool on it. Return the structured output. Do NOT edit any files.`
}

phase('AuthorTests')

const results = await parallel(BUGS.map(b => () =>
  agent(prompt(b), { label: b.slice(0, 26), phase: 'AuthorTests', schema: SCHEMA })
    .then(r => ({ ...r, bug: b }))
    .catch(e => ({ bug: b, kind: 'error', target_file: '', run_line: '', function_ir: '', error_checks: [], check_prefix: 'CHECK', tool: 'llc', target_is_autogenerated: false, rationale: 'agent error: ' + String(e) }))
))
log(`Authored ${results.filter(r => r.function_ir).length}/${BUGS.length} test designs`)
return { results }
